// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: achievements.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listAchievements = `-- name: ListAchievements :many
select id, title, description, icon, points, sort_order
from public.achievements
order by sort_order
`

func (q *Queries) ListAchievements(ctx context.Context) ([]Achievement, error) {
	rows, err := q.db.Query(ctx, listAchievements)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Achievement{}
	for rows.Next() {
		var i Achievement
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Icon,
			&i.Points,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlockAchievement = `-- name: UnlockAchievement :exec
select public.unlock_achievement($1::uuid, $2)
`

type UnlockAchievementParams struct {
	ProfileID     pgtype.UUID `json:"profile_id"`
	AchievementID string      `json:"achievement_id"`
}

func (q *Queries) UnlockAchievement(ctx context.Context, arg UnlockAchievementParams) error {
	_, err := q.db.Exec(ctx, unlockAchievement, arg.ProfileID, arg.AchievementID)
	return err
}

const unlockedAchievementIDs = `-- name: UnlockedAchievementIDs :many
select achievement_id
from public.profile_achievements
where profile_id = $1::uuid
`

func (q *Queries) UnlockedAchievementIDs(ctx context.Context, profileID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, unlockedAchievementIDs, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var achievement_id string
		if err := rows.Scan(&achievement_id); err != nil {
			return nil, err
		}
		items = append(items, achievement_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
