// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: friends.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addFriend = `-- name: AddFriend :exec
insert into public.friends (profile_id, friend_profile_id, status)
values ($1::uuid, $2::uuid, $3)
on conflict (profile_id, friend_profile_id) do update set status = excluded.status
`

type AddFriendParams struct {
	ProfileID       pgtype.UUID `json:"profile_id"`
	FriendProfileID pgtype.UUID `json:"friend_profile_id"`
	Status          string      `json:"status"`
}

func (q *Queries) AddFriend(ctx context.Context, arg AddFriendParams) error {
	_, err := q.db.Exec(ctx, addFriend, arg.ProfileID, arg.FriendProfileID, arg.Status)
	return err
}

const listFriends = `-- name: ListFriends :many
select profile_id, friend_profile_id, status, created_at
from public.friends
where profile_id = $1::uuid
order by created_at desc
`

func (q *Queries) ListFriends(ctx context.Context, profileID pgtype.UUID) ([]Friend, error) {
	rows, err := q.db.Query(ctx, listFriends, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Friend{}
	for rows.Next() {
		var i Friend
		if err := rows.Scan(
			&i.ProfileID,
			&i.FriendProfileID,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
