// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: games.sql

package postgres

import (
	"context"
)

const getGameByID = `-- name: GetGameByID :one
select id, title, sort_order, active, created_at
from public.games
where id = $1::text
`

func (q *Queries) GetGameByID(ctx context.Context, gameID string) (Game, error) {
	row := q.db.QueryRow(ctx, getGameByID, gameID)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.SortOrder,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveGames = `-- name: ListActiveGames :many
select id, title, sort_order, active, created_at
from public.games
where active = true
order by sort_order, id
`

func (q *Queries) ListActiveGames(ctx context.Context) ([]Game, error) {
	rows, err := q.db.Query(ctx, listActiveGames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Game{}
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.SortOrder,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
