// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: leaderboard.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const leaderboardGame = `-- name: LeaderboardGame :many
select
  row_number() over (order by gs.mmr desc, gs.wins desc) as rank,
  p.id as profile_id,
  p.display_name,
  p.avatar_seed,
  p.level,
  gs.mmr,
  gs.wins,
  gs.losses,
  gs.matches_played
from public.game_stats gs
join public.profiles p on p.id = gs.profile_id
where gs.game_id = $1
order by gs.mmr desc, gs.wins desc
limit $2
`

type LeaderboardGameParams struct {
	Game     string `json:"game"`
	RowLimit int32  `json:"row_limit"`
}

type LeaderboardGameRow struct {
	Rank          int64       `json:"rank"`
	ProfileID     pgtype.UUID `json:"profile_id"`
	DisplayName   string      `json:"display_name"`
	AvatarSeed    string      `json:"avatar_seed"`
	Level         pgtype.Int4 `json:"level"`
	Mmr           int32       `json:"mmr"`
	Wins          int32       `json:"wins"`
	Losses        int32       `json:"losses"`
	MatchesPlayed int32       `json:"matches_played"`
}

func (q *Queries) LeaderboardGame(ctx context.Context, arg LeaderboardGameParams) ([]LeaderboardGameRow, error) {
	rows, err := q.db.Query(ctx, leaderboardGame, arg.Game, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LeaderboardGameRow{}
	for rows.Next() {
		var i LeaderboardGameRow
		if err := rows.Scan(
			&i.Rank,
			&i.ProfileID,
			&i.DisplayName,
			&i.AvatarSeed,
			&i.Level,
			&i.Mmr,
			&i.Wins,
			&i.Losses,
			&i.MatchesPlayed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const leaderboardGlobal = `-- name: LeaderboardGlobal :many
select
  row_number() over (order by p.xp desc) as rank,
  p.id as profile_id,
  p.display_name,
  p.avatar_seed,
  p.level,
  p.xp
from public.profiles p
order by p.xp desc
limit $1
`

type LeaderboardGlobalRow struct {
	Rank        int64       `json:"rank"`
	ProfileID   pgtype.UUID `json:"profile_id"`
	DisplayName string      `json:"display_name"`
	AvatarSeed  string      `json:"avatar_seed"`
	Level       pgtype.Int4 `json:"level"`
	Xp          int32       `json:"xp"`
}

func (q *Queries) LeaderboardGlobal(ctx context.Context, rowLimit int32) ([]LeaderboardGlobalRow, error) {
	rows, err := q.db.Query(ctx, leaderboardGlobal, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LeaderboardGlobalRow{}
	for rows.Next() {
		var i LeaderboardGlobalRow
		if err := rows.Scan(
			&i.Rank,
			&i.ProfileID,
			&i.DisplayName,
			&i.AvatarSeed,
			&i.Level,
			&i.Xp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const leaderboardRecent = `-- name: LeaderboardRecent :many
select
  row_number() over (order by count(*) desc) as rank,
  p.id as profile_id,
  p.display_name,
  p.avatar_seed,
  p.level,
  count(*) as wins
from public.match_participants mp
join public.matches m on m.id = mp.match_id
join public.profiles p on p.id = mp.profile_id
where mp.placement = 1
  and m.ended_at >= $1
  and ($2 is null or m.game_id = $2)
group by p.id, p.display_name, p.avatar_seed, p.level
order by wins desc
limit $3
`

type LeaderboardRecentParams struct {
	Since    pgtype.Timestamptz `json:"since"`
	Game     interface{}        `json:"game"`
	RowLimit int32              `json:"row_limit"`
}

type LeaderboardRecentRow struct {
	Rank        int64       `json:"rank"`
	ProfileID   pgtype.UUID `json:"profile_id"`
	DisplayName string      `json:"display_name"`
	AvatarSeed  string      `json:"avatar_seed"`
	Level       pgtype.Int4 `json:"level"`
	Wins        int64       `json:"wins"`
}

func (q *Queries) LeaderboardRecent(ctx context.Context, arg LeaderboardRecentParams) ([]LeaderboardRecentRow, error) {
	rows, err := q.db.Query(ctx, leaderboardRecent, arg.Since, arg.Game, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LeaderboardRecentRow{}
	for rows.Next() {
		var i LeaderboardRecentRow
		if err := rows.Scan(
			&i.Rank,
			&i.ProfileID,
			&i.DisplayName,
			&i.AvatarSeed,
			&i.Level,
			&i.Wins,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
