// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: learning.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteBookmarksForOwner = `-- name: DeleteBookmarksForOwner :exec
delete from public.bookmarks where profile_id = $1::uuid
`

func (q *Queries) DeleteBookmarksForOwner(ctx context.Context, profileID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBookmarksForOwner, profileID)
	return err
}

const deleteNote = `-- name: DeleteNote :execrows
delete from public.learning_notes
where profile_id = $1::uuid and item_id = $2 and kind = $3
`

type DeleteNoteParams struct {
	ProfileID pgtype.UUID `json:"profile_id"`
	ItemID    string      `json:"item_id"`
	Kind      string      `json:"kind"`
}

func (q *Queries) DeleteNote(ctx context.Context, arg DeleteNoteParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNote, arg.ProfileID, arg.ItemID, arg.Kind)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertBookmark = `-- name: InsertBookmark :exec
insert into public.bookmarks (profile_id, item_id)
values ($1::uuid, $2)
on conflict (profile_id, item_id) do nothing
`

type InsertBookmarkParams struct {
	ProfileID pgtype.UUID `json:"profile_id"`
	ItemID    string      `json:"item_id"`
}

func (q *Queries) InsertBookmark(ctx context.Context, arg InsertBookmarkParams) error {
	_, err := q.db.Exec(ctx, insertBookmark, arg.ProfileID, arg.ItemID)
	return err
}

const insertProblemAttempt = `-- name: InsertProblemAttempt :exec

insert into public.problem_attempts (id, profile_id, problem_id, kind, correct, duration_ms, detail)
values ($1::uuid, $2::uuid, $3,
        $4, $5, $6, $7)
on conflict (id) do nothing
`

type InsertProblemAttemptParams struct {
	ID         pgtype.UUID `json:"id"`
	ProfileID  pgtype.UUID `json:"profile_id"`
	ProblemID  string      `json:"problem_id"`
	Kind       string      `json:"kind"`
	Correct    bool        `json:"correct"`
	DurationMs pgtype.Int4 `json:"duration_ms"`
	Detail     []byte      `json:"detail"`
}

// ---------------------------------------------------------------- problem_attempts
func (q *Queries) InsertProblemAttempt(ctx context.Context, arg InsertProblemAttemptParams) error {
	_, err := q.db.Exec(ctx, insertProblemAttempt,
		arg.ID,
		arg.ProfileID,
		arg.ProblemID,
		arg.Kind,
		arg.Correct,
		arg.DurationMs,
		arg.Detail,
	)
	return err
}

const listBookmarks = `-- name: ListBookmarks :many

select item_id
from public.bookmarks
where profile_id = $1::uuid
order by created_at desc
`

// ---------------------------------------------------------------- bookmarks
func (q *Queries) ListBookmarks(ctx context.Context, profileID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listBookmarks, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var item_id string
		if err := rows.Scan(&item_id); err != nil {
			return nil, err
		}
		items = append(items, item_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueReviews = `-- name: ListDueReviews :many
select problem_id, due, interval_days, reps, fsrs, updated_at
from public.review_schedule
where profile_id = $1::uuid and due <= $2
order by due asc
limit $3
`

type ListDueReviewsParams struct {
	ProfileID pgtype.UUID        `json:"profile_id"`
	At        pgtype.Timestamptz `json:"at"`
	Lim       int32              `json:"lim"`
}

type ListDueReviewsRow struct {
	ProblemID    string             `json:"problem_id"`
	Due          pgtype.Timestamptz `json:"due"`
	IntervalDays int32              `json:"interval_days"`
	Reps         int32              `json:"reps"`
	Fsrs         []byte             `json:"fsrs"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListDueReviews(ctx context.Context, arg ListDueReviewsParams) ([]ListDueReviewsRow, error) {
	rows, err := q.db.Query(ctx, listDueReviews, arg.ProfileID, arg.At, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDueReviewsRow{}
	for rows.Next() {
		var i ListDueReviewsRow
		if err := rows.Scan(
			&i.ProblemID,
			&i.Due,
			&i.IntervalDays,
			&i.Reps,
			&i.Fsrs,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnrollments = `-- name: ListEnrollments :many

select course_id, enrolled_at, last_item_id, progress, completed_at, updated_at
from public.course_enrollments
where profile_id = $1::uuid
order by updated_at desc
`

type ListEnrollmentsRow struct {
	CourseID    string             `json:"course_id"`
	EnrolledAt  pgtype.Timestamptz `json:"enrolled_at"`
	LastItemID  pgtype.Text        `json:"last_item_id"`
	Progress    float32            `json:"progress"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

// ---------------------------------------------------------------- course_enrollments
func (q *Queries) ListEnrollments(ctx context.Context, profileID pgtype.UUID) ([]ListEnrollmentsRow, error) {
	rows, err := q.db.Query(ctx, listEnrollments, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnrollmentsRow{}
	for rows.Next() {
		var i ListEnrollmentsRow
		if err := rows.Scan(
			&i.CourseID,
			&i.EnrolledAt,
			&i.LastItemID,
			&i.Progress,
			&i.CompletedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotes = `-- name: ListNotes :many

select item_id, kind, body, updated_at
from public.learning_notes
where profile_id = $1::uuid
order by updated_at desc
`

type ListNotesRow struct {
	ItemID    string             `json:"item_id"`
	Kind      string             `json:"kind"`
	Body      string             `json:"body"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// ---------------------------------------------------------------- learning_notes
func (q *Queries) ListNotes(ctx context.Context, profileID pgtype.UUID) ([]ListNotesRow, error) {
	rows, err := q.db.Query(ctx, listNotes, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNotesRow{}
	for rows.Next() {
		var i ListNotesRow
		if err := rows.Scan(
			&i.ItemID,
			&i.Kind,
			&i.Body,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProblemProgress = `-- name: ListProblemProgress :many


select problem_id, attempts, correct, streak, best_streak, mastered, last_attempt_at, updated_at
from public.problem_progress
where profile_id = $1::uuid
order by updated_at desc
`

type ListProblemProgressRow struct {
	ProblemID     string             `json:"problem_id"`
	Attempts      int32              `json:"attempts"`
	Correct       int32              `json:"correct"`
	Streak        int32              `json:"streak"`
	BestStreak    int32              `json:"best_streak"`
	Mastered      bool               `json:"mastered"`
	LastAttemptAt pgtype.Timestamptz `json:"last_attempt_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

// Learner-state queries. Server-side merge lives in the ON CONFLICT clauses so a
// concurrent push from a second device converges to the same value the client's
// pure merge produces. Owner-scoped by profile_id on every statement.
// ---------------------------------------------------------------- problem_progress
func (q *Queries) ListProblemProgress(ctx context.Context, profileID pgtype.UUID) ([]ListProblemProgressRow, error) {
	rows, err := q.db.Query(ctx, listProblemProgress, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProblemProgressRow{}
	for rows.Next() {
		var i ListProblemProgressRow
		if err := rows.Scan(
			&i.ProblemID,
			&i.Attempts,
			&i.Correct,
			&i.Streak,
			&i.BestStreak,
			&i.Mastered,
			&i.LastAttemptAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentMistakes = `-- name: ListRecentMistakes :many
select id::text as id, problem_id, kind, correct, duration_ms, detail, created_at
from public.problem_attempts
where profile_id = $1::uuid and correct = false
order by created_at desc
limit $2
`

type ListRecentMistakesParams struct {
	ProfileID pgtype.UUID `json:"profile_id"`
	Lim       int32       `json:"lim"`
}

type ListRecentMistakesRow struct {
	ID         string             `json:"id"`
	ProblemID  string             `json:"problem_id"`
	Kind       string             `json:"kind"`
	Correct    bool               `json:"correct"`
	DurationMs pgtype.Int4        `json:"duration_ms"`
	Detail     []byte             `json:"detail"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListRecentMistakes(ctx context.Context, arg ListRecentMistakesParams) ([]ListRecentMistakesRow, error) {
	rows, err := q.db.Query(ctx, listRecentMistakes, arg.ProfileID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentMistakesRow{}
	for rows.Next() {
		var i ListRecentMistakesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProblemID,
			&i.Kind,
			&i.Correct,
			&i.DurationMs,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewSchedule = `-- name: ListReviewSchedule :many

select problem_id, due, interval_days, reps, fsrs, updated_at
from public.review_schedule
where profile_id = $1::uuid
order by due asc
`

type ListReviewScheduleRow struct {
	ProblemID    string             `json:"problem_id"`
	Due          pgtype.Timestamptz `json:"due"`
	IntervalDays int32              `json:"interval_days"`
	Reps         int32              `json:"reps"`
	Fsrs         []byte             `json:"fsrs"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

// ---------------------------------------------------------------- review_schedule
func (q *Queries) ListReviewSchedule(ctx context.Context, profileID pgtype.UUID) ([]ListReviewScheduleRow, error) {
	rows, err := q.db.Query(ctx, listReviewSchedule, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReviewScheduleRow{}
	for rows.Next() {
		var i ListReviewScheduleRow
		if err := rows.Scan(
			&i.ProblemID,
			&i.Due,
			&i.IntervalDays,
			&i.Reps,
			&i.Fsrs,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEnrollment = `-- name: UpsertEnrollment :one
insert into public.course_enrollments
  (profile_id, course_id, last_item_id, progress, completed_at, updated_at)
values
  ($1::uuid, $2, $3,
   $4, $5, now())
on conflict (profile_id, course_id) do update set
  last_item_id = coalesce(excluded.last_item_id, public.course_enrollments.last_item_id),
  progress     = greatest(public.course_enrollments.progress, excluded.progress),
  completed_at = coalesce(public.course_enrollments.completed_at, excluded.completed_at),
  updated_at   = now()
returning course_id, enrolled_at, last_item_id, progress, completed_at, updated_at
`

type UpsertEnrollmentParams struct {
	ProfileID   pgtype.UUID        `json:"profile_id"`
	CourseID    string             `json:"course_id"`
	LastItemID  pgtype.Text        `json:"last_item_id"`
	Progress    float32            `json:"progress"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

type UpsertEnrollmentRow struct {
	CourseID    string             `json:"course_id"`
	EnrolledAt  pgtype.Timestamptz `json:"enrolled_at"`
	LastItemID  pgtype.Text        `json:"last_item_id"`
	Progress    float32            `json:"progress"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertEnrollment(ctx context.Context, arg UpsertEnrollmentParams) (UpsertEnrollmentRow, error) {
	row := q.db.QueryRow(ctx, upsertEnrollment,
		arg.ProfileID,
		arg.CourseID,
		arg.LastItemID,
		arg.Progress,
		arg.CompletedAt,
	)
	var i UpsertEnrollmentRow
	err := row.Scan(
		&i.CourseID,
		&i.EnrolledAt,
		&i.LastItemID,
		&i.Progress,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertNote = `-- name: UpsertNote :one
insert into public.learning_notes (profile_id, item_id, kind, body, updated_at)
values ($1::uuid, $2, $3, $4, $5)
on conflict (profile_id, item_id, kind) do update set
  body       = excluded.body,
  updated_at = greatest(public.learning_notes.updated_at, excluded.updated_at)
returning item_id, kind, body, updated_at
`

type UpsertNoteParams struct {
	ProfileID pgtype.UUID        `json:"profile_id"`
	ItemID    string             `json:"item_id"`
	Kind      string             `json:"kind"`
	Body      string             `json:"body"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type UpsertNoteRow struct {
	ItemID    string             `json:"item_id"`
	Kind      string             `json:"kind"`
	Body      string             `json:"body"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertNote(ctx context.Context, arg UpsertNoteParams) (UpsertNoteRow, error) {
	row := q.db.QueryRow(ctx, upsertNote,
		arg.ProfileID,
		arg.ItemID,
		arg.Kind,
		arg.Body,
		arg.UpdatedAt,
	)
	var i UpsertNoteRow
	err := row.Scan(
		&i.ItemID,
		&i.Kind,
		&i.Body,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProblemProgress = `-- name: UpsertProblemProgress :one
insert into public.problem_progress
  (profile_id, problem_id, attempts, correct, streak, best_streak, mastered, last_attempt_at, updated_at)
values
  ($1::uuid, $2, $3, $4,
   $5, $6, $7, $8, now())
on conflict (profile_id, problem_id) do update set
  attempts        = greatest(public.problem_progress.attempts, excluded.attempts),
  correct         = least(
                      greatest(public.problem_progress.correct, excluded.correct),
                      greatest(public.problem_progress.attempts, excluded.attempts)),
  best_streak     = greatest(public.problem_progress.best_streak, excluded.best_streak),
  mastered        = public.problem_progress.mastered or excluded.mastered,
  streak          = case
                      when excluded.last_attempt_at is not null
                       and (public.problem_progress.last_attempt_at is null
                            or excluded.last_attempt_at >= public.problem_progress.last_attempt_at)
                      then excluded.streak
                      else public.problem_progress.streak end,
  last_attempt_at = greatest(public.problem_progress.last_attempt_at, excluded.last_attempt_at),
  updated_at      = now()
returning problem_id, attempts, correct, streak, best_streak, mastered, last_attempt_at, updated_at
`

type UpsertProblemProgressParams struct {
	ProfileID     pgtype.UUID        `json:"profile_id"`
	ProblemID     string             `json:"problem_id"`
	Attempts      int32              `json:"attempts"`
	Correct       int32              `json:"correct"`
	Streak        int32              `json:"streak"`
	BestStreak    int32              `json:"best_streak"`
	Mastered      bool               `json:"mastered"`
	LastAttemptAt pgtype.Timestamptz `json:"last_attempt_at"`
}

type UpsertProblemProgressRow struct {
	ProblemID     string             `json:"problem_id"`
	Attempts      int32              `json:"attempts"`
	Correct       int32              `json:"correct"`
	Streak        int32              `json:"streak"`
	BestStreak    int32              `json:"best_streak"`
	Mastered      bool               `json:"mastered"`
	LastAttemptAt pgtype.Timestamptz `json:"last_attempt_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

// Field-wise monotonic merge: counters take the max, mastered latches, streak +
// last_attempt_at come from whichever side attempted most recently.
func (q *Queries) UpsertProblemProgress(ctx context.Context, arg UpsertProblemProgressParams) (UpsertProblemProgressRow, error) {
	row := q.db.QueryRow(ctx, upsertProblemProgress,
		arg.ProfileID,
		arg.ProblemID,
		arg.Attempts,
		arg.Correct,
		arg.Streak,
		arg.BestStreak,
		arg.Mastered,
		arg.LastAttemptAt,
	)
	var i UpsertProblemProgressRow
	err := row.Scan(
		&i.ProblemID,
		&i.Attempts,
		&i.Correct,
		&i.Streak,
		&i.BestStreak,
		&i.Mastered,
		&i.LastAttemptAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertReviewCard = `-- name: UpsertReviewCard :one
insert into public.review_schedule
  (profile_id, problem_id, due, interval_days, reps, fsrs, updated_at)
values
  ($1::uuid, $2, $3,
   $4, $5, $6, now())
on conflict (profile_id, problem_id) do update set
  reps          = greatest(public.review_schedule.reps, excluded.reps),
  due           = case when excluded.reps > public.review_schedule.reps
                         or (excluded.reps = public.review_schedule.reps
                             and excluded.due > public.review_schedule.due)
                       then excluded.due else public.review_schedule.due end,
  interval_days = case when excluded.reps > public.review_schedule.reps
                         or (excluded.reps = public.review_schedule.reps
                             and excluded.due > public.review_schedule.due)
                       then excluded.interval_days else public.review_schedule.interval_days end,
  fsrs          = case when excluded.reps > public.review_schedule.reps
                         or (excluded.reps = public.review_schedule.reps
                             and excluded.due > public.review_schedule.due)
                       then excluded.fsrs else public.review_schedule.fsrs end,
  updated_at    = now()
returning problem_id, due, interval_days, reps, fsrs, updated_at
`

type UpsertReviewCardParams struct {
	ProfileID    pgtype.UUID        `json:"profile_id"`
	ProblemID    string             `json:"problem_id"`
	Due          pgtype.Timestamptz `json:"due"`
	IntervalDays int32              `json:"interval_days"`
	Reps         int32              `json:"reps"`
	Fsrs         []byte             `json:"fsrs"`
}

type UpsertReviewCardRow struct {
	ProblemID    string             `json:"problem_id"`
	Due          pgtype.Timestamptz `json:"due"`
	IntervalDays int32              `json:"interval_days"`
	Reps         int32              `json:"reps"`
	Fsrs         []byte             `json:"fsrs"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

// Higher reps wins; tie -> later due. Mirrors the client mergeSrsCard.
// Whole-card merge: the winner (higher reps, or on a tie the later due) supplies
// due, interval_days AND fsrs together, so the row is never a mix of two cards. This
// mirrors the client mergeSrsCard exactly so both sides converge.
func (q *Queries) UpsertReviewCard(ctx context.Context, arg UpsertReviewCardParams) (UpsertReviewCardRow, error) {
	row := q.db.QueryRow(ctx, upsertReviewCard,
		arg.ProfileID,
		arg.ProblemID,
		arg.Due,
		arg.IntervalDays,
		arg.Reps,
		arg.Fsrs,
	)
	var i UpsertReviewCardRow
	err := row.Scan(
		&i.ProblemID,
		&i.Due,
		&i.IntervalDays,
		&i.Reps,
		&i.Fsrs,
		&i.UpdatedAt,
	)
	return i, err
}
