// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: prep_plans.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPrepPlan = `-- name: CreatePrepPlan :one
insert into public.prep_plans (owner_profile_id, title)
values ($1::uuid, $2)
returning
  id::text,
  owner_profile_id::text,
  title,
  notes,
  created_at,
  updated_at
`

type CreatePrepPlanParams struct {
	OwnerProfileID pgtype.UUID `json:"owner_profile_id"`
	Title          string      `json:"title"`
}

type CreatePrepPlanRow struct {
	ID             string             `json:"id"`
	OwnerProfileID string             `json:"owner_profile_id"`
	Title          string             `json:"title"`
	Notes          string             `json:"notes"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreatePrepPlan(ctx context.Context, arg CreatePrepPlanParams) (CreatePrepPlanRow, error) {
	row := q.db.QueryRow(ctx, createPrepPlan, arg.OwnerProfileID, arg.Title)
	var i CreatePrepPlanRow
	err := row.Scan(
		&i.ID,
		&i.OwnerProfileID,
		&i.Title,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePrepPlan = `-- name: DeletePrepPlan :execrows
delete from public.prep_plans
where id = $1::uuid and owner_profile_id = $2::uuid
`

type DeletePrepPlanParams struct {
	ID             pgtype.UUID `json:"id"`
	OwnerProfileID pgtype.UUID `json:"owner_profile_id"`
}

func (q *Queries) DeletePrepPlan(ctx context.Context, arg DeletePrepPlanParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePrepPlan, arg.ID, arg.OwnerProfileID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePrepPlanItems = `-- name: DeletePrepPlanItems :exec
delete from public.prep_plan_items
where plan_id = $1::uuid
`

func (q *Queries) DeletePrepPlanItems(ctx context.Context, planID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePrepPlanItems, planID)
	return err
}

const getPrepPlanHeader = `-- name: GetPrepPlanHeader :one
select
  id::text,
  owner_profile_id::text,
  title,
  notes,
  created_at,
  updated_at
from public.prep_plans
where id = $1::uuid and owner_profile_id = $2::uuid
`

type GetPrepPlanHeaderParams struct {
	ID             pgtype.UUID `json:"id"`
	OwnerProfileID pgtype.UUID `json:"owner_profile_id"`
}

type GetPrepPlanHeaderRow struct {
	ID             string             `json:"id"`
	OwnerProfileID string             `json:"owner_profile_id"`
	Title          string             `json:"title"`
	Notes          string             `json:"notes"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetPrepPlanHeader(ctx context.Context, arg GetPrepPlanHeaderParams) (GetPrepPlanHeaderRow, error) {
	row := q.db.QueryRow(ctx, getPrepPlanHeader, arg.ID, arg.OwnerProfileID)
	var i GetPrepPlanHeaderRow
	err := row.Scan(
		&i.ID,
		&i.OwnerProfileID,
		&i.Title,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPrepPlanItem = `-- name: InsertPrepPlanItem :exec
insert into public.prep_plan_items (plan_id, item_id, position, completed)
values ($1::uuid, $2, $3, $4)
`

type InsertPrepPlanItemParams struct {
	PlanID    pgtype.UUID `json:"plan_id"`
	ItemID    string      `json:"item_id"`
	Position  int32       `json:"position"`
	Completed bool        `json:"completed"`
}

func (q *Queries) InsertPrepPlanItem(ctx context.Context, arg InsertPrepPlanItemParams) error {
	_, err := q.db.Exec(ctx, insertPrepPlanItem,
		arg.PlanID,
		arg.ItemID,
		arg.Position,
		arg.Completed,
	)
	return err
}

const listPrepPlanItems = `-- name: ListPrepPlanItems :many
select item_id, position, completed
from public.prep_plan_items
where plan_id = $1::uuid
order by position asc
`

type ListPrepPlanItemsRow struct {
	ItemID    string `json:"item_id"`
	Position  int32  `json:"position"`
	Completed bool   `json:"completed"`
}

func (q *Queries) ListPrepPlanItems(ctx context.Context, planID pgtype.UUID) ([]ListPrepPlanItemsRow, error) {
	rows, err := q.db.Query(ctx, listPrepPlanItems, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPrepPlanItemsRow{}
	for rows.Next() {
		var i ListPrepPlanItemsRow
		if err := rows.Scan(&i.ItemID, &i.Position, &i.Completed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrepPlanSummaries = `-- name: ListPrepPlanSummaries :many
select
  p.id::text as id,
  p.title,
  p.updated_at,
  count(i.item_id)::int as item_count,
  count(i.item_id) filter (where i.completed = true)::int as completed_count
from public.prep_plans p
left join public.prep_plan_items i on i.plan_id = p.id
where p.owner_profile_id = $1::uuid
group by p.id, p.title, p.updated_at
order by p.created_at desc
limit 200
`

type ListPrepPlanSummariesRow struct {
	ID             string             `json:"id"`
	Title          string             `json:"title"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ItemCount      int32              `json:"item_count"`
	CompletedCount int32              `json:"completed_count"`
}

func (q *Queries) ListPrepPlanSummaries(ctx context.Context, ownerProfileID pgtype.UUID) ([]ListPrepPlanSummariesRow, error) {
	rows, err := q.db.Query(ctx, listPrepPlanSummaries, ownerProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPrepPlanSummariesRow{}
	for rows.Next() {
		var i ListPrepPlanSummariesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.UpdatedAt,
			&i.ItemCount,
			&i.CompletedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePrepPlanMeta = `-- name: UpdatePrepPlanMeta :one
update public.prep_plans
set
  title = coalesce($1, title),
  notes = coalesce($2, notes),
  updated_at = now()
where id = $3::uuid and owner_profile_id = $4::uuid
returning
  id::text,
  owner_profile_id::text,
  title,
  notes,
  created_at,
  updated_at
`

type UpdatePrepPlanMetaParams struct {
	Title          pgtype.Text `json:"title"`
	Notes          pgtype.Text `json:"notes"`
	ID             pgtype.UUID `json:"id"`
	OwnerProfileID pgtype.UUID `json:"owner_profile_id"`
}

type UpdatePrepPlanMetaRow struct {
	ID             string             `json:"id"`
	OwnerProfileID string             `json:"owner_profile_id"`
	Title          string             `json:"title"`
	Notes          string             `json:"notes"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdatePrepPlanMeta(ctx context.Context, arg UpdatePrepPlanMetaParams) (UpdatePrepPlanMetaRow, error) {
	row := q.db.QueryRow(ctx, updatePrepPlanMeta,
		arg.Title,
		arg.Notes,
		arg.ID,
		arg.OwnerProfileID,
	)
	var i UpdatePrepPlanMetaRow
	err := row.Scan(
		&i.ID,
		&i.OwnerProfileID,
		&i.Title,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
