// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profiles.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEmailProfile = `-- name: CreateEmailProfile :one
insert into public.profiles (
  session_token, is_anonymous, personal_room_code, email, password_hash, display_name
)
values (
  $1,
  false,
  $2,
  $3,
  $4,
  $5
)
returning
  id::text,
  display_name,
  avatar_seed,
  personal_room_code,
  email,
  is_admin,
  is_anonymous,
  xp,
  level,
  created_at,
  updated_at
`

type CreateEmailProfileParams struct {
	SessionToken     pgtype.Text `json:"session_token"`
	PersonalRoomCode pgtype.Text `json:"personal_room_code"`
	Email            pgtype.Text `json:"email"`
	PasswordHash     pgtype.Text `json:"password_hash"`
	DisplayName      string      `json:"display_name"`
}

type CreateEmailProfileRow struct {
	ID               string             `json:"id"`
	DisplayName      string             `json:"display_name"`
	AvatarSeed       string             `json:"avatar_seed"`
	PersonalRoomCode pgtype.Text        `json:"personal_room_code"`
	Email            pgtype.Text        `json:"email"`
	IsAdmin          bool               `json:"is_admin"`
	IsAnonymous      bool               `json:"is_anonymous"`
	Xp               int32              `json:"xp"`
	Level            pgtype.Int4        `json:"level"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateEmailProfile(ctx context.Context, arg CreateEmailProfileParams) (CreateEmailProfileRow, error) {
	row := q.db.QueryRow(ctx, createEmailProfile,
		arg.SessionToken,
		arg.PersonalRoomCode,
		arg.Email,
		arg.PasswordHash,
		arg.DisplayName,
	)
	var i CreateEmailProfileRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.AvatarSeed,
		&i.PersonalRoomCode,
		&i.Email,
		&i.IsAdmin,
		&i.IsAnonymous,
		&i.Xp,
		&i.Level,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGuestProfile = `-- name: CreateGuestProfile :one
insert into public.profiles (session_token, is_anonymous, personal_room_code)
values ($1, true, $2)
returning
  id::text,
  display_name,
  avatar_seed,
  personal_room_code,
  email,
  is_admin,
  is_anonymous,
  xp,
  level,
  created_at,
  updated_at
`

type CreateGuestProfileParams struct {
	SessionToken     pgtype.Text `json:"session_token"`
	PersonalRoomCode pgtype.Text `json:"personal_room_code"`
}

type CreateGuestProfileRow struct {
	ID               string             `json:"id"`
	DisplayName      string             `json:"display_name"`
	AvatarSeed       string             `json:"avatar_seed"`
	PersonalRoomCode pgtype.Text        `json:"personal_room_code"`
	Email            pgtype.Text        `json:"email"`
	IsAdmin          bool               `json:"is_admin"`
	IsAnonymous      bool               `json:"is_anonymous"`
	Xp               int32              `json:"xp"`
	Level            pgtype.Int4        `json:"level"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateGuestProfile(ctx context.Context, arg CreateGuestProfileParams) (CreateGuestProfileRow, error) {
	row := q.db.QueryRow(ctx, createGuestProfile, arg.SessionToken, arg.PersonalRoomCode)
	var i CreateGuestProfileRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.AvatarSeed,
		&i.PersonalRoomCode,
		&i.Email,
		&i.IsAdmin,
		&i.IsAnonymous,
		&i.Xp,
		&i.Level,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfileByEmail = `-- name: GetProfileByEmail :one
select
  id::text,
  display_name,
  avatar_seed,
  personal_room_code,
  email,
  is_admin,
  is_anonymous,
  xp,
  level,
  created_at,
  updated_at,
  password_hash
from public.profiles
where lower(email) = lower($1)
`

type GetProfileByEmailRow struct {
	ID               string             `json:"id"`
	DisplayName      string             `json:"display_name"`
	AvatarSeed       string             `json:"avatar_seed"`
	PersonalRoomCode pgtype.Text        `json:"personal_room_code"`
	Email            pgtype.Text        `json:"email"`
	IsAdmin          bool               `json:"is_admin"`
	IsAnonymous      bool               `json:"is_anonymous"`
	Xp               int32              `json:"xp"`
	Level            pgtype.Int4        `json:"level"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	PasswordHash     pgtype.Text        `json:"password_hash"`
}

func (q *Queries) GetProfileByEmail(ctx context.Context, email string) (GetProfileByEmailRow, error) {
	row := q.db.QueryRow(ctx, getProfileByEmail, email)
	var i GetProfileByEmailRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.AvatarSeed,
		&i.PersonalRoomCode,
		&i.Email,
		&i.IsAdmin,
		&i.IsAnonymous,
		&i.Xp,
		&i.Level,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
	)
	return i, err
}

const getProfileByID = `-- name: GetProfileByID :one
select
  id::text,
  display_name,
  avatar_seed,
  personal_room_code,
  email,
  is_admin,
  is_anonymous,
  xp,
  level,
  created_at,
  updated_at
from public.profiles
where id = $1::uuid
`

type GetProfileByIDRow struct {
	ID               string             `json:"id"`
	DisplayName      string             `json:"display_name"`
	AvatarSeed       string             `json:"avatar_seed"`
	PersonalRoomCode pgtype.Text        `json:"personal_room_code"`
	Email            pgtype.Text        `json:"email"`
	IsAdmin          bool               `json:"is_admin"`
	IsAnonymous      bool               `json:"is_anonymous"`
	Xp               int32              `json:"xp"`
	Level            pgtype.Int4        `json:"level"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetProfileByID(ctx context.Context, id pgtype.UUID) (GetProfileByIDRow, error) {
	row := q.db.QueryRow(ctx, getProfileByID, id)
	var i GetProfileByIDRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.AvatarSeed,
		&i.PersonalRoomCode,
		&i.Email,
		&i.IsAdmin,
		&i.IsAnonymous,
		&i.Xp,
		&i.Level,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfileByToken = `-- name: GetProfileByToken :one
select
  id::text,
  display_name,
  avatar_seed,
  personal_room_code,
  email,
  is_admin,
  is_anonymous,
  xp,
  level,
  created_at,
  updated_at
from public.profiles
where session_token = $1
`

type GetProfileByTokenRow struct {
	ID               string             `json:"id"`
	DisplayName      string             `json:"display_name"`
	AvatarSeed       string             `json:"avatar_seed"`
	PersonalRoomCode pgtype.Text        `json:"personal_room_code"`
	Email            pgtype.Text        `json:"email"`
	IsAdmin          bool               `json:"is_admin"`
	IsAnonymous      bool               `json:"is_anonymous"`
	Xp               int32              `json:"xp"`
	Level            pgtype.Int4        `json:"level"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetProfileByToken(ctx context.Context, sessionToken pgtype.Text) (GetProfileByTokenRow, error) {
	row := q.db.QueryRow(ctx, getProfileByToken, sessionToken)
	var i GetProfileByTokenRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.AvatarSeed,
		&i.PersonalRoomCode,
		&i.Email,
		&i.IsAdmin,
		&i.IsAnonymous,
		&i.Xp,
		&i.Level,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfileOpenAIKeyEnc = `-- name: GetProfileOpenAIKeyEnc :one
select openai_api_key_enc
from public.profiles
where id = $1::uuid
`

func (q *Queries) GetProfileOpenAIKeyEnc(ctx context.Context, id pgtype.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getProfileOpenAIKeyEnc, id)
	var openai_api_key_enc []byte
	err := row.Scan(&openai_api_key_enc)
	return openai_api_key_enc, err
}

const listProfilesByIDs = `-- name: ListProfilesByIDs :many
select
  id::text,
  display_name,
  avatar_seed,
  personal_room_code,
  email,
  is_admin,
  is_anonymous,
  xp,
  level,
  created_at,
  updated_at
from public.profiles
where id = any($1::uuid[])
`

type ListProfilesByIDsRow struct {
	ID               string             `json:"id"`
	DisplayName      string             `json:"display_name"`
	AvatarSeed       string             `json:"avatar_seed"`
	PersonalRoomCode pgtype.Text        `json:"personal_room_code"`
	Email            pgtype.Text        `json:"email"`
	IsAdmin          bool               `json:"is_admin"`
	IsAnonymous      bool               `json:"is_anonymous"`
	Xp               int32              `json:"xp"`
	Level            pgtype.Int4        `json:"level"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListProfilesByIDs(ctx context.Context, ids []pgtype.UUID) ([]ListProfilesByIDsRow, error) {
	rows, err := q.db.Query(ctx, listProfilesByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProfilesByIDsRow{}
	for rows.Next() {
		var i ListProfilesByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.AvatarSeed,
			&i.PersonalRoomCode,
			&i.Email,
			&i.IsAdmin,
			&i.IsAnonymous,
			&i.Xp,
			&i.Level,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rotateSessionToken = `-- name: RotateSessionToken :one
update public.profiles
set session_token = $1
where id = $2::uuid
returning
  id::text,
  display_name,
  avatar_seed,
  personal_room_code,
  email,
  is_admin,
  is_anonymous,
  xp,
  level,
  created_at,
  updated_at
`

type RotateSessionTokenParams struct {
	SessionToken pgtype.Text `json:"session_token"`
	ID           pgtype.UUID `json:"id"`
}

type RotateSessionTokenRow struct {
	ID               string             `json:"id"`
	DisplayName      string             `json:"display_name"`
	AvatarSeed       string             `json:"avatar_seed"`
	PersonalRoomCode pgtype.Text        `json:"personal_room_code"`
	Email            pgtype.Text        `json:"email"`
	IsAdmin          bool               `json:"is_admin"`
	IsAnonymous      bool               `json:"is_anonymous"`
	Xp               int32              `json:"xp"`
	Level            pgtype.Int4        `json:"level"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) RotateSessionToken(ctx context.Context, arg RotateSessionTokenParams) (RotateSessionTokenRow, error) {
	row := q.db.QueryRow(ctx, rotateSessionToken, arg.SessionToken, arg.ID)
	var i RotateSessionTokenRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.AvatarSeed,
		&i.PersonalRoomCode,
		&i.Email,
		&i.IsAdmin,
		&i.IsAnonymous,
		&i.Xp,
		&i.Level,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setAdminByEmail = `-- name: SetAdminByEmail :execrows
update public.profiles
set is_admin = true
where lower(email) = lower($1)
`

func (q *Queries) SetAdminByEmail(ctx context.Context, email string) (int64, error) {
	result, err := q.db.Exec(ctx, setAdminByEmail, email)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setProfileOpenAIKey = `-- name: SetProfileOpenAIKey :exec
update public.profiles
set openai_api_key_enc = $1
where id = $2::uuid
`

type SetProfileOpenAIKeyParams struct {
	OpenaiApiKeyEnc []byte      `json:"openai_api_key_enc"`
	ID              pgtype.UUID `json:"id"`
}

func (q *Queries) SetProfileOpenAIKey(ctx context.Context, arg SetProfileOpenAIKeyParams) error {
	_, err := q.db.Exec(ctx, setProfileOpenAIKey, arg.OpenaiApiKeyEnc, arg.ID)
	return err
}

const updatePasswordHashByEmail = `-- name: UpdatePasswordHashByEmail :execrows
update public.profiles
set password_hash = $1
where lower(email) = lower($2)
`

type UpdatePasswordHashByEmailParams struct {
	PasswordHash pgtype.Text `json:"password_hash"`
	Email        string      `json:"email"`
}

func (q *Queries) UpdatePasswordHashByEmail(ctx context.Context, arg UpdatePasswordHashByEmailParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePasswordHashByEmail, arg.PasswordHash, arg.Email)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateProfile = `-- name: UpdateProfile :one
update public.profiles
set
  display_name = coalesce($1, display_name),
  avatar_seed = coalesce($2, avatar_seed)
where id = $3::uuid
returning
  id::text,
  display_name,
  avatar_seed,
  personal_room_code,
  email,
  is_admin,
  is_anonymous,
  xp,
  level,
  created_at,
  updated_at
`

type UpdateProfileParams struct {
	DisplayName pgtype.Text `json:"display_name"`
	AvatarSeed  pgtype.Text `json:"avatar_seed"`
	ID          pgtype.UUID `json:"id"`
}

type UpdateProfileRow struct {
	ID               string             `json:"id"`
	DisplayName      string             `json:"display_name"`
	AvatarSeed       string             `json:"avatar_seed"`
	PersonalRoomCode pgtype.Text        `json:"personal_room_code"`
	Email            pgtype.Text        `json:"email"`
	IsAdmin          bool               `json:"is_admin"`
	IsAnonymous      bool               `json:"is_anonymous"`
	Xp               int32              `json:"xp"`
	Level            pgtype.Int4        `json:"level"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (UpdateProfileRow, error) {
	row := q.db.QueryRow(ctx, updateProfile, arg.DisplayName, arg.AvatarSeed, arg.ID)
	var i UpdateProfileRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.AvatarSeed,
		&i.PersonalRoomCode,
		&i.Email,
		&i.IsAdmin,
		&i.IsAnonymous,
		&i.Xp,
		&i.Level,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
