// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddFriend(ctx context.Context, arg AddFriendParams) error
	ContentCourses(ctx context.Context) ([]ContentCoursesRow, error)
	ContentItems(ctx context.Context) ([]ContentItemsRow, error)
	ContentProblemByID(ctx context.Context, id string) (ContentProblemByIDRow, error)
	ContentProblemQuizChoices(ctx context.Context, problemID pgtype.Text) ([]ContentProblemQuizChoicesRow, error)
	ContentProblemQuizQuestions(ctx context.Context, problemID pgtype.Text) ([]ContentProblemQuizQuestionsRow, error)
	ContentProblemSolutions(ctx context.Context, problemID string) ([]ContentProblemSolutionsRow, error)
	ContentProblemTags(ctx context.Context, problemID string) ([]string, error)
	ContentTopics(ctx context.Context) ([]ContentTopicsRow, error)
	CreateCanvas(ctx context.Context, arg CreateCanvasParams) (CreateCanvasRow, error)
	CreateEmailProfile(ctx context.Context, arg CreateEmailProfileParams) (CreateEmailProfileRow, error)
	CreateGuestProfile(ctx context.Context, arg CreateGuestProfileParams) (CreateGuestProfileRow, error)
	CreateInterviewSession(ctx context.Context, arg CreateInterviewSessionParams) (CreateInterviewSessionRow, error)
	CreatePrepPlan(ctx context.Context, arg CreatePrepPlanParams) (CreatePrepPlanRow, error)
	CreateResume(ctx context.Context, arg CreateResumeParams) (CreateResumeRow, error)
	CreateResumeVariant(ctx context.Context, arg CreateResumeVariantParams) (CreateResumeVariantRow, error)
	DeleteCanvas(ctx context.Context, arg DeleteCanvasParams) (int64, error)
	DeletePrepPlan(ctx context.Context, arg DeletePrepPlanParams) (int64, error)
	DeletePrepPlanItems(ctx context.Context, planID pgtype.UUID) error
	DeleteResume(ctx context.Context, arg DeleteResumeParams) (int64, error)
	DeleteResumeVariant(ctx context.Context, arg DeleteResumeVariantParams) (int64, error)
	EndInterviewSession(ctx context.Context, arg EndInterviewSessionParams) (EndInterviewSessionRow, error)
	GameStatsByProfile(ctx context.Context, profileID pgtype.UUID) ([]GameStat, error)
	GetCanvas(ctx context.Context, id pgtype.UUID) (GetCanvasRow, error)
	GetGameByID(ctx context.Context, gameID string) (Game, error)
	GetInterviewSession(ctx context.Context, id pgtype.UUID) (GetInterviewSessionRow, error)
	GetInterviewSessionByToken(ctx context.Context, guestToken string) (GetInterviewSessionByTokenRow, error)
	GetOrCreateDailyChallenge(ctx context.Context, challengeDate pgtype.Date) (DailyChallenge, error)
	GetPrepPlanHeader(ctx context.Context, arg GetPrepPlanHeaderParams) (GetPrepPlanHeaderRow, error)
	GetProfileByEmail(ctx context.Context, email string) (GetProfileByEmailRow, error)
	GetProfileByID(ctx context.Context, id pgtype.UUID) (GetProfileByIDRow, error)
	GetProfileByToken(ctx context.Context, sessionToken pgtype.Text) (GetProfileByTokenRow, error)
	GetProfileOpenAIKeyEnc(ctx context.Context, id pgtype.UUID) ([]byte, error)
	GetResumeByID(ctx context.Context, id pgtype.UUID) (GetResumeByIDRow, error)
	GetResumeByIDForOwner(ctx context.Context, arg GetResumeByIDForOwnerParams) (GetResumeByIDForOwnerRow, error)
	GetRoom(ctx context.Context, code string) (Room, error)
	InsertPrepPlanItem(ctx context.Context, arg InsertPrepPlanItemParams) error
	LeaderboardGame(ctx context.Context, arg LeaderboardGameParams) ([]LeaderboardGameRow, error)
	LeaderboardGlobal(ctx context.Context, rowLimit int32) ([]LeaderboardGlobalRow, error)
	LeaderboardRecent(ctx context.Context, arg LeaderboardRecentParams) ([]LeaderboardRecentRow, error)
	ListAchievements(ctx context.Context) ([]Achievement, error)
	ListActiveGames(ctx context.Context) ([]Game, error)
	ListCanvases(ctx context.Context, ownerProfileID pgtype.UUID) ([]ListCanvasesRow, error)
	ListFriends(ctx context.Context, profileID pgtype.UUID) ([]Friend, error)
	ListInterviewSummaries(ctx context.Context, ownerProfileID pgtype.UUID) ([]ListInterviewSummariesRow, error)
	ListPrepPlanItems(ctx context.Context, planID pgtype.UUID) ([]ListPrepPlanItemsRow, error)
	ListPrepPlanSummaries(ctx context.Context, ownerProfileID pgtype.UUID) ([]ListPrepPlanSummariesRow, error)
	ListProfilesByIDs(ctx context.Context, ids []pgtype.UUID) ([]ListProfilesByIDsRow, error)
	ListPublicResumeDirectory(ctx context.Context) ([]ListPublicResumeDirectoryRow, error)
	ListPublicRooms(ctx context.Context, rowLimit int32) ([]Room, error)
	ListResumeSummaries(ctx context.Context, ownerProfileID pgtype.UUID) ([]ListResumeSummariesRow, error)
	ListResumeVariants(ctx context.Context, arg ListResumeVariantsParams) ([]ListResumeVariantsRow, error)
	MatchHistory(ctx context.Context, arg MatchHistoryParams) ([]MatchHistoryRow, error)
	ReopenInterviewSession(ctx context.Context, arg ReopenInterviewSessionParams) (ReopenInterviewSessionRow, error)
	RotateInterviewToken(ctx context.Context, arg RotateInterviewTokenParams) (RotateInterviewTokenRow, error)
	RotateSessionToken(ctx context.Context, arg RotateSessionTokenParams) (RotateSessionTokenRow, error)
	SetAdminByEmail(ctx context.Context, email string) (int64, error)
	SetProfileOpenAIKey(ctx context.Context, arg SetProfileOpenAIKeyParams) error
	SubmitDailyScore(ctx context.Context, arg SubmitDailyScoreParams) error
	SubmitMatchResult(ctx context.Context, arg SubmitMatchResultParams) ([]byte, error)
	TouchRoom(ctx context.Context, code string) error
	UnlockAchievement(ctx context.Context, arg UnlockAchievementParams) error
	UnlockedAchievementIDs(ctx context.Context, profileID pgtype.UUID) ([]string, error)
	UpdateCanvas(ctx context.Context, arg UpdateCanvasParams) (pgtype.Timestamptz, error)
	UpdatePasswordHashByEmail(ctx context.Context, arg UpdatePasswordHashByEmailParams) (int64, error)
	UpdatePrepPlanMeta(ctx context.Context, arg UpdatePrepPlanMetaParams) (UpdatePrepPlanMetaRow, error)
	UpdateProfile(ctx context.Context, arg UpdateProfileParams) (UpdateProfileRow, error)
	UpdateResume(ctx context.Context, arg UpdateResumeParams) (UpdateResumeRow, error)
	UpsertRoom(ctx context.Context, arg UpsertRoomParams) (Room, error)
}

var _ Querier = (*Queries)(nil)
