// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rooms.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRoom = `-- name: GetRoom :one
select code, host_profile_id, title, game_id, mode, capacity, is_public, created_at, last_active_at
from public.rooms
where code = $1
`

func (q *Queries) GetRoom(ctx context.Context, code string) (Room, error) {
	row := q.db.QueryRow(ctx, getRoom, code)
	var i Room
	err := row.Scan(
		&i.Code,
		&i.HostProfileID,
		&i.Title,
		&i.GameID,
		&i.Mode,
		&i.Capacity,
		&i.IsPublic,
		&i.CreatedAt,
		&i.LastActiveAt,
	)
	return i, err
}

const listPublicRooms = `-- name: ListPublicRooms :many
select code, host_profile_id, title, game_id, mode, capacity, is_public, created_at, last_active_at
from public.rooms
where is_public = true
order by last_active_at desc
limit $1
`

func (q *Queries) ListPublicRooms(ctx context.Context, rowLimit int32) ([]Room, error) {
	rows, err := q.db.Query(ctx, listPublicRooms, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Room{}
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.Code,
			&i.HostProfileID,
			&i.Title,
			&i.GameID,
			&i.Mode,
			&i.Capacity,
			&i.IsPublic,
			&i.CreatedAt,
			&i.LastActiveAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchRoom = `-- name: TouchRoom :exec
update public.rooms
set last_active_at = now()
where code = $1
`

func (q *Queries) TouchRoom(ctx context.Context, code string) error {
	_, err := q.db.Exec(ctx, touchRoom, code)
	return err
}

const upsertRoom = `-- name: UpsertRoom :one
insert into public.rooms (code, host_profile_id, title, game_id, mode, capacity, is_public, last_active_at)
values (
  $1,
  $2::uuid,
  nullif($3, ''),
  nullif($4, ''),
  $5,
  $6::int,
  $7,
  now()
)
on conflict (code) do update set
  host_profile_id = coalesce(excluded.host_profile_id, public.rooms.host_profile_id),
  title = coalesce(excluded.title, public.rooms.title),
  game_id = coalesce(excluded.game_id, public.rooms.game_id),
  mode = coalesce(excluded.mode, public.rooms.mode),
  capacity = coalesce(excluded.capacity, public.rooms.capacity),
  is_public = coalesce(excluded.is_public, public.rooms.is_public),
  last_active_at = now()
returning code, host_profile_id, title, game_id, mode, capacity, is_public, created_at, last_active_at
`

type UpsertRoomParams struct {
	Code          string      `json:"code"`
	HostProfileID pgtype.UUID `json:"host_profile_id"`
	Title         interface{} `json:"title"`
	GameID        interface{} `json:"game_id"`
	Mode          string      `json:"mode"`
	Capacity      int32       `json:"capacity"`
	IsPublic      bool        `json:"is_public"`
}

func (q *Queries) UpsertRoom(ctx context.Context, arg UpsertRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, upsertRoom,
		arg.Code,
		arg.HostProfileID,
		arg.Title,
		arg.GameID,
		arg.Mode,
		arg.Capacity,
		arg.IsPublic,
	)
	var i Room
	err := row.Scan(
		&i.Code,
		&i.HostProfileID,
		&i.Title,
		&i.GameID,
		&i.Mode,
		&i.Capacity,
		&i.IsPublic,
		&i.CreatedAt,
		&i.LastActiveAt,
	)
	return i, err
}
