// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const gameStatsByProfile = `-- name: GameStatsByProfile :many
select
  profile_id,
  game_id,
  mmr,
  wins,
  losses,
  draws,
  streak,
  best_streak,
  matches_played,
  updated_at
from public.game_stats
where profile_id = $1::uuid
`

func (q *Queries) GameStatsByProfile(ctx context.Context, profileID pgtype.UUID) ([]GameStat, error) {
	rows, err := q.db.Query(ctx, gameStatsByProfile, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GameStat{}
	for rows.Next() {
		var i GameStat
		if err := rows.Scan(
			&i.ProfileID,
			&i.GameID,
			&i.Mmr,
			&i.Wins,
			&i.Losses,
			&i.Draws,
			&i.Streak,
			&i.BestStreak,
			&i.MatchesPlayed,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const matchHistory = `-- name: MatchHistory :many
select
  mp.id,
  mp.match_id,
  mp.profile_id,
  mp.display_name,
  mp.placement,
  mp.score,
  mp.mmr_before,
  mp.mmr_after,
  mp.created_at,
  row_to_json(m.*) as match
from public.match_participants mp
join public.matches m on m.id = mp.match_id
where mp.profile_id = $1::uuid
order by mp.created_at desc
limit $2
`

type MatchHistoryParams struct {
	ProfileID pgtype.UUID `json:"profile_id"`
	RowLimit  int32       `json:"row_limit"`
}

type MatchHistoryRow struct {
	ID          pgtype.UUID        `json:"id"`
	MatchID     pgtype.UUID        `json:"match_id"`
	ProfileID   pgtype.UUID        `json:"profile_id"`
	DisplayName string             `json:"display_name"`
	Placement   int32              `json:"placement"`
	Score       int32              `json:"score"`
	MmrBefore   pgtype.Int4        `json:"mmr_before"`
	MmrAfter    pgtype.Int4        `json:"mmr_after"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Match       []byte             `json:"match"`
}

func (q *Queries) MatchHistory(ctx context.Context, arg MatchHistoryParams) ([]MatchHistoryRow, error) {
	rows, err := q.db.Query(ctx, matchHistory, arg.ProfileID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MatchHistoryRow{}
	for rows.Next() {
		var i MatchHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.ProfileID,
			&i.DisplayName,
			&i.Placement,
			&i.Score,
			&i.MmrBefore,
			&i.MmrAfter,
			&i.CreatedAt,
			&i.Match,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const submitMatchResult = `-- name: SubmitMatchResult :one
select public.submit_match_result(
  $1,
  $2,
  $3,
  $4::jsonb,
  $5::jsonb
)::jsonb as result
`

type SubmitMatchResultParams struct {
	Game         string `json:"game"`
	Room         string `json:"room"`
	Mode         string `json:"mode"`
	Participants []byte `json:"participants"`
	Metadata     []byte `json:"metadata"`
}

func (q *Queries) SubmitMatchResult(ctx context.Context, arg SubmitMatchResultParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, submitMatchResult,
		arg.Game,
		arg.Room,
		arg.Mode,
		arg.Participants,
		arg.Metadata,
	)
	var result []byte
	err := row.Scan(&result)
	return result, err
}
