// AUTO-GENERATED by scripts/build-plugin-meta.mts — do not edit by hand.
// Run `npm run build-plugin-meta` after changing any plugin metadata or catalog.
import type { CourseDef } from '@/content/types';

export const GO_COURSE_ID = "go-senior";

export const IMPORTED_COURSES: CourseDef[] = [
  {
    "id": "lib-graph",
    "title": "Graph library",
    "summary": "32 reference solutions imported from your Go practice repo.",
    "icon": "Network",
    "topics": [
      {
        "id": "lib-graph-all",
        "title": "Reference problems",
        "summary": "32 imported reference solutions",
        "items": [
          {
            "id": "imp-0-01-bfs-shortest-reach",
            "kind": "problem",
            "pluginId": "imp-0-01-bfs-shortest-reach",
            "status": "todo"
          },
          {
            "id": "imp-0-02-clone-graph",
            "kind": "problem",
            "pluginId": "imp-0-02-clone-graph",
            "status": "todo"
          },
          {
            "id": "imp-0-03-find-shortest-path-with-bfs",
            "kind": "problem",
            "pluginId": "imp-0-03-find-shortest-path-with-bfs",
            "status": "todo"
          },
          {
            "id": "imp-0-04-graph-traversal",
            "kind": "problem",
            "pluginId": "imp-0-04-graph-traversal",
            "status": "todo"
          },
          {
            "id": "imp-0-05-has-path-from-source-to-destination",
            "kind": "problem",
            "pluginId": "imp-0-05-has-path-from-source-to-destination",
            "status": "todo"
          },
          {
            "id": "imp-0-06-print-all-paths-from-source-to-destination",
            "kind": "problem",
            "pluginId": "imp-0-06-print-all-paths-from-source-to-destination",
            "status": "todo"
          },
          {
            "id": "imp-0-07-shortest-distance-from-all-buildings",
            "kind": "problem",
            "pluginId": "imp-0-07-shortest-distance-from-all-buildings",
            "status": "todo"
          },
          {
            "id": "imp-0-08-topological-sort-with-dfs",
            "kind": "problem",
            "pluginId": "imp-0-08-topological-sort-with-dfs",
            "status": "todo"
          },
          {
            "id": "imp-1-subset-component",
            "kind": "problem",
            "pluginId": "imp-1-subset-component",
            "status": "todo"
          },
          {
            "id": "imp-2-alien-dictionary",
            "kind": "problem",
            "pluginId": "imp-2-alien-dictionary",
            "status": "todo"
          },
          {
            "id": "imp-3-remove-invalid-parentheses",
            "kind": "problem",
            "pluginId": "imp-3-remove-invalid-parentheses",
            "status": "todo"
          },
          {
            "id": "imp-4-floyd-city-of-blinding-lights",
            "kind": "problem",
            "pluginId": "imp-4-floyd-city-of-blinding-lights",
            "status": "todo"
          },
          {
            "id": "imp-5-swim-in-rising-water",
            "kind": "problem",
            "pluginId": "imp-5-swim-in-rising-water",
            "status": "todo"
          },
          {
            "id": "imp-6-find-shortest-path-with-dijkstra-s",
            "kind": "problem",
            "pluginId": "imp-6-find-shortest-path-with-dijkstra-s",
            "status": "todo"
          },
          {
            "id": "imp-7-is-graph-bipartite",
            "kind": "problem",
            "pluginId": "imp-7-is-graph-bipartite",
            "status": "todo"
          },
          {
            "id": "imp-8-merging-communities",
            "kind": "problem",
            "pluginId": "imp-8-merging-communities",
            "status": "todo"
          },
          {
            "id": "imp-9-similar-string-groups",
            "kind": "problem",
            "pluginId": "imp-9-similar-string-groups",
            "status": "todo"
          },
          {
            "id": "imp-10-word-ladder",
            "kind": "problem",
            "pluginId": "imp-10-word-ladder",
            "status": "todo"
          },
          {
            "id": "imp-11-shortest-path-in-a-grid-with-obstacles-eliminati",
            "kind": "problem",
            "pluginId": "imp-11-shortest-path-in-a-grid-with-obstacles-eliminati",
            "status": "todo"
          },
          {
            "id": "imp-12-shortest-path-in-binary-matrix",
            "kind": "problem",
            "pluginId": "imp-12-shortest-path-in-binary-matrix",
            "status": "todo"
          },
          {
            "id": "imp-13-robot-room-cleaner",
            "kind": "problem",
            "pluginId": "imp-13-robot-room-cleaner",
            "status": "todo"
          },
          {
            "id": "imp-14-the-earliest-moment-when-everyone-become-friends",
            "kind": "problem",
            "pluginId": "imp-14-the-earliest-moment-when-everyone-become-friends",
            "status": "todo"
          },
          {
            "id": "imp-15-find-all-possible-recipes-from-given-supplies",
            "kind": "problem",
            "pluginId": "imp-15-find-all-possible-recipes-from-given-supplies",
            "status": "todo"
          },
          {
            "id": "imp-16-detonate-the-maximum-bombs",
            "kind": "problem",
            "pluginId": "imp-16-detonate-the-maximum-bombs",
            "status": "todo"
          },
          {
            "id": "imp-17-maximal-network-rank",
            "kind": "problem",
            "pluginId": "imp-17-maximal-network-rank",
            "status": "todo"
          },
          {
            "id": "imp-18-number-of-good-paths",
            "kind": "problem",
            "pluginId": "imp-18-number-of-good-paths",
            "status": "todo"
          },
          {
            "id": "imp-19-maximum-score-of-a-node-sequence",
            "kind": "problem",
            "pluginId": "imp-19-maximum-score-of-a-node-sequence",
            "status": "todo"
          },
          {
            "id": "imp-20-course-schedule",
            "kind": "problem",
            "pluginId": "imp-20-course-schedule",
            "status": "todo"
          },
          {
            "id": "imp-22-find-degree-of-vertex",
            "kind": "problem",
            "pluginId": "imp-22-find-degree-of-vertex",
            "status": "todo"
          },
          {
            "id": "imp-23-detect-cycle",
            "kind": "problem",
            "pluginId": "imp-23-detect-cycle",
            "status": "todo"
          },
          {
            "id": "imp-24-number-of-islands",
            "kind": "problem",
            "pluginId": "imp-24-number-of-islands",
            "status": "todo"
          },
          {
            "id": "imp-25-critical-connections-in-a-network",
            "kind": "problem",
            "pluginId": "imp-25-critical-connections-in-a-network",
            "status": "todo"
          }
        ]
      }
    ]
  },
  {
    "id": "lib-backtracking",
    "title": "Backtracking library",
    "summary": "19 reference solutions imported from your Go practice repo.",
    "icon": "GitBranch",
    "topics": [
      {
        "id": "lib-backtracking-all",
        "title": "Reference problems",
        "summary": "19 imported reference solutions",
        "items": [
          {
            "id": "imp-26-subsets",
            "kind": "problem",
            "pluginId": "imp-26-subsets",
            "status": "todo"
          },
          {
            "id": "imp-27-combinations",
            "kind": "problem",
            "pluginId": "imp-27-combinations",
            "status": "todo"
          },
          {
            "id": "imp-28-combination-of-subset-strings",
            "kind": "problem",
            "pluginId": "imp-28-combination-of-subset-strings",
            "status": "todo"
          },
          {
            "id": "imp-29-combination-sum-ii",
            "kind": "problem",
            "pluginId": "imp-29-combination-sum-ii",
            "status": "todo"
          },
          {
            "id": "imp-30-decode-numbers",
            "kind": "problem",
            "pluginId": "imp-30-decode-numbers",
            "status": "todo"
          },
          {
            "id": "imp-31-expression-add-operators",
            "kind": "problem",
            "pluginId": "imp-31-expression-add-operators",
            "status": "todo"
          },
          {
            "id": "imp-32-generate-binary-strings",
            "kind": "problem",
            "pluginId": "imp-32-generate-binary-strings",
            "status": "todo"
          },
          {
            "id": "imp-33-strobogrammatic-number-ii",
            "kind": "problem",
            "pluginId": "imp-33-strobogrammatic-number-ii",
            "status": "todo"
          },
          {
            "id": "imp-34-generate-parentheses",
            "kind": "problem",
            "pluginId": "imp-34-generate-parentheses",
            "status": "todo"
          },
          {
            "id": "imp-36-letter-combinations-of-a-phone-number",
            "kind": "problem",
            "pluginId": "imp-36-letter-combinations-of-a-phone-number",
            "status": "todo"
          },
          {
            "id": "imp-37-maximum-length-of-a-concatenated-string-with-uni",
            "kind": "problem",
            "pluginId": "imp-37-maximum-length-of-a-concatenated-string-with-uni",
            "status": "todo"
          },
          {
            "id": "imp-38-nested-list-weight-sum",
            "kind": "problem",
            "pluginId": "imp-38-nested-list-weight-sum",
            "status": "todo"
          },
          {
            "id": "imp-39-different-ways-to-add-parentheses",
            "kind": "problem",
            "pluginId": "imp-39-different-ways-to-add-parentheses",
            "status": "todo"
          },
          {
            "id": "imp-40-restore-ip-addresses",
            "kind": "problem",
            "pluginId": "imp-40-restore-ip-addresses",
            "status": "todo"
          },
          {
            "id": "imp-41-permutations",
            "kind": "problem",
            "pluginId": "imp-41-permutations",
            "status": "todo"
          },
          {
            "id": "imp-42-cartesian-product-of-multiple-arrays",
            "kind": "problem",
            "pluginId": "imp-42-cartesian-product-of-multiple-arrays",
            "status": "todo"
          },
          {
            "id": "imp-43-permutations",
            "kind": "problem",
            "pluginId": "imp-43-permutations",
            "status": "todo"
          },
          {
            "id": "imp-44-word-search",
            "kind": "problem",
            "pluginId": "imp-44-word-search",
            "status": "todo"
          },
          {
            "id": "imp-45-word-search-ii",
            "kind": "problem",
            "pluginId": "imp-45-word-search-ii",
            "status": "todo"
          }
        ]
      }
    ]
  },
  {
    "id": "lib-binary-search",
    "title": "Binary-search library",
    "summary": "11 reference solutions imported from your Go practice repo.",
    "icon": "Search",
    "topics": [
      {
        "id": "lib-binary-search-all",
        "title": "Reference problems",
        "summary": "11 imported reference solutions",
        "items": [
          {
            "id": "imp-46-search-in-rotated-sorted-array",
            "kind": "problem",
            "pluginId": "imp-46-search-in-rotated-sorted-array",
            "status": "todo"
          },
          {
            "id": "imp-47-maximum-length-of-ribbon-cut",
            "kind": "problem",
            "pluginId": "imp-47-maximum-length-of-ribbon-cut",
            "status": "todo"
          },
          {
            "id": "imp-48-find-smallest-letter-greater-than-target",
            "kind": "problem",
            "pluginId": "imp-48-find-smallest-letter-greater-than-target",
            "status": "todo"
          },
          {
            "id": "imp-49-kth-largest-element-in-an-array",
            "kind": "problem",
            "pluginId": "imp-49-kth-largest-element-in-an-array",
            "status": "todo"
          },
          {
            "id": "imp-50-find-right-interval",
            "kind": "problem",
            "pluginId": "imp-50-find-right-interval",
            "status": "todo"
          },
          {
            "id": "imp-51-missing-number-in-arithmetic-progression",
            "kind": "problem",
            "pluginId": "imp-51-missing-number-in-arithmetic-progression",
            "status": "todo"
          },
          {
            "id": "imp-52-missing-number",
            "kind": "problem",
            "pluginId": "imp-52-missing-number",
            "status": "todo"
          },
          {
            "id": "imp-53-find-first-and-last-position-of-element-in-sorte",
            "kind": "problem",
            "pluginId": "imp-53-find-first-and-last-position-of-element-in-sorte",
            "status": "todo"
          },
          {
            "id": "imp-54-find-peak-element",
            "kind": "problem",
            "pluginId": "imp-54-find-peak-element",
            "status": "todo"
          },
          {
            "id": "imp-55-leftmost-column-with-at-least-a-one",
            "kind": "problem",
            "pluginId": "imp-55-leftmost-column-with-at-least-a-one",
            "status": "todo"
          },
          {
            "id": "imp-56-squares-of-a-sorted-array",
            "kind": "problem",
            "pluginId": "imp-56-squares-of-a-sorted-array",
            "status": "todo"
          }
        ]
      }
    ]
  },
  {
    "id": "lib-dynamic-programming",
    "title": "DP library",
    "summary": "29 reference solutions imported from your Go practice repo.",
    "icon": "Table",
    "topics": [
      {
        "id": "lib-dynamic-programming-all",
        "title": "Reference problems",
        "summary": "29 imported reference solutions",
        "items": [
          {
            "id": "imp-57-check-if-an-original-string-exists-given-two-enc",
            "kind": "problem",
            "pluginId": "imp-57-check-if-an-original-string-exists-given-two-enc",
            "status": "todo"
          },
          {
            "id": "imp-58-climbing-stairs",
            "kind": "problem",
            "pluginId": "imp-58-climbing-stairs",
            "status": "todo"
          },
          {
            "id": "imp-59-coin-change",
            "kind": "problem",
            "pluginId": "imp-59-coin-change",
            "status": "todo"
          },
          {
            "id": "imp-60-coin-change-ii",
            "kind": "problem",
            "pluginId": "imp-60-coin-change-ii",
            "status": "todo"
          },
          {
            "id": "imp-61-edit-distance",
            "kind": "problem",
            "pluginId": "imp-61-edit-distance",
            "status": "todo"
          },
          {
            "id": "imp-62-filling-bookcase-shelves",
            "kind": "problem",
            "pluginId": "imp-62-filling-bookcase-shelves",
            "status": "todo"
          },
          {
            "id": "imp-63-0-1-knapsack",
            "kind": "problem",
            "pluginId": "imp-63-0-1-knapsack",
            "status": "todo"
          },
          {
            "id": "imp-64-perfect-squares",
            "kind": "problem",
            "pluginId": "imp-64-perfect-squares",
            "status": "todo"
          },
          {
            "id": "imp-65-longest-common-subsequence",
            "kind": "problem",
            "pluginId": "imp-65-longest-common-subsequence",
            "status": "todo"
          },
          {
            "id": "imp-66-longest-increasing-subsequence",
            "kind": "problem",
            "pluginId": "imp-66-longest-increasing-subsequence",
            "status": "todo"
          },
          {
            "id": "imp-67-longest-palindromic-subsequence",
            "kind": "problem",
            "pluginId": "imp-67-longest-palindromic-subsequence",
            "status": "todo"
          },
          {
            "id": "imp-68-longest-string-chain",
            "kind": "problem",
            "pluginId": "imp-68-longest-string-chain",
            "status": "todo"
          },
          {
            "id": "imp-69-longest-valid-parentheses",
            "kind": "problem",
            "pluginId": "imp-69-longest-valid-parentheses",
            "status": "todo"
          },
          {
            "id": "imp-70-maximal-rectangle",
            "kind": "problem",
            "pluginId": "imp-70-maximal-rectangle",
            "status": "todo"
          },
          {
            "id": "imp-71-maximal-square",
            "kind": "problem",
            "pluginId": "imp-71-maximal-square",
            "status": "todo"
          },
          {
            "id": "imp-72-maximum-and-sum-of-array",
            "kind": "problem",
            "pluginId": "imp-72-maximum-and-sum-of-array",
            "status": "todo"
          },
          {
            "id": "imp-73-maximum-number-of-points-with-cost",
            "kind": "problem",
            "pluginId": "imp-73-maximum-number-of-points-with-cost",
            "status": "todo"
          },
          {
            "id": "imp-74-minimum-path-sum",
            "kind": "problem",
            "pluginId": "imp-74-minimum-path-sum",
            "status": "todo"
          },
          {
            "id": "imp-75-minimum-deletions-to-make-string-balanced",
            "kind": "problem",
            "pluginId": "imp-75-minimum-deletions-to-make-string-balanced",
            "status": "todo"
          },
          {
            "id": "imp-76-distinct-subsequences",
            "kind": "problem",
            "pluginId": "imp-76-distinct-subsequences",
            "status": "todo"
          },
          {
            "id": "imp-77-unique-paths",
            "kind": "problem",
            "pluginId": "imp-77-unique-paths",
            "status": "todo"
          },
          {
            "id": "imp-78-decode-ways",
            "kind": "problem",
            "pluginId": "imp-78-decode-ways",
            "status": "todo"
          },
          {
            "id": "imp-79-partition-array-into-two-arrays-to-minimize-sum-",
            "kind": "problem",
            "pluginId": "imp-79-partition-array-into-two-arrays-to-minimize-sum-",
            "status": "todo"
          },
          {
            "id": "imp-80-race-car",
            "kind": "problem",
            "pluginId": "imp-80-race-car",
            "status": "todo"
          },
          {
            "id": "imp-81-range-sum-query-2d-immutable",
            "kind": "problem",
            "pluginId": "imp-81-range-sum-query-2d-immutable",
            "status": "todo"
          },
          {
            "id": "imp-82-regular-expression-matching",
            "kind": "problem",
            "pluginId": "imp-82-regular-expression-matching",
            "status": "todo"
          },
          {
            "id": "imp-83-sentence-screen-fitting",
            "kind": "problem",
            "pluginId": "imp-83-sentence-screen-fitting",
            "status": "todo"
          },
          {
            "id": "imp-84-student-attendance-record-ii",
            "kind": "problem",
            "pluginId": "imp-84-student-attendance-record-ii",
            "status": "todo"
          },
          {
            "id": "imp-85-valid-palindrome-iii",
            "kind": "problem",
            "pluginId": "imp-85-valid-palindrome-iii",
            "status": "todo"
          }
        ]
      }
    ]
  }
];

export const PREP_COURSES: CourseDef[] = [
  {
    "id": "prep-arrays",
    "title": "Arrays · prep library",
    "summary": "20 Arrays problems from your prep study collection.",
    "icon": "Table",
    "topics": [
      {
        "id": "prep-arrays-all",
        "title": "Arrays",
        "items": [
          {
            "id": "prep-arrays-find-duplicate-and-missing",
            "kind": "problem",
            "pluginId": "prep-arrays-find-duplicate-and-missing",
            "status": "todo"
          },
          {
            "id": "prep-arrays-find-duplicate-number",
            "kind": "problem",
            "pluginId": "prep-arrays-find-duplicate-number",
            "status": "todo"
          },
          {
            "id": "prep-arrays-find-intersection-of-two-sorted",
            "kind": "problem",
            "pluginId": "prep-arrays-find-intersection-of-two-sorted",
            "status": "todo"
          },
          {
            "id": "prep-arrays-find-majority-element",
            "kind": "problem",
            "pluginId": "prep-arrays-find-majority-element",
            "status": "todo"
          },
          {
            "id": "prep-arrays-jump-game",
            "kind": "problem",
            "pluginId": "prep-arrays-jump-game",
            "status": "todo"
          },
          {
            "id": "prep-arrays-max-product-of-subarray",
            "kind": "problem",
            "pluginId": "prep-arrays-max-product-of-subarray",
            "status": "todo"
          },
          {
            "id": "prep-arrays-max-profit-selling-stocks",
            "kind": "problem",
            "pluginId": "prep-arrays-max-profit-selling-stocks",
            "status": "todo"
          },
          {
            "id": "prep-arrays-max-rectangle-in-histogram",
            "kind": "problem",
            "pluginId": "prep-arrays-max-rectangle-in-histogram",
            "status": "todo"
          },
          {
            "id": "prep-arrays-max-sum-of-subarray-size-k",
            "kind": "problem",
            "pluginId": "prep-arrays-max-sum-of-subarray-size-k",
            "status": "todo"
          },
          {
            "id": "prep-arrays-merge-two-sorted-arrays",
            "kind": "problem",
            "pluginId": "prep-arrays-merge-two-sorted-arrays",
            "status": "todo"
          },
          {
            "id": "prep-arrays-move-all-zeros-to-end",
            "kind": "problem",
            "pluginId": "prep-arrays-move-all-zeros-to-end",
            "status": "todo"
          },
          {
            "id": "prep-arrays-next-permutation",
            "kind": "problem",
            "pluginId": "prep-arrays-next-permutation",
            "status": "todo"
          },
          {
            "id": "prep-arrays-remove-duplicates-in-place",
            "kind": "problem",
            "pluginId": "prep-arrays-remove-duplicates-in-place",
            "status": "todo"
          },
          {
            "id": "prep-arrays-reverse-array",
            "kind": "problem",
            "pluginId": "prep-arrays-reverse-array",
            "status": "todo"
          },
          {
            "id": "prep-arrays-rotate-array",
            "kind": "problem",
            "pluginId": "prep-arrays-rotate-array",
            "status": "todo"
          },
          {
            "id": "prep-arrays-self-exclude-product",
            "kind": "problem",
            "pluginId": "prep-arrays-self-exclude-product",
            "status": "todo"
          },
          {
            "id": "prep-arrays-task-scheduler",
            "kind": "problem",
            "pluginId": "prep-arrays-task-scheduler",
            "status": "todo"
          },
          {
            "id": "prep-arrays-trap-most-water",
            "kind": "problem",
            "pluginId": "prep-arrays-trap-most-water",
            "status": "todo"
          },
          {
            "id": "prep-arrays-trap-rain-water",
            "kind": "problem",
            "pluginId": "prep-arrays-trap-rain-water",
            "status": "todo"
          },
          {
            "id": "prep-arrays-two-sum",
            "kind": "problem",
            "pluginId": "prep-arrays-two-sum",
            "status": "todo"
          }
        ]
      }
    ]
  },
  {
    "id": "prep-strings",
    "title": "Strings · prep library",
    "summary": "39 Strings problems from your prep study collection.",
    "icon": "Type",
    "topics": [
      {
        "id": "prep-strings-all",
        "title": "Strings",
        "items": [
          {
            "id": "prep-strings-count-words-obtained-after-adding-a-letter",
            "kind": "problem",
            "pluginId": "prep-strings-count-words-obtained-after-adding-a-letter",
            "status": "todo"
          },
          {
            "id": "prep-strings-custom-sort-string",
            "kind": "problem",
            "pluginId": "prep-strings-custom-sort-string",
            "status": "todo"
          },
          {
            "id": "prep-strings-find-all-subset-words",
            "kind": "problem",
            "pluginId": "prep-strings-find-all-subset-words",
            "status": "todo"
          },
          {
            "id": "prep-strings-find-anagram-substring-indices",
            "kind": "problem",
            "pluginId": "prep-strings-find-anagram-substring-indices",
            "status": "todo"
          },
          {
            "id": "prep-strings-find-and-replace-in-string",
            "kind": "problem",
            "pluginId": "prep-strings-find-and-replace-in-string",
            "status": "todo"
          },
          {
            "id": "prep-strings-find-first-unique-character",
            "kind": "problem",
            "pluginId": "prep-strings-find-first-unique-character",
            "status": "todo"
          },
          {
            "id": "prep-strings-find-repeated-substrings-size-k",
            "kind": "problem",
            "pluginId": "prep-strings-find-repeated-substrings-size-k",
            "status": "todo"
          },
          {
            "id": "prep-strings-group-anagrams",
            "kind": "problem",
            "pluginId": "prep-strings-group-anagrams",
            "status": "todo"
          },
          {
            "id": "prep-strings-group-shifted-strings",
            "kind": "problem",
            "pluginId": "prep-strings-group-shifted-strings",
            "status": "todo"
          },
          {
            "id": "prep-strings-is-anagram",
            "kind": "problem",
            "pluginId": "prep-strings-is-anagram",
            "status": "todo"
          },
          {
            "id": "prep-strings-is-isomorphic",
            "kind": "problem",
            "pluginId": "prep-strings-is-isomorphic",
            "status": "todo"
          },
          {
            "id": "prep-strings-is-palindrome",
            "kind": "problem",
            "pluginId": "prep-strings-is-palindrome",
            "status": "todo"
          },
          {
            "id": "prep-strings-longest-common-prefix",
            "kind": "problem",
            "pluginId": "prep-strings-longest-common-prefix",
            "status": "todo"
          },
          {
            "id": "prep-strings-longest-happy-string",
            "kind": "problem",
            "pluginId": "prep-strings-longest-happy-string",
            "status": "todo"
          },
          {
            "id": "prep-strings-longest-palindromic-substring",
            "kind": "problem",
            "pluginId": "prep-strings-longest-palindromic-substring",
            "status": "todo"
          },
          {
            "id": "prep-strings-longest-substring-with-unique",
            "kind": "problem",
            "pluginId": "prep-strings-longest-substring-with-unique",
            "status": "todo"
          },
          {
            "id": "prep-strings-min-insertions-to-form-palin",
            "kind": "problem",
            "pluginId": "prep-strings-min-insertions-to-form-palin",
            "status": "todo"
          },
          {
            "id": "prep-strings-min-window-substring",
            "kind": "problem",
            "pluginId": "prep-strings-min-window-substring",
            "status": "todo"
          },
          {
            "id": "prep-strings-minimum-add-to-make-parentheses-valid",
            "kind": "problem",
            "pluginId": "prep-strings-minimum-add-to-make-parentheses-valid",
            "status": "todo"
          },
          {
            "id": "prep-strings-minimum-remove-to-make-valid-parentheses",
            "kind": "problem",
            "pluginId": "prep-strings-minimum-remove-to-make-valid-parentheses",
            "status": "todo"
          },
          {
            "id": "prep-strings-minimum-time-difference",
            "kind": "problem",
            "pluginId": "prep-strings-minimum-time-difference",
            "status": "todo"
          },
          {
            "id": "prep-strings-minimum-time-to-make-rope-colorful",
            "kind": "problem",
            "pluginId": "prep-strings-minimum-time-to-make-rope-colorful",
            "status": "todo"
          },
          {
            "id": "prep-strings-number-of-matching-subsequences",
            "kind": "problem",
            "pluginId": "prep-strings-number-of-matching-subsequences",
            "status": "todo"
          },
          {
            "id": "prep-strings-number-of-steps-to-reduce-a-number-in-binary-representation-",
            "kind": "problem",
            "pluginId": "prep-strings-number-of-steps-to-reduce-a-number-in-binary-representation-",
            "status": "todo"
          },
          {
            "id": "prep-strings-ransom-note",
            "kind": "problem",
            "pluginId": "prep-strings-ransom-note",
            "status": "todo"
          },
          {
            "id": "prep-strings-reverse-words",
            "kind": "problem",
            "pluginId": "prep-strings-reverse-words",
            "status": "todo"
          },
          {
            "id": "prep-strings-reverse-words-in-a-string",
            "kind": "problem",
            "pluginId": "prep-strings-reverse-words-in-a-string",
            "status": "todo"
          },
          {
            "id": "prep-strings-rotate-string",
            "kind": "problem",
            "pluginId": "prep-strings-rotate-string",
            "status": "todo"
          },
          {
            "id": "prep-strings-run-length-encoding",
            "kind": "problem",
            "pluginId": "prep-strings-run-length-encoding",
            "status": "todo"
          },
          {
            "id": "prep-strings-shortest-subarray-contains-all",
            "kind": "problem",
            "pluginId": "prep-strings-shortest-subarray-contains-all",
            "status": "todo"
          },
          {
            "id": "prep-strings-shortest-way-to-form-string",
            "kind": "problem",
            "pluginId": "prep-strings-shortest-way-to-form-string",
            "status": "todo"
          },
          {
            "id": "prep-strings-strings-differ-by-one-character",
            "kind": "problem",
            "pluginId": "prep-strings-strings-differ-by-one-character",
            "status": "todo"
          },
          {
            "id": "prep-strings-sum-of-prefix-scores-of-strings",
            "kind": "problem",
            "pluginId": "prep-strings-sum-of-prefix-scores-of-strings",
            "status": "todo"
          },
          {
            "id": "prep-strings-swap-adjacent-in-lr-string",
            "kind": "problem",
            "pluginId": "prep-strings-swap-adjacent-in-lr-string",
            "status": "todo"
          },
          {
            "id": "prep-strings-swap-even-odd",
            "kind": "problem",
            "pluginId": "prep-strings-swap-even-odd",
            "status": "todo"
          },
          {
            "id": "prep-strings-text-justification",
            "kind": "problem",
            "pluginId": "prep-strings-text-justification",
            "status": "todo"
          },
          {
            "id": "prep-strings-valid-number",
            "kind": "problem",
            "pluginId": "prep-strings-valid-number",
            "status": "todo"
          },
          {
            "id": "prep-strings-word-break",
            "kind": "problem",
            "pluginId": "prep-strings-word-break",
            "status": "todo"
          },
          {
            "id": "prep-strings-word-wrap",
            "kind": "problem",
            "pluginId": "prep-strings-word-wrap",
            "status": "todo"
          }
        ]
      }
    ]
  },
  {
    "id": "prep-hash-maps",
    "title": "Hash maps · prep library",
    "summary": "11 Hash maps problems from your prep study collection.",
    "icon": "Hash",
    "topics": [
      {
        "id": "prep-hash-maps-all",
        "title": "Hash maps",
        "items": [
          {
            "id": "prep-hash-maps-find-k-closest-to-center",
            "kind": "problem",
            "pluginId": "prep-hash-maps-find-k-closest-to-center",
            "status": "todo"
          },
          {
            "id": "prep-hash-maps-find-kth-largest",
            "kind": "problem",
            "pluginId": "prep-hash-maps-find-kth-largest",
            "status": "todo"
          },
          {
            "id": "prep-hash-maps-find-most-popular-cost-books",
            "kind": "problem",
            "pluginId": "prep-hash-maps-find-most-popular-cost-books",
            "status": "todo"
          },
          {
            "id": "prep-hash-maps-find-top-k-frequent-elements",
            "kind": "problem",
            "pluginId": "prep-hash-maps-find-top-k-frequent-elements",
            "status": "todo"
          },
          {
            "id": "prep-hash-maps-find-top-k-tweet-words-in-last",
            "kind": "problem",
            "pluginId": "prep-hash-maps-find-top-k-tweet-words-in-last",
            "status": "todo"
          },
          {
            "id": "prep-hash-maps-find-x-to-make-array-sum-to-k",
            "kind": "problem",
            "pluginId": "prep-hash-maps-find-x-to-make-array-sum-to-k",
            "status": "todo"
          },
          {
            "id": "prep-hash-maps-find-year-with-most-population",
            "kind": "problem",
            "pluginId": "prep-hash-maps-find-year-with-most-population",
            "status": "todo"
          },
          {
            "id": "prep-hash-maps-get-all-element-counts",
            "kind": "problem",
            "pluginId": "prep-hash-maps-get-all-element-counts",
            "status": "todo"
          },
          {
            "id": "prep-hash-maps-object-as-key",
            "kind": "problem",
            "pluginId": "prep-hash-maps-object-as-key",
            "status": "todo"
          },
          {
            "id": "prep-hash-maps-remove-duplicate-contacts",
            "kind": "problem",
            "pluginId": "prep-hash-maps-remove-duplicate-contacts",
            "status": "todo"
          },
          {
            "id": "prep-hash-maps-sort-pairs",
            "kind": "problem",
            "pluginId": "prep-hash-maps-sort-pairs",
            "status": "todo"
          }
        ]
      }
    ]
  },
  {
    "id": "prep-linked-lists",
    "title": "Linked lists · prep library",
    "summary": "17 Linked lists problems from your prep study collection.",
    "icon": "Link",
    "topics": [
      {
        "id": "prep-linked-lists-all",
        "title": "Linked lists",
        "items": [
          {
            "id": "prep-linked-lists-add-two-numbers",
            "kind": "problem",
            "pluginId": "prep-linked-lists-add-two-numbers",
            "status": "todo"
          },
          {
            "id": "prep-linked-lists-copy-list-with-random-pointer",
            "kind": "problem",
            "pluginId": "prep-linked-lists-copy-list-with-random-pointer",
            "status": "todo"
          },
          {
            "id": "prep-linked-lists-deep-copy-random-pointers",
            "kind": "problem",
            "pluginId": "prep-linked-lists-deep-copy-random-pointers",
            "status": "todo"
          },
          {
            "id": "prep-linked-lists-delete-every-kth-node-in-dll",
            "kind": "problem",
            "pluginId": "prep-linked-lists-delete-every-kth-node-in-dll",
            "status": "todo"
          },
          {
            "id": "prep-linked-lists-delete-node",
            "kind": "problem",
            "pluginId": "prep-linked-lists-delete-node",
            "status": "todo"
          },
          {
            "id": "prep-linked-lists-detect-loop",
            "kind": "problem",
            "pluginId": "prep-linked-lists-detect-loop",
            "status": "todo"
          },
          {
            "id": "prep-linked-lists-find-intersection-of-two-lists",
            "kind": "problem",
            "pluginId": "prep-linked-lists-find-intersection-of-two-lists",
            "status": "todo"
          },
          {
            "id": "prep-linked-lists-find-node",
            "kind": "problem",
            "pluginId": "prep-linked-lists-find-node",
            "status": "todo"
          },
          {
            "id": "prep-linked-lists-flatten-doubly-linked-list",
            "kind": "problem",
            "pluginId": "prep-linked-lists-flatten-doubly-linked-list",
            "status": "todo"
          },
          {
            "id": "prep-linked-lists-insert-into-a-sorted-circular-linked-list",
            "kind": "problem",
            "pluginId": "prep-linked-lists-insert-into-a-sorted-circular-linked-list",
            "status": "todo"
          },
          {
            "id": "prep-linked-lists-last-men-standing",
            "kind": "problem",
            "pluginId": "prep-linked-lists-last-men-standing",
            "status": "todo"
          },
          {
            "id": "prep-linked-lists-merge-k-sorted-lists",
            "kind": "problem",
            "pluginId": "prep-linked-lists-merge-k-sorted-lists",
            "status": "todo"
          },
          {
            "id": "prep-linked-lists-merge-two-sorted-lists",
            "kind": "problem",
            "pluginId": "prep-linked-lists-merge-two-sorted-lists",
            "status": "todo"
          },
          {
            "id": "prep-linked-lists-print-from-end",
            "kind": "problem",
            "pluginId": "prep-linked-lists-print-from-end",
            "status": "todo"
          },
          {
            "id": "prep-linked-lists-reverse-linked-list",
            "kind": "problem",
            "pluginId": "prep-linked-lists-reverse-linked-list",
            "status": "todo"
          },
          {
            "id": "prep-linked-lists-reverse-nodes-in-k-group",
            "kind": "problem",
            "pluginId": "prep-linked-lists-reverse-nodes-in-k-group",
            "status": "todo"
          },
          {
            "id": "prep-linked-lists-sort-linked-list",
            "kind": "problem",
            "pluginId": "prep-linked-lists-sort-linked-list",
            "status": "todo"
          }
        ]
      }
    ]
  },
  {
    "id": "prep-stacks-queues",
    "title": "Stacks & queues · prep library",
    "summary": "14 Stacks & queues problems from your prep study collection.",
    "icon": "Layers",
    "topics": [
      {
        "id": "prep-stacks-queues-all",
        "title": "Stacks & queues",
        "items": [
          {
            "id": "prep-stacks-queues-basic-calculator",
            "kind": "problem",
            "pluginId": "prep-stacks-queues-basic-calculator",
            "status": "todo"
          },
          {
            "id": "prep-stacks-queues-buildings-with-an-ocean-view",
            "kind": "problem",
            "pluginId": "prep-stacks-queues-buildings-with-an-ocean-view",
            "status": "todo"
          },
          {
            "id": "prep-stacks-queues-calculate-infix",
            "kind": "problem",
            "pluginId": "prep-stacks-queues-calculate-infix",
            "status": "todo"
          },
          {
            "id": "prep-stacks-queues-calculate-postfix",
            "kind": "problem",
            "pluginId": "prep-stacks-queues-calculate-postfix",
            "status": "todo"
          },
          {
            "id": "prep-stacks-queues-decode-string",
            "kind": "problem",
            "pluginId": "prep-stacks-queues-decode-string",
            "status": "todo"
          },
          {
            "id": "prep-stacks-queues-find-max-in-sliding-window",
            "kind": "problem",
            "pluginId": "prep-stacks-queues-find-max-in-sliding-window",
            "status": "todo"
          },
          {
            "id": "prep-stacks-queues-find-moving-average-in-sliding",
            "kind": "problem",
            "pluginId": "prep-stacks-queues-find-moving-average-in-sliding",
            "status": "todo"
          },
          {
            "id": "prep-stacks-queues-implement-queue-with-max",
            "kind": "problem",
            "pluginId": "prep-stacks-queues-implement-queue-with-max",
            "status": "todo"
          },
          {
            "id": "prep-stacks-queues-implement-stack-with-min",
            "kind": "problem",
            "pluginId": "prep-stacks-queues-implement-stack-with-min",
            "status": "todo"
          },
          {
            "id": "prep-stacks-queues-infix-to-postfix",
            "kind": "problem",
            "pluginId": "prep-stacks-queues-infix-to-postfix",
            "status": "todo"
          },
          {
            "id": "prep-stacks-queues-prefix-to-postfix",
            "kind": "problem",
            "pluginId": "prep-stacks-queues-prefix-to-postfix",
            "status": "todo"
          },
          {
            "id": "prep-stacks-queues-simplify-path",
            "kind": "problem",
            "pluginId": "prep-stacks-queues-simplify-path",
            "status": "todo"
          },
          {
            "id": "prep-stacks-queues-trapping-rain-water",
            "kind": "problem",
            "pluginId": "prep-stacks-queues-trapping-rain-water",
            "status": "todo"
          },
          {
            "id": "prep-stacks-queues-validate-parentheses",
            "kind": "problem",
            "pluginId": "prep-stacks-queues-validate-parentheses",
            "status": "todo"
          }
        ]
      }
    ]
  },
  {
    "id": "prep-trees",
    "title": "Trees · prep library",
    "summary": "46 Trees problems from your prep study collection.",
    "icon": "ListTree",
    "topics": [
      {
        "id": "prep-trees-all",
        "title": "Trees",
        "items": [
          {
            "id": "prep-trees-binary-search-tree-iterator",
            "kind": "problem",
            "pluginId": "prep-trees-binary-search-tree-iterator",
            "status": "todo"
          },
          {
            "id": "prep-trees-binary-tree-maximum-path-sum",
            "kind": "problem",
            "pluginId": "prep-trees-binary-tree-maximum-path-sum",
            "status": "todo"
          },
          {
            "id": "prep-trees-binary-tree-right-side-view",
            "kind": "problem",
            "pluginId": "prep-trees-binary-tree-right-side-view",
            "status": "todo"
          },
          {
            "id": "prep-trees-binary-tree-traversal-iteratively",
            "kind": "problem",
            "pluginId": "prep-trees-binary-tree-traversal-iteratively",
            "status": "todo"
          },
          {
            "id": "prep-trees-binary-tree-vertical-order-traversal",
            "kind": "problem",
            "pluginId": "prep-trees-binary-tree-vertical-order-traversal",
            "status": "todo"
          },
          {
            "id": "prep-trees-binary-tree-zigzag-level-order-traversal",
            "kind": "problem",
            "pluginId": "prep-trees-binary-tree-zigzag-level-order-traversal",
            "status": "todo"
          },
          {
            "id": "prep-trees-convert-binary-search-tree-to-sorted-doubly-linked-list",
            "kind": "problem",
            "pluginId": "prep-trees-convert-binary-search-tree-to-sorted-doubly-linked-list",
            "status": "todo"
          },
          {
            "id": "prep-trees-convert-binary-tree-to-doubly",
            "kind": "problem",
            "pluginId": "prep-trees-convert-binary-tree-to-doubly",
            "status": "todo"
          },
          {
            "id": "prep-trees-convert-sorted-array-to-bst",
            "kind": "problem",
            "pluginId": "prep-trees-convert-sorted-array-to-bst",
            "status": "todo"
          },
          {
            "id": "prep-trees-convert-sorted-linked-list-to-bst",
            "kind": "problem",
            "pluginId": "prep-trees-convert-sorted-linked-list-to-bst",
            "status": "todo"
          },
          {
            "id": "prep-trees-count-good-nodes-in-binary-tree",
            "kind": "problem",
            "pluginId": "prep-trees-count-good-nodes-in-binary-tree",
            "status": "todo"
          },
          {
            "id": "prep-trees-find-distance-of-two-nodes",
            "kind": "problem",
            "pluginId": "prep-trees-find-distance-of-two-nodes",
            "status": "todo"
          },
          {
            "id": "prep-trees-nary-tree-distance-of-two-nodes",
            "kind": "problem",
            "pluginId": "prep-trees-nary-tree-distance-of-two-nodes",
            "status": "todo"
          },
          {
            "id": "prep-trees-find-kth-largest-in-bst",
            "kind": "problem",
            "pluginId": "prep-trees-find-kth-largest-in-bst",
            "status": "todo"
          },
          {
            "id": "prep-trees-find-leaves-of-binary-tree",
            "kind": "problem",
            "pluginId": "prep-trees-find-leaves-of-binary-tree",
            "status": "todo"
          },
          {
            "id": "prep-trees-nary-tree-lowest-common-ancestor",
            "kind": "problem",
            "pluginId": "prep-trees-nary-tree-lowest-common-ancestor",
            "status": "todo"
          },
          {
            "id": "prep-trees-flip-tree",
            "kind": "problem",
            "pluginId": "prep-trees-flip-tree",
            "status": "todo"
          },
          {
            "id": "prep-trees-get-diameter",
            "kind": "problem",
            "pluginId": "prep-trees-get-diameter",
            "status": "todo"
          },
          {
            "id": "prep-trees-nary-tree-diameter",
            "kind": "problem",
            "pluginId": "prep-trees-nary-tree-diameter",
            "status": "todo"
          },
          {
            "id": "prep-trees-get-height",
            "kind": "problem",
            "pluginId": "prep-trees-get-height",
            "status": "todo"
          },
          {
            "id": "prep-trees-nary-tree-height",
            "kind": "problem",
            "pluginId": "prep-trees-nary-tree-height",
            "status": "todo"
          },
          {
            "id": "prep-trees-inorder-successor-in-bst",
            "kind": "problem",
            "pluginId": "prep-trees-inorder-successor-in-bst",
            "status": "todo"
          },
          {
            "id": "prep-trees-is-balanced",
            "kind": "problem",
            "pluginId": "prep-trees-is-balanced",
            "status": "todo"
          },
          {
            "id": "prep-trees-is-bst",
            "kind": "problem",
            "pluginId": "prep-trees-is-bst",
            "status": "todo"
          },
          {
            "id": "prep-trees-is-complete",
            "kind": "problem",
            "pluginId": "prep-trees-is-complete",
            "status": "todo"
          },
          {
            "id": "prep-trees-is-subtree",
            "kind": "problem",
            "pluginId": "prep-trees-is-subtree",
            "status": "todo"
          },
          {
            "id": "prep-trees-is-symmetric",
            "kind": "problem",
            "pluginId": "prep-trees-is-symmetric",
            "status": "todo"
          },
          {
            "id": "prep-trees-level-order",
            "kind": "problem",
            "pluginId": "prep-trees-level-order",
            "status": "todo"
          },
          {
            "id": "prep-trees-nary-tree-level-order",
            "kind": "problem",
            "pluginId": "prep-trees-nary-tree-level-order",
            "status": "todo"
          },
          {
            "id": "prep-trees-longest-path-with-different-adjacent-characters",
            "kind": "problem",
            "pluginId": "prep-trees-longest-path-with-different-adjacent-characters",
            "status": "todo"
          },
          {
            "id": "prep-trees-lowest-common-ancestor-of-a-binary-tree",
            "kind": "problem",
            "pluginId": "prep-trees-lowest-common-ancestor-of-a-binary-tree",
            "status": "todo"
          },
          {
            "id": "prep-trees-lowest-common-ancestor-of-a-binary-tree-iii",
            "kind": "problem",
            "pluginId": "prep-trees-lowest-common-ancestor-of-a-binary-tree-iii",
            "status": "todo"
          },
          {
            "id": "prep-trees-nary-tree-monarchy-succession",
            "kind": "problem",
            "pluginId": "prep-trees-nary-tree-monarchy-succession",
            "status": "todo"
          },
          {
            "id": "prep-trees-nary-tree-traversal-iteratively",
            "kind": "problem",
            "pluginId": "prep-trees-nary-tree-traversal-iteratively",
            "status": "todo"
          },
          {
            "id": "prep-trees-path-sum-to-k",
            "kind": "problem",
            "pluginId": "prep-trees-path-sum-to-k",
            "status": "todo"
          },
          {
            "id": "prep-trees-populate-next-pointers-to-right",
            "kind": "problem",
            "pluginId": "prep-trees-populate-next-pointers-to-right",
            "status": "todo"
          },
          {
            "id": "prep-trees-print-all-root-to-leaf-paths",
            "kind": "problem",
            "pluginId": "prep-trees-print-all-root-to-leaf-paths",
            "status": "todo"
          },
          {
            "id": "prep-trees-print-leaves",
            "kind": "problem",
            "pluginId": "prep-trees-print-leaves",
            "status": "todo"
          },
          {
            "id": "prep-trees-print-side-view",
            "kind": "problem",
            "pluginId": "prep-trees-print-side-view",
            "status": "todo"
          },
          {
            "id": "prep-trees-print-vertical",
            "kind": "problem",
            "pluginId": "prep-trees-print-vertical",
            "status": "todo"
          },
          {
            "id": "prep-trees-recover-binary-search-tree",
            "kind": "problem",
            "pluginId": "prep-trees-recover-binary-search-tree",
            "status": "todo"
          },
          {
            "id": "prep-trees-serialize-and-deserialize",
            "kind": "problem",
            "pluginId": "prep-trees-serialize-and-deserialize",
            "status": "todo"
          },
          {
            "id": "prep-trees-serialize-and-deserialize-binary-tree",
            "kind": "problem",
            "pluginId": "prep-trees-serialize-and-deserialize-binary-tree",
            "status": "todo"
          },
          {
            "id": "prep-trees-step-by-step-directions-from-a-binary-tree-node-to-another",
            "kind": "problem",
            "pluginId": "prep-trees-step-by-step-directions-from-a-binary-tree-node-to-another",
            "status": "todo"
          },
          {
            "id": "prep-trees-sum-of-nodes",
            "kind": "problem",
            "pluginId": "prep-trees-sum-of-nodes",
            "status": "todo"
          },
          {
            "id": "prep-trees-vertical-order-traversal-of-a-binary-tree",
            "kind": "problem",
            "pluginId": "prep-trees-vertical-order-traversal-of-a-binary-tree",
            "status": "todo"
          }
        ]
      }
    ]
  },
  {
    "id": "prep-tries",
    "title": "Tries · prep library",
    "summary": "3 Tries problems from your prep study collection.",
    "icon": "Network",
    "topics": [
      {
        "id": "prep-tries-all",
        "title": "Tries",
        "items": [
          {
            "id": "prep-tries-find-distinct-palindromic-sub",
            "kind": "problem",
            "pluginId": "prep-tries-find-distinct-palindromic-sub",
            "status": "todo"
          },
          {
            "id": "prep-tries-implement-trie-methods",
            "kind": "problem",
            "pluginId": "prep-tries-implement-trie-methods",
            "status": "todo"
          },
          {
            "id": "prep-tries-longest-repeated-substring",
            "kind": "problem",
            "pluginId": "prep-tries-longest-repeated-substring",
            "status": "todo"
          }
        ]
      }
    ]
  },
  {
    "id": "prep-matrices",
    "title": "Matrices · prep library",
    "summary": "18 Matrices problems from your prep study collection.",
    "icon": "Grid",
    "topics": [
      {
        "id": "prep-matrices-all",
        "title": "Matrices",
        "items": [
          {
            "id": "prep-matrices-battleships-in-a-board",
            "kind": "problem",
            "pluginId": "prep-matrices-battleships-in-a-board",
            "status": "todo"
          },
          {
            "id": "prep-matrices-check-if-word-can-be-placed-in-crossword",
            "kind": "problem",
            "pluginId": "prep-matrices-check-if-word-can-be-placed-in-crossword",
            "status": "todo"
          },
          {
            "id": "prep-matrices-diagonal-traverse",
            "kind": "problem",
            "pluginId": "prep-matrices-diagonal-traverse",
            "status": "todo"
          },
          {
            "id": "prep-matrices-fill-rows-and-columns-with-1s",
            "kind": "problem",
            "pluginId": "prep-matrices-fill-rows-and-columns-with-1s",
            "status": "todo"
          },
          {
            "id": "prep-matrices-find-path-between-cells",
            "kind": "problem",
            "pluginId": "prep-matrices-find-path-between-cells",
            "status": "todo"
          },
          {
            "id": "prep-matrices-longest-increasing-path",
            "kind": "problem",
            "pluginId": "prep-matrices-longest-increasing-path",
            "status": "todo"
          },
          {
            "id": "prep-matrices-longest-increasing-path-in-a-matrix",
            "kind": "problem",
            "pluginId": "prep-matrices-longest-increasing-path-in-a-matrix",
            "status": "todo"
          },
          {
            "id": "prep-matrices-longest-line-of-consecutive-one-in-matrix",
            "kind": "problem",
            "pluginId": "prep-matrices-longest-line-of-consecutive-one-in-matrix",
            "status": "todo"
          },
          {
            "id": "prep-matrices-max-region",
            "kind": "problem",
            "pluginId": "prep-matrices-max-region",
            "status": "todo"
          },
          {
            "id": "prep-matrices-min-distance-of-meeting-point",
            "kind": "problem",
            "pluginId": "prep-matrices-min-distance-of-meeting-point",
            "status": "todo"
          },
          {
            "id": "prep-matrices-nearest-bikes",
            "kind": "problem",
            "pluginId": "prep-matrices-nearest-bikes",
            "status": "todo"
          },
          {
            "id": "prep-matrices-print-matrix-in-spiral-order",
            "kind": "problem",
            "pluginId": "prep-matrices-print-matrix-in-spiral-order",
            "status": "todo"
          },
          {
            "id": "prep-matrices-remove-all-ones-with-row-and-column-flips",
            "kind": "problem",
            "pluginId": "prep-matrices-remove-all-ones-with-row-and-column-flips",
            "status": "todo"
          },
          {
            "id": "prep-matrices-rotate-matrix-by-90-degrees",
            "kind": "problem",
            "pluginId": "prep-matrices-rotate-matrix-by-90-degrees",
            "status": "todo"
          },
          {
            "id": "prep-matrices-search-a-2d-matrix-ii",
            "kind": "problem",
            "pluginId": "prep-matrices-search-a-2d-matrix-ii",
            "status": "todo"
          },
          {
            "id": "prep-matrices-search-in-sorted-matrix",
            "kind": "problem",
            "pluginId": "prep-matrices-search-in-sorted-matrix",
            "status": "todo"
          },
          {
            "id": "prep-matrices-spiral-matrix",
            "kind": "problem",
            "pluginId": "prep-matrices-spiral-matrix",
            "status": "todo"
          },
          {
            "id": "prep-matrices-word-search-on-board",
            "kind": "problem",
            "pluginId": "prep-matrices-word-search-on-board",
            "status": "todo"
          }
        ]
      }
    ]
  },
  {
    "id": "prep-intervals",
    "title": "Intervals · prep library",
    "summary": "10 Intervals problems from your prep study collection.",
    "icon": "CalendarRange",
    "topics": [
      {
        "id": "prep-intervals-all",
        "title": "Intervals",
        "items": [
          {
            "id": "prep-intervals-count-intervals-range",
            "kind": "problem",
            "pluginId": "prep-intervals-count-intervals-range",
            "status": "todo"
          },
          {
            "id": "prep-intervals-distance-of-nearest-stores",
            "kind": "problem",
            "pluginId": "prep-intervals-distance-of-nearest-stores",
            "status": "todo"
          },
          {
            "id": "prep-intervals-draw-skyline",
            "kind": "problem",
            "pluginId": "prep-intervals-draw-skyline",
            "status": "todo"
          },
          {
            "id": "prep-intervals-insert-interval",
            "kind": "problem",
            "pluginId": "prep-intervals-insert-interval",
            "status": "todo"
          },
          {
            "id": "prep-intervals-is-overlapped",
            "kind": "problem",
            "pluginId": "prep-intervals-is-overlapped",
            "status": "todo"
          },
          {
            "id": "prep-intervals-is-square",
            "kind": "problem",
            "pluginId": "prep-intervals-is-square",
            "status": "todo"
          },
          {
            "id": "prep-intervals-meeting-rooms-ii",
            "kind": "problem",
            "pluginId": "prep-intervals-meeting-rooms-ii",
            "status": "todo"
          },
          {
            "id": "prep-intervals-merge-intervals",
            "kind": "problem",
            "pluginId": "prep-intervals-merge-intervals",
            "status": "todo"
          },
          {
            "id": "prep-intervals-schedule-meetings",
            "kind": "problem",
            "pluginId": "prep-intervals-schedule-meetings",
            "status": "todo"
          },
          {
            "id": "prep-intervals-weighted-job-scheduler",
            "kind": "problem",
            "pluginId": "prep-intervals-weighted-job-scheduler",
            "status": "todo"
          }
        ]
      }
    ]
  },
  {
    "id": "prep-prefix-sum",
    "title": "Prefix sum · prep library",
    "summary": "3 Prefix sum problems from your prep study collection.",
    "icon": "Sigma",
    "topics": [
      {
        "id": "prep-prefix-sum-all",
        "title": "Prefix sum",
        "items": [
          {
            "id": "prep-prefix-sum-array-manipulation",
            "kind": "problem",
            "pluginId": "prep-prefix-sum-array-manipulation",
            "status": "todo"
          },
          {
            "id": "prep-prefix-sum-continuous-subarray-sum",
            "kind": "problem",
            "pluginId": "prep-prefix-sum-continuous-subarray-sum",
            "status": "todo"
          },
          {
            "id": "prep-prefix-sum-subarray-sum-equals-k",
            "kind": "problem",
            "pluginId": "prep-prefix-sum-subarray-sum-equals-k",
            "status": "todo"
          }
        ]
      }
    ]
  },
  {
    "id": "prep-sliding-window",
    "title": "Sliding window · prep library",
    "summary": "1 Sliding window problems from your prep study collection.",
    "icon": "RectangleHorizontal",
    "topics": [
      {
        "id": "prep-sliding-window-all",
        "title": "Sliding window",
        "items": [
          {
            "id": "prep-sliding-window-minimum-window-substring",
            "kind": "problem",
            "pluginId": "prep-sliding-window-minimum-window-substring",
            "status": "todo"
          }
        ]
      }
    ]
  },
  {
    "id": "prep-sorting",
    "title": "Sorting · prep library",
    "summary": "7 Sorting problems from your prep study collection.",
    "icon": "ArrowDownUp",
    "topics": [
      {
        "id": "prep-sorting-all",
        "title": "Sorting",
        "items": [
          {
            "id": "prep-sorting-3sum",
            "kind": "problem",
            "pluginId": "prep-sorting-3sum",
            "status": "todo"
          },
          {
            "id": "prep-sorting-equal-sum-arrays-with-minimum-number-of-operations",
            "kind": "problem",
            "pluginId": "prep-sorting-equal-sum-arrays-with-minimum-number-of-operations",
            "status": "todo"
          },
          {
            "id": "prep-sorting-max-chunks-to-make-sorted-ii",
            "kind": "problem",
            "pluginId": "prep-sorting-max-chunks-to-make-sorted-ii",
            "status": "todo"
          },
          {
            "id": "prep-sorting-minimum-deletions-to-make-character-frequencies-unique",
            "kind": "problem",
            "pluginId": "prep-sorting-minimum-deletions-to-make-character-frequencies-unique",
            "status": "todo"
          },
          {
            "id": "prep-sorting-sort-integers-by-the-power-value",
            "kind": "problem",
            "pluginId": "prep-sorting-sort-integers-by-the-power-value",
            "status": "todo"
          },
          {
            "id": "prep-sorting-the-number-of-weak-characters-in-the-game",
            "kind": "problem",
            "pluginId": "prep-sorting-the-number-of-weak-characters-in-the-game",
            "status": "todo"
          },
          {
            "id": "prep-sorting-top-k-frequent-elements",
            "kind": "problem",
            "pluginId": "prep-sorting-top-k-frequent-elements",
            "status": "todo"
          }
        ]
      }
    ]
  },
  {
    "id": "prep-math",
    "title": "Math · prep library",
    "summary": "39 Math problems from your prep study collection.",
    "icon": "Sigma",
    "topics": [
      {
        "id": "prep-math-all",
        "title": "Math",
        "items": [
          {
            "id": "prep-math-add-binary",
            "kind": "problem",
            "pluginId": "prep-math-add-binary",
            "status": "todo"
          },
          {
            "id": "prep-math-add-two-big-string-numbers",
            "kind": "problem",
            "pluginId": "prep-math-add-two-big-string-numbers",
            "status": "todo"
          },
          {
            "id": "prep-math-base-26-encoding",
            "kind": "problem",
            "pluginId": "prep-math-base-26-encoding",
            "status": "todo"
          },
          {
            "id": "prep-math-basic-calculator-ii",
            "kind": "problem",
            "pluginId": "prep-math-basic-calculator-ii",
            "status": "todo"
          },
          {
            "id": "prep-math-cinema-seat-allocation",
            "kind": "problem",
            "pluginId": "prep-math-cinema-seat-allocation",
            "status": "todo"
          },
          {
            "id": "prep-math-convert-decimal-to-base-n",
            "kind": "problem",
            "pluginId": "prep-math-convert-decimal-to-base-n",
            "status": "todo"
          },
          {
            "id": "prep-math-convert-string-to-integer",
            "kind": "problem",
            "pluginId": "prep-math-convert-string-to-integer",
            "status": "todo"
          },
          {
            "id": "prep-math-count-set-bits-in-number",
            "kind": "problem",
            "pluginId": "prep-math-count-set-bits-in-number",
            "status": "todo"
          },
          {
            "id": "prep-math-covert-integer-to-roman-numeral",
            "kind": "problem",
            "pluginId": "prep-math-covert-integer-to-roman-numeral",
            "status": "todo"
          },
          {
            "id": "prep-math-factorial-number",
            "kind": "problem",
            "pluginId": "prep-math-factorial-number",
            "status": "todo"
          },
          {
            "id": "prep-math-fibonacci-number",
            "kind": "problem",
            "pluginId": "prep-math-fibonacci-number",
            "status": "todo"
          },
          {
            "id": "prep-math-find-missing-number",
            "kind": "problem",
            "pluginId": "prep-math-find-missing-number",
            "status": "todo"
          },
          {
            "id": "prep-math-find-single-number",
            "kind": "problem",
            "pluginId": "prep-math-find-single-number",
            "status": "todo"
          },
          {
            "id": "prep-math-fizzbuzz",
            "kind": "problem",
            "pluginId": "prep-math-fizzbuzz",
            "status": "todo"
          },
          {
            "id": "prep-math-hamming-distance",
            "kind": "problem",
            "pluginId": "prep-math-hamming-distance",
            "status": "todo"
          },
          {
            "id": "prep-math-integer-to-english-words",
            "kind": "problem",
            "pluginId": "prep-math-integer-to-english-words",
            "status": "todo"
          },
          {
            "id": "prep-math-is-binary",
            "kind": "problem",
            "pluginId": "prep-math-is-binary",
            "status": "todo"
          },
          {
            "id": "prep-math-is-odd-number",
            "kind": "problem",
            "pluginId": "prep-math-is-odd-number",
            "status": "todo"
          },
          {
            "id": "prep-math-is-palindromic-number",
            "kind": "problem",
            "pluginId": "prep-math-is-palindromic-number",
            "status": "todo"
          },
          {
            "id": "prep-math-is-strobogrammatic-number",
            "kind": "problem",
            "pluginId": "prep-math-is-strobogrammatic-number",
            "status": "todo"
          },
          {
            "id": "prep-math-k-closest-points-to-origin",
            "kind": "problem",
            "pluginId": "prep-math-k-closest-points-to-origin",
            "status": "todo"
          },
          {
            "id": "prep-math-log-two",
            "kind": "problem",
            "pluginId": "prep-math-log-two",
            "status": "todo"
          },
          {
            "id": "prep-math-maximum-number-of-visible-points",
            "kind": "problem",
            "pluginId": "prep-math-maximum-number-of-visible-points",
            "status": "todo"
          },
          {
            "id": "prep-math-maximum-split-of-positive-even-integers",
            "kind": "problem",
            "pluginId": "prep-math-maximum-split-of-positive-even-integers",
            "status": "todo"
          },
          {
            "id": "prep-math-maximum-swap",
            "kind": "problem",
            "pluginId": "prep-math-maximum-swap",
            "status": "todo"
          },
          {
            "id": "prep-math-minimum-cost-to-set-cooking-time",
            "kind": "problem",
            "pluginId": "prep-math-minimum-cost-to-set-cooking-time",
            "status": "todo"
          },
          {
            "id": "prep-math-minimum-moves-to-equal-array-elements",
            "kind": "problem",
            "pluginId": "prep-math-minimum-moves-to-equal-array-elements",
            "status": "todo"
          },
          {
            "id": "prep-math-multiply-string-numbers",
            "kind": "problem",
            "pluginId": "prep-math-multiply-string-numbers",
            "status": "todo"
          },
          {
            "id": "prep-math-multiply-strings",
            "kind": "problem",
            "pluginId": "prep-math-multiply-strings",
            "status": "todo"
          },
          {
            "id": "prep-math-next-greater-element-iii",
            "kind": "problem",
            "pluginId": "prep-math-next-greater-element-iii",
            "status": "todo"
          },
          {
            "id": "prep-math-powx-n",
            "kind": "problem",
            "pluginId": "prep-math-powx-n",
            "status": "todo"
          },
          {
            "id": "prep-math-power-two",
            "kind": "problem",
            "pluginId": "prep-math-power-two",
            "status": "todo"
          },
          {
            "id": "prep-math-power-x-of-y",
            "kind": "problem",
            "pluginId": "prep-math-power-x-of-y",
            "status": "todo"
          },
          {
            "id": "prep-math-prime-number",
            "kind": "problem",
            "pluginId": "prep-math-prime-number",
            "status": "todo"
          },
          {
            "id": "prep-math-random-number",
            "kind": "problem",
            "pluginId": "prep-math-random-number",
            "status": "todo"
          },
          {
            "id": "prep-math-random-number-not-in-array",
            "kind": "problem",
            "pluginId": "prep-math-random-number-not-in-array",
            "status": "todo"
          },
          {
            "id": "prep-math-reverse-number",
            "kind": "problem",
            "pluginId": "prep-math-reverse-number",
            "status": "todo"
          },
          {
            "id": "prep-math-square-root",
            "kind": "problem",
            "pluginId": "prep-math-square-root",
            "status": "todo"
          },
          {
            "id": "prep-math-sum-of-digits",
            "kind": "problem",
            "pluginId": "prep-math-sum-of-digits",
            "status": "todo"
          }
        ]
      }
    ]
  },
  {
    "id": "prep-design",
    "title": "Design · prep library",
    "summary": "30 Design problems from your prep study collection.",
    "icon": "Boxes",
    "topics": [
      {
        "id": "prep-design-all",
        "title": "Design",
        "items": [
          {
            "id": "prep-design-amount-of-new-area-painted-each-day",
            "kind": "problem",
            "pluginId": "prep-design-amount-of-new-area-painted-each-day",
            "status": "todo"
          },
          {
            "id": "prep-design-design-in-memory-file-system",
            "kind": "problem",
            "pluginId": "prep-design-design-in-memory-file-system",
            "status": "todo"
          },
          {
            "id": "prep-design-design-parking-system",
            "kind": "problem",
            "pluginId": "prep-design-design-parking-system",
            "status": "todo"
          },
          {
            "id": "prep-design-design-tic-tac-toe",
            "kind": "problem",
            "pluginId": "prep-design-design-tic-tac-toe",
            "status": "todo"
          },
          {
            "id": "prep-design-detect-squares",
            "kind": "problem",
            "pluginId": "prep-design-detect-squares",
            "status": "todo"
          },
          {
            "id": "prep-design-dictionary-and-spell",
            "kind": "problem",
            "pluginId": "prep-design-dictionary-and-spell",
            "status": "todo"
          },
          {
            "id": "prep-design-dot-product-of-two-sparse-vectors",
            "kind": "problem",
            "pluginId": "prep-design-dot-product-of-two-sparse-vectors",
            "status": "todo"
          },
          {
            "id": "prep-design-exclusive-time-of-functions",
            "kind": "problem",
            "pluginId": "prep-design-exclusive-time-of-functions",
            "status": "todo"
          },
          {
            "id": "prep-design-design-an-expression-tree-with-evaluate-function",
            "kind": "problem",
            "pluginId": "prep-design-design-an-expression-tree-with-evaluate-function",
            "status": "todo"
          },
          {
            "id": "prep-design-find-median-from-data-stream",
            "kind": "problem",
            "pluginId": "prep-design-find-median-from-data-stream",
            "status": "todo"
          },
          {
            "id": "prep-design-find-servers-that-handled-most-number-of-requests",
            "kind": "problem",
            "pluginId": "prep-design-find-servers-that-handled-most-number-of-requests",
            "status": "todo"
          },
          {
            "id": "prep-design-guess-the-word",
            "kind": "problem",
            "pluginId": "prep-design-guess-the-word",
            "status": "todo"
          },
          {
            "id": "prep-design-insert-delete-getrandom-o1",
            "kind": "problem",
            "pluginId": "prep-design-insert-delete-getrandom-o1",
            "status": "todo"
          },
          {
            "id": "prep-design-load-balancer",
            "kind": "problem",
            "pluginId": "prep-design-load-balancer",
            "status": "todo"
          },
          {
            "id": "prep-design-log-analyzer",
            "kind": "problem",
            "pluginId": "prep-design-log-analyzer",
            "status": "todo"
          },
          {
            "id": "prep-design-logger-rate-limiter",
            "kind": "problem",
            "pluginId": "prep-design-logger-rate-limiter",
            "status": "todo"
          },
          {
            "id": "prep-design-lru-cache",
            "kind": "problem",
            "pluginId": "prep-design-lru-cache",
            "status": "todo"
          },
          {
            "id": "prep-design-meeting-rooms-iii",
            "kind": "problem",
            "pluginId": "prep-design-meeting-rooms-iii",
            "status": "todo"
          },
          {
            "id": "prep-design-my-calendar-i",
            "kind": "problem",
            "pluginId": "prep-design-my-calendar-i",
            "status": "todo"
          },
          {
            "id": "prep-design-phone-directory",
            "kind": "problem",
            "pluginId": "prep-design-phone-directory",
            "status": "todo"
          },
          {
            "id": "prep-design-random-pick-index",
            "kind": "problem",
            "pluginId": "prep-design-random-pick-index",
            "status": "todo"
          },
          {
            "id": "prep-design-random-pick-with-weight",
            "kind": "problem",
            "pluginId": "prep-design-random-pick-with-weight",
            "status": "todo"
          },
          {
            "id": "prep-design-range-module",
            "kind": "problem",
            "pluginId": "prep-design-range-module",
            "status": "todo"
          },
          {
            "id": "prep-design-read-n-characters-given-read4-ii-call-multiple-times",
            "kind": "problem",
            "pluginId": "prep-design-read-n-characters-given-read4-ii-call-multiple-times",
            "status": "todo"
          },
          {
            "id": "prep-design-rle-iterator",
            "kind": "problem",
            "pluginId": "prep-design-rle-iterator",
            "status": "todo"
          },
          {
            "id": "prep-design-sequentially-ordinal-rank-tracker",
            "kind": "problem",
            "pluginId": "prep-design-sequentially-ordinal-rank-tracker",
            "status": "todo"
          },
          {
            "id": "prep-design-snapshot-array",
            "kind": "problem",
            "pluginId": "prep-design-snapshot-array",
            "status": "todo"
          },
          {
            "id": "prep-design-stock-price-fluctuation",
            "kind": "problem",
            "pluginId": "prep-design-stock-price-fluctuation",
            "status": "todo"
          },
          {
            "id": "prep-design-tiny-url",
            "kind": "problem",
            "pluginId": "prep-design-tiny-url",
            "status": "todo"
          },
          {
            "id": "prep-design-version-control-snapshot",
            "kind": "problem",
            "pluginId": "prep-design-version-control-snapshot",
            "status": "todo"
          }
        ]
      }
    ]
  },
  {
    "id": "prep-streams-io",
    "title": "Streams & I/O · prep library",
    "summary": "12 Streams & I/O problems from your prep study collection.",
    "icon": "Waves",
    "topics": [
      {
        "id": "prep-streams-io-all",
        "title": "Streams & I/O",
        "items": [
          {
            "id": "prep-streams-io-add-spaces-around-parentheses-in",
            "kind": "problem",
            "pluginId": "prep-streams-io-add-spaces-around-parentheses-in",
            "status": "todo"
          },
          {
            "id": "prep-streams-io-binary-tree-in-order-iterator",
            "kind": "problem",
            "pluginId": "prep-streams-io-binary-tree-in-order-iterator",
            "status": "todo"
          },
          {
            "id": "prep-streams-io-check-palindrome-in-stream",
            "kind": "problem",
            "pluginId": "prep-streams-io-check-palindrome-in-stream",
            "status": "todo"
          },
          {
            "id": "prep-streams-io-clean-directories-recursively",
            "kind": "problem",
            "pluginId": "prep-streams-io-clean-directories-recursively",
            "status": "todo"
          },
          {
            "id": "prep-streams-io-count-words-in-file",
            "kind": "problem",
            "pluginId": "prep-streams-io-count-words-in-file",
            "status": "todo"
          },
          {
            "id": "prep-streams-io-file-line-iterator",
            "kind": "problem",
            "pluginId": "prep-streams-io-file-line-iterator",
            "status": "todo"
          },
          {
            "id": "prep-streams-io-find-files-size-larger-than-5m",
            "kind": "problem",
            "pluginId": "prep-streams-io-find-files-size-larger-than-5m",
            "status": "todo"
          },
          {
            "id": "prep-streams-io-find-kth-largest-in-stream",
            "kind": "problem",
            "pluginId": "prep-streams-io-find-kth-largest-in-stream",
            "status": "todo"
          },
          {
            "id": "prep-streams-io-find-median-in-stream",
            "kind": "problem",
            "pluginId": "prep-streams-io-find-median-in-stream",
            "status": "todo"
          },
          {
            "id": "prep-streams-io-merge-k-sorted-streams-in-one",
            "kind": "problem",
            "pluginId": "prep-streams-io-merge-k-sorted-streams-in-one",
            "status": "todo"
          },
          {
            "id": "prep-streams-io-rate-limiter-iterator",
            "kind": "problem",
            "pluginId": "prep-streams-io-rate-limiter-iterator",
            "status": "todo"
          },
          {
            "id": "prep-streams-io-reverse-content-of-file-in-place",
            "kind": "problem",
            "pluginId": "prep-streams-io-reverse-content-of-file-in-place",
            "status": "todo"
          }
        ]
      }
    ]
  },
  {
    "id": "prep-database",
    "title": "Database · prep library",
    "summary": "1 Database problems from your prep study collection.",
    "icon": "Database",
    "topics": [
      {
        "id": "prep-database-all",
        "title": "Database",
        "items": [
          {
            "id": "prep-database-department-top-three-salaries",
            "kind": "problem",
            "pluginId": "prep-database-department-top-three-salaries",
            "status": "todo"
          }
        ]
      }
    ]
  }
];

export const GO_COURSES: CourseDef[] = [
  {
    "id": "go-senior",
    "title": "Go — Senior Developer",
    "summary": "Advanced Go for senior & staff interviews — concurrency, runtime & memory, generics, and system design. Each concept ships an advanced quiz, a coding drill, and a design question.",
    "icon": "Boxes",
    "topics": [
      {
        "id": "go-senior-concurrency",
        "title": "Concurrency & Goroutines",
        "summary": "8 senior concurrency & goroutines concepts.",
        "items": [
          {
            "id": "go-conc-scheduler",
            "kind": "problem",
            "pluginId": "go-conc-scheduler",
            "status": "todo",
            "estimatedMinutes": 12
          },
          {
            "id": "go-conc-channels",
            "kind": "problem",
            "pluginId": "go-conc-channels",
            "status": "todo",
            "estimatedMinutes": 12
          },
          {
            "id": "go-conc-select",
            "kind": "problem",
            "pluginId": "go-conc-select",
            "status": "todo",
            "estimatedMinutes": 12
          },
          {
            "id": "go-conc-context",
            "kind": "problem",
            "pluginId": "go-conc-context",
            "status": "todo",
            "estimatedMinutes": 12
          },
          {
            "id": "go-conc-sync",
            "kind": "problem",
            "pluginId": "go-conc-sync",
            "status": "todo",
            "estimatedMinutes": 12
          },
          {
            "id": "go-conc-worker-pool",
            "kind": "problem",
            "pluginId": "go-conc-worker-pool",
            "status": "todo",
            "estimatedMinutes": 12
          },
          {
            "id": "go-conc-hazards",
            "kind": "problem",
            "pluginId": "go-conc-hazards",
            "status": "todo",
            "estimatedMinutes": 12
          },
          {
            "id": "go-conc-atomic",
            "kind": "problem",
            "pluginId": "go-conc-atomic",
            "status": "todo",
            "estimatedMinutes": 12
          }
        ]
      },
      {
        "id": "go-senior-runtime-memory",
        "title": "Runtime & Memory",
        "summary": "4 senior runtime & memory concepts.",
        "items": [
          {
            "id": "go-mem-stack-heap",
            "kind": "problem",
            "pluginId": "go-mem-stack-heap",
            "status": "todo",
            "estimatedMinutes": 12
          },
          {
            "id": "go-mem-gc",
            "kind": "problem",
            "pluginId": "go-mem-gc",
            "status": "todo",
            "estimatedMinutes": 12
          },
          {
            "id": "go-mem-model",
            "kind": "problem",
            "pluginId": "go-mem-model",
            "status": "todo",
            "estimatedMinutes": 12
          },
          {
            "id": "go-mem-pool-alloc",
            "kind": "problem",
            "pluginId": "go-mem-pool-alloc",
            "status": "todo",
            "estimatedMinutes": 12
          }
        ]
      },
      {
        "id": "go-senior-interfaces-types",
        "title": "Interfaces & Type System",
        "summary": "5 senior interfaces & type system concepts.",
        "items": [
          {
            "id": "go-iface-internals",
            "kind": "problem",
            "pluginId": "go-iface-internals",
            "status": "todo",
            "estimatedMinutes": 12
          },
          {
            "id": "go-iface-nil",
            "kind": "problem",
            "pluginId": "go-iface-nil",
            "status": "todo",
            "estimatedMinutes": 12
          },
          {
            "id": "go-iface-method-sets",
            "kind": "problem",
            "pluginId": "go-iface-method-sets",
            "status": "todo",
            "estimatedMinutes": 12
          },
          {
            "id": "go-iface-embedding",
            "kind": "problem",
            "pluginId": "go-iface-embedding",
            "status": "todo",
            "estimatedMinutes": 12
          },
          {
            "id": "go-iface-assertions",
            "kind": "problem",
            "pluginId": "go-iface-assertions",
            "status": "todo",
            "estimatedMinutes": 12
          }
        ]
      },
      {
        "id": "go-senior-generics",
        "title": "Generics",
        "summary": "4 senior generics concepts.",
        "items": [
          {
            "id": "go-gen-type-params",
            "kind": "problem",
            "pluginId": "go-gen-type-params",
            "status": "todo",
            "estimatedMinutes": 12
          },
          {
            "id": "go-gen-constraints",
            "kind": "problem",
            "pluginId": "go-gen-constraints",
            "status": "todo",
            "estimatedMinutes": 12
          },
          {
            "id": "go-gen-inference",
            "kind": "problem",
            "pluginId": "go-gen-inference",
            "status": "todo",
            "estimatedMinutes": 12
          },
          {
            "id": "go-gen-pitfalls",
            "kind": "problem",
            "pluginId": "go-gen-pitfalls",
            "status": "todo",
            "estimatedMinutes": 12
          }
        ]
      },
      {
        "id": "go-senior-errors",
        "title": "Error Handling",
        "summary": "4 senior error handling concepts.",
        "items": [
          {
            "id": "go-err-wrapping",
            "kind": "problem",
            "pluginId": "go-err-wrapping",
            "status": "todo",
            "estimatedMinutes": 12
          },
          {
            "id": "go-err-sentinel-typed",
            "kind": "problem",
            "pluginId": "go-err-sentinel-typed",
            "status": "todo",
            "estimatedMinutes": 12
          },
          {
            "id": "go-err-panic-recover",
            "kind": "problem",
            "pluginId": "go-err-panic-recover",
            "status": "todo",
            "estimatedMinutes": 12
          },
          {
            "id": "go-err-custom",
            "kind": "problem",
            "pluginId": "go-err-custom",
            "status": "todo",
            "estimatedMinutes": 12
          }
        ]
      },
      {
        "id": "go-senior-slices-maps",
        "title": "Slices, Maps & Data",
        "summary": "4 senior slices, maps & data concepts.",
        "items": [
          {
            "id": "go-data-slice-internals",
            "kind": "problem",
            "pluginId": "go-data-slice-internals",
            "status": "todo",
            "estimatedMinutes": 12
          },
          {
            "id": "go-data-slice-aliasing",
            "kind": "problem",
            "pluginId": "go-data-slice-aliasing",
            "status": "todo",
            "estimatedMinutes": 12
          },
          {
            "id": "go-data-maps",
            "kind": "problem",
            "pluginId": "go-data-maps",
            "status": "todo",
            "estimatedMinutes": 12
          },
          {
            "id": "go-data-strings-runes",
            "kind": "problem",
            "pluginId": "go-data-strings-runes",
            "status": "todo",
            "estimatedMinutes": 12
          }
        ]
      },
      {
        "id": "go-senior-stdlib-idioms",
        "title": "Standard Library & Idioms",
        "summary": "4 senior standard library & idioms concepts.",
        "items": [
          {
            "id": "go-std-io",
            "kind": "problem",
            "pluginId": "go-std-io",
            "status": "todo",
            "estimatedMinutes": 12
          },
          {
            "id": "go-std-json",
            "kind": "problem",
            "pluginId": "go-std-json",
            "status": "todo",
            "estimatedMinutes": 12
          },
          {
            "id": "go-std-time",
            "kind": "problem",
            "pluginId": "go-std-time",
            "status": "todo",
            "estimatedMinutes": 12
          },
          {
            "id": "go-std-defer-idioms",
            "kind": "problem",
            "pluginId": "go-std-defer-idioms",
            "status": "todo",
            "estimatedMinutes": 12
          }
        ]
      },
      {
        "id": "go-senior-performance",
        "title": "Performance & Profiling",
        "summary": "4 senior performance & profiling concepts.",
        "items": [
          {
            "id": "go-perf-benchmarks",
            "kind": "problem",
            "pluginId": "go-perf-benchmarks",
            "status": "todo",
            "estimatedMinutes": 12
          },
          {
            "id": "go-perf-pprof",
            "kind": "problem",
            "pluginId": "go-perf-pprof",
            "status": "todo",
            "estimatedMinutes": 12
          },
          {
            "id": "go-perf-allocations",
            "kind": "problem",
            "pluginId": "go-perf-allocations",
            "status": "todo",
            "estimatedMinutes": 12
          },
          {
            "id": "go-perf-datastructures",
            "kind": "problem",
            "pluginId": "go-perf-datastructures",
            "status": "todo",
            "estimatedMinutes": 12
          }
        ]
      },
      {
        "id": "go-senior-testing",
        "title": "Testing & Reliability",
        "summary": "4 senior testing & reliability concepts.",
        "items": [
          {
            "id": "go-test-table",
            "kind": "problem",
            "pluginId": "go-test-table",
            "status": "todo",
            "estimatedMinutes": 12
          },
          {
            "id": "go-test-parallel",
            "kind": "problem",
            "pluginId": "go-test-parallel",
            "status": "todo",
            "estimatedMinutes": 12
          },
          {
            "id": "go-test-fuzz",
            "kind": "problem",
            "pluginId": "go-test-fuzz",
            "status": "todo",
            "estimatedMinutes": 12
          },
          {
            "id": "go-test-doubles",
            "kind": "problem",
            "pluginId": "go-test-doubles",
            "status": "todo",
            "estimatedMinutes": 12
          }
        ]
      },
      {
        "id": "go-senior-design",
        "title": "System Design in Go",
        "summary": "5 senior system design in go concepts.",
        "items": [
          {
            "id": "go-design-rate-limiter",
            "kind": "problem",
            "pluginId": "go-design-rate-limiter",
            "status": "todo",
            "estimatedMinutes": 12
          },
          {
            "id": "go-design-worker-pool",
            "kind": "problem",
            "pluginId": "go-design-worker-pool",
            "status": "todo",
            "estimatedMinutes": 12
          },
          {
            "id": "go-design-lru-cache",
            "kind": "problem",
            "pluginId": "go-design-lru-cache",
            "status": "todo",
            "estimatedMinutes": 12
          },
          {
            "id": "go-design-graceful-shutdown",
            "kind": "problem",
            "pluginId": "go-design-graceful-shutdown",
            "status": "todo",
            "estimatedMinutes": 12
          },
          {
            "id": "go-design-pipeline",
            "kind": "problem",
            "pluginId": "go-design-pipeline",
            "status": "todo",
            "estimatedMinutes": 12
          }
        ]
      }
    ]
  }
];

export interface GoBrowseCategory {
  id: string;
  title: string;
  summary: string;
  icon: string;
  courseTopicId: string;
}

export const GO_BROWSE_CATEGORIES: GoBrowseCategory[] = [
  {
    "id": "go-senior-concurrency",
    "title": "Concurrency & Goroutines",
    "summary": "8 senior concurrency & goroutines concepts.",
    "icon": "Workflow",
    "courseTopicId": "go-senior-concurrency"
  },
  {
    "id": "go-senior-runtime-memory",
    "title": "Runtime & Memory",
    "summary": "4 senior runtime & memory concepts.",
    "icon": "Cpu",
    "courseTopicId": "go-senior-runtime-memory"
  },
  {
    "id": "go-senior-interfaces-types",
    "title": "Interfaces & Type System",
    "summary": "5 senior interfaces & type system concepts.",
    "icon": "Shapes",
    "courseTopicId": "go-senior-interfaces-types"
  },
  {
    "id": "go-senior-generics",
    "title": "Generics",
    "summary": "4 senior generics concepts.",
    "icon": "Braces",
    "courseTopicId": "go-senior-generics"
  },
  {
    "id": "go-senior-errors",
    "title": "Error Handling",
    "summary": "4 senior error handling concepts.",
    "icon": "TriangleAlert",
    "courseTopicId": "go-senior-errors"
  },
  {
    "id": "go-senior-slices-maps",
    "title": "Slices, Maps & Data",
    "summary": "4 senior slices, maps & data concepts.",
    "icon": "Table",
    "courseTopicId": "go-senior-slices-maps"
  },
  {
    "id": "go-senior-stdlib-idioms",
    "title": "Standard Library & Idioms",
    "summary": "4 senior standard library & idioms concepts.",
    "icon": "Library",
    "courseTopicId": "go-senior-stdlib-idioms"
  },
  {
    "id": "go-senior-performance",
    "title": "Performance & Profiling",
    "summary": "4 senior performance & profiling concepts.",
    "icon": "Gauge",
    "courseTopicId": "go-senior-performance"
  },
  {
    "id": "go-senior-testing",
    "title": "Testing & Reliability",
    "summary": "4 senior testing & reliability concepts.",
    "icon": "FlaskConical",
    "courseTopicId": "go-senior-testing"
  },
  {
    "id": "go-senior-design",
    "title": "System Design in Go",
    "summary": "5 senior system design in go concepts.",
    "icon": "Blocks",
    "courseTopicId": "go-senior-design"
  }
];
