/**
 * Generates the eager plugin META index + light course defs consumed by the
 * catalog/sidebar/registry, so the heavy per-group implementations can stay behind
 * dynamic import().  Run: `npm run build-plugin-meta`  (check: `--check`).
 *
 * It imports the built plugin arrays + course defs at build time (Node, via
 * vite-node) and writes:
 *   src/plugins/_generated/pluginMeta.ts   — PLUGIN_META (id → meta + group)
 *   src/plugins/_generated/courses.ts      — IMPORTED/PREP/GO course defs + browse cats
 *
 * Guarded by `npm run check-plugin-meta` so the generated files can't drift.
 */
import { writeFileSync, readFileSync, existsSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import type { ProblemPlugin } from '@/core/types';
import type { PluginGroup } from '@/plugins';
import { curatedPlugins } from '@/plugins';
import { importedPlugins, importedCourses } from '@/plugins/imported';
import { prepPlugins, prepCourses } from '@/plugins/imported/prep';
import { goCoursePlugins, goCourses, goBrowseCategories, GO_COURSE_ID } from '@/plugins/go-course';
import { openrtbPlugins, openrtbCourses, openrtbBrowseCategories, OPENRTB_COURSE_ID } from '@/plugins/openrtb';

const outDir = join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'plugins', '_generated');

const GROUPS: [PluginGroup, ProblemPlugin<any, any>[]][] = [
  ['curated', curatedPlugins],
  ['imported', importedPlugins],
  ['prep', prepPlugins],
  ['go-course', goCoursePlugins],
  ['openrtb', openrtbPlugins],
];

interface MetaEntry {
  id: string;
  title: string;
  number?: string;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  tags: string[];
  summary: string;
  source?: string;
  group: PluginGroup;
}

const metas: MetaEntry[] = [];
const seen = new Set<string>();
for (const [group, plugins] of GROUPS) {
  for (const p of plugins) {
    const m = p.meta;
    if (seen.has(m.id)) continue; // first registration wins, mirroring the registry
    seen.add(m.id);
    metas.push({
      id: m.id,
      title: m.title,
      ...(m.number ? { number: m.number } : {}),
      difficulty: m.difficulty,
      tags: m.tags,
      summary: m.summary,
      ...(m.source ? { source: m.source } : {}),
      group,
    });
  }
}

const BANNER = '// AUTO-GENERATED by scripts/build-plugin-meta.mts — do not edit by hand.\n// Run `npm run build-plugin-meta` after changing any plugin metadata or catalog.\n';

const metaFile =
  BANNER +
  `import type { PluginGroup } from '..';\n\n` +
  `export interface PluginMetaEntry {\n` +
  `  id: string;\n  title: string;\n  number?: string;\n  difficulty: 'Easy' | 'Medium' | 'Hard';\n` +
  `  tags: string[];\n  summary: string;\n  source?: string;\n  group: PluginGroup;\n}\n\n` +
  `export const PLUGIN_META: PluginMetaEntry[] = ${JSON.stringify(metas, null, 2)};\n`;

const coursesFile =
  BANNER +
  `import type { CourseDef } from '@/content/types';\n\n` +
  `export const GO_COURSE_ID = ${JSON.stringify(GO_COURSE_ID)};\n\n` +
  `export const OPENRTB_COURSE_ID = ${JSON.stringify(OPENRTB_COURSE_ID)};\n\n` +
  `export const IMPORTED_COURSES: CourseDef[] = ${JSON.stringify(importedCourses, null, 2)};\n\n` +
  `export const PREP_COURSES: CourseDef[] = ${JSON.stringify(prepCourses, null, 2)};\n\n` +
  `export const GO_COURSES: CourseDef[] = ${JSON.stringify(goCourses, null, 2)};\n\n` +
  `export const OPENRTB_COURSES: CourseDef[] = ${JSON.stringify(openrtbCourses, null, 2)};\n\n` +
  `export interface GoBrowseCategory {\n  id: string;\n  title: string;\n  summary: string;\n  icon: string;\n  courseTopicId: string;\n}\n\n` +
  `export const GO_BROWSE_CATEGORIES: GoBrowseCategory[] = ${JSON.stringify(goBrowseCategories, null, 2)};\n\n` +
  `export interface OpenRTBBrowseCategory {\n  id: string;\n  title: string;\n  summary: string;\n  icon: string;\n  courseTopicId: string;\n}\n\n` +
  `export const OPENRTB_BROWSE_CATEGORIES: OpenRTBBrowseCategory[] = ${JSON.stringify(openrtbBrowseCategories, null, 2)};\n`;

const targets: [string, string][] = [
  [join(outDir, 'pluginMeta.ts'), metaFile],
  [join(outDir, 'courses.ts'), coursesFile],
];

const check = process.argv.includes('--check');
let drift = false;
for (const [path, content] of targets) {
  const current = existsSync(path) ? readFileSync(path, 'utf8') : null;
  if (current === content) continue;
  if (check) {
    drift = true;
    console.error(`✗ ${path.split('/').slice(-2).join('/')} is out of date — run \`npm run build-plugin-meta\`.`);
  } else {
    mkdirSync(outDir, { recursive: true });
    writeFileSync(path, content);
    console.log(`✓ wrote ${path.split('/').slice(-2).join('/')}`);
  }
}

if (check && drift) process.exit(1);
if (check) console.log(`✓ plugin meta up to date (${metas.length} plugins).`);
else console.log(`✓ generated meta for ${metas.length} plugins across ${GROUPS.length} groups.`);
