/**
 * Per-problem mnemonic icons — a distinct, memorable little picture for each problem,
 * keyed by the item/plugin id. Inner SVG markup only (no <svg> wrapper), drawn in a
 * 0 0 48 48 viewBox; strokes inherit currentColor with var(--accent)/good/bad focal
 * detail. The board falls back to the per-shape glyph when an id is absent here.
 *
 * Generated by the problem-mnemonic-icons workflow; safe to hand-edit individual entries.
 */
export const PROBLEM_GLYPHS: Readonly<Record<string, string>> = {
  'binary-search':
    '<path d="M7 31h34"/><path d="M11 28v6M17 28v6M24 27v8M31 28v6M37 28v6"/><path d="M13 37l4-3M35 37l-4-3" stroke="var(--accent)"/><circle cx="24" cy="17" r="7" stroke="var(--accent)"/><path d="M29 22l5 5" stroke="var(--accent)"/><path d="M24 14v6M21 17h6" stroke="var(--accent)"/>',
  'bubble-sort':
    '<path d="M6 42c4-3 32-3 36 0"/><circle cx="15" cy="30" r="4"/><circle cx="24" cy="22" r="5"/><circle cx="32" cy="13" r="6" stroke="var(--accent)"/><circle cx="30" cy="11" r="1.3" fill="var(--accent)" stroke="none"/><circle cx="11" cy="36" r="2"/>',
  'heap-operations':
    '<path d="M8 40h32"/><path d="M13 40l11-16 11 16z"/><path d="M19 36v-9M19 27l-2.5 3M19 27l2.5 3" stroke="var(--accent)"/><path d="M29 25v9M29 34l-2.5-3M29 34l2.5-3"/>',
  'heap-sort':
    '<path d="M8 41h30"/><path d="M12 41l9-15 9 15z"/><path d="M16 41l5-8 5 8"/><path d="M33 5v6" stroke="var(--accent)"/><path d="M30 11h6" stroke="var(--accent)"/><path d="M33 11v3" stroke="var(--accent)"/><circle cx="33" cy="17" r="3" fill="var(--accent)" stroke="none"/>',
  'imp-0-01-bfs-shortest-reach':
    '<circle cx="17" cy="31" r="3" fill="var(--accent)" stroke="none"/><path d="M17 31a9 9 0 0 1 9-9"/><path d="M17 31a16 16 0 0 1 16-16"/><path d="M17 31a23 23 0 0 1 23-23"/><circle cx="26" cy="22" r="2"/><circle cx="33" cy="15" r="2"/>',
  'imp-0-02-clone-graph':
    '<rect x="7" y="18" width="24" height="14" rx="2"/><path d="M11 18v-6h16v6"/><circle cx="17" cy="9" r="1.4"/><circle cx="23" cy="9" r="1.4"/><path d="M17 9h6"/><path d="M11 25h16"/><rect x="34" y="22" width="10" height="13" rx="1.5" stroke="var(--accent)"/><circle cx="37" cy="27" r="1.3" fill="var(--accent)" stroke="none"/><circle cx="41" cy="27" r="1.3" fill="var(--accent)" stroke="none"/><path d="M37 27h4" stroke="var(--accent)"/>',
  'imp-0-03-find-shortest-path-with-bfs':
    '<circle cx="9" cy="37" r="2.5"/><path d="M14 35h2M19 33h2M24 31h2M29 29h2"/><path d="M36 28V11"/><path d="M36 11h8v6h-8z" fill="var(--accent)" stroke="var(--accent)"/><path d="M33 39h6"/>',
  'imp-0-04-graph-traversal':
    '<circle cx="12" cy="15" r="3"/><circle cx="28" cy="12" r="3"/><circle cx="20" cy="28" r="3"/><path d="M15 16l3 10M26 14l-4 12"/><circle cx="33" cy="31" r="6" stroke="var(--accent)"/><path d="M37 35l5 5" stroke="var(--accent)"/>',
  'imp-0-05-has-path-from-source-to-destination':
    '<path d="M11 9a4 4 0 014 4c0 3-4 7-4 7s-4-4-4-7a4 4 0 014-4z"/><circle cx="11" cy="13" r="1.3"/><path d="M38 24a4 4 0 014 4c0 3-4 7-4 7s-4-4-4-7a4 4 0 014-4z"/><circle cx="38" cy="28" r="1.3"/><path d="M13 21c5 7 13 4 22 9" stroke-dasharray="3 3"/><path d="M22 36l3 4 6-8" stroke="var(--good)"/>',
  'imp-0-06-print-all-paths-from-source-to-destination':
    '<circle cx="8" cy="24" r="3"/><path d="M11 23c8-9 17-9 26-10M11 24h26M11 25c8 9 17 9 26 10"/><rect x="37" y="10" width="7" height="8" rx="1" fill="var(--accent)" stroke="none"/><rect x="37" y="20" width="7" height="8" rx="1" fill="var(--accent)" stroke="none"/><rect x="37" y="30" width="7" height="8" rx="1" fill="var(--accent)" stroke="none"/>',
  'imp-0-07-shortest-distance-from-all-buildings':
    '<rect x="8" y="23" width="7" height="15"/><rect x="17" y="16" width="7" height="22"/><rect x="26" y="27" width="7" height="11"/><path d="M10 26h3M19 20h3M19 25h3M28 30h3"/><path d="M34 20a14 14 0 015 14" stroke="var(--accent)"/><path d="M37 24a9 9 0 013 9" stroke="var(--accent)"/>',
  'imp-0-08-topological-sort-with-dfs':
    '<ellipse cx="22" cy="15" rx="13" ry="3.5"/><ellipse cx="22" cy="23" rx="13" ry="3.5"/><ellipse cx="22" cy="31" rx="13" ry="3.5"/><path d="M38 21c5 3 5 10 0 13" stroke="var(--accent)"/><path d="M38 34l-1-4 4 0" stroke="var(--accent)"/>',
  'imp-1-subset-component':
    '<path d="M11 10c-3 0-3 28 0 28M11 10h3M11 38h3"/><circle cx="22" cy="22" r="7"/><circle cx="31" cy="22" r="7"/><circle cx="22" cy="22" r="1.5" fill="var(--accent)" stroke="none"/><circle cx="31" cy="22" r="1.5" fill="var(--accent)" stroke="none"/><path d="M37 10c3 0 3 28 0 28M37 10h-3M37 38h-3"/>',
  'imp-10-word-ladder':
    '<path d="M15 7v34M33 7v34"/><path d="M15 14h18M15 22h18M15 30h18M15 38h18"/><path d="M15 18h18" stroke="var(--accent)"/><circle cx="24" cy="18" r="2.2" fill="var(--accent)" stroke="var(--accent)"/>',
  'imp-11-shortest-path-in-a-grid-with-obstacles-eliminati':
    '<rect x="8" y="12" width="30" height="24" rx="2"/><path d="M18 12v24M28 12v24M8 20h30M8 28h30" stroke-opacity="0.35"/><path d="M9 13l8 6M17 13l-8 6" stroke="var(--bad)"/><rect x="20" y="22" width="4" height="5" rx="1"/><path d="M24 22c2-1 4 0 5-2"/><circle cx="30" cy="19" r="1.6" fill="var(--accent)" stroke="var(--accent)"/><path d="M30 17c1-1.5 0-3-1-2" stroke="var(--accent)"/>',
  'imp-12-shortest-path-in-binary-matrix':
    '<rect x="7" y="7" width="34" height="34" rx="2"/><path d="M18.3 7v34M29.7 7v34M7 18.3h34M7 29.7h34" stroke-opacity="0.35"/><path d="M12 12l25 25" stroke="var(--accent)"/><path d="M37 37l-7-.5M37 37l-.5-7" stroke="var(--accent)"/><path d="M12.5 12.5m-3 0a3 3 0 1 0 6 0a3 3 0 1 0 -6 0" stroke-opacity="0.7"/><path d="M12.5 9v7M9 12.5h7" stroke-opacity="0.7"/>',
  'imp-13-robot-room-cleaner':
    '<path d="M11 33c0-7 6-12 13-12s13 5 13 12"/><path d="M9 33h30"/><circle cx="18" cy="29" r="2"/><circle cx="30" cy="29" r="2" fill="var(--accent)" stroke="none"/><path d="M24 21v-5M24 16l-3-2M24 16l3-2"/><path d="M14 38c3 0 3-2 6-2s3 2 6 2 3-2 6-2" stroke="var(--accent)"/>',
  'imp-14-the-earliest-moment-when-everyone-become-friends':
    '<circle cx="24" cy="12" r="6"/><path d="M24 8v4l3 2" stroke="var(--accent)"/><circle cx="14" cy="29" r="3.5"/><circle cx="34" cy="29" r="3.5"/><path d="M14 33v7M34 33v7"/><path d="M16.5 35l5 2.5 5-2.5 5 2.5" stroke="var(--accent)"/>',
  'imp-15-find-all-possible-recipes-from-given-supplies':
    '<path d="M11 25h26v3a10 10 0 0 1-10 10h-6a10 10 0 0 1-10-10z"/><path d="M7 25h34"/><path d="M17 25c-3-4-1-8 2-8-1-3 7-4 5 0 4-1 5 4 2 8" stroke="var(--accent)"/><path d="M16 32l3 3 6-6" stroke="var(--good)"/>',
  'imp-16-detonate-the-maximum-bombs':
    '<circle cx="22" cy="28" r="9"/><path d="M28 22l3-3M31 19c0-2 2-2 2-4" stroke="var(--accent)"/><path d="M33 13l1 2 2 1-2 1-1 2-1-2-2-1 2-1z" fill="var(--accent)" stroke="none"/><circle cx="22" cy="28" r="15" stroke-dasharray="3 3" stroke-opacity="0.6"/><path d="M19 25l3-3 2 2"/>',
  'imp-17-maximal-network-rank':
    '<circle cx="17" cy="24" r="4" stroke="var(--accent)"/><circle cx="31" cy="24" r="4" stroke="var(--accent)"/><path d="M21 24h6" stroke="var(--accent)"/><circle cx="9" cy="12" r="2.5"/><circle cx="9" cy="36" r="2.5"/><circle cx="39" cy="12" r="2.5"/><circle cx="39" cy="36" r="2.5"/><path d="M14.5 21.5 11 14M14.5 26.5 11 34M33.5 21.5 37 14M33.5 26.5 37 34"/>',
  'imp-18-number-of-good-paths':
    '<circle cx="11" cy="16" r="3"/><circle cx="37" cy="16" r="3"/><circle cx="24" cy="34" r="3"/><path d="M13 18l9 14M35 18l-9 14"/><path d="M11 8l1.1 2.2 2.4.3-1.8 1.7.5 2.4L11 13.4 8.8 14.6l.5-2.4-1.8-1.7 2.4-.3z" fill="var(--accent)" stroke="none"/><path d="M37 8l1.1 2.2 2.4.3-1.8 1.7.5 2.4L37 13.4l-2.2 1.2.5-2.4-1.8-1.7 2.4-.3z" fill="var(--accent)" stroke="none"/>',
  'imp-19-maximum-score-of-a-node-sequence':
    '<circle cx="9" cy="31" r="3"/><circle cx="20" cy="25" r="3"/><circle cx="31" cy="25" r="3"/><circle cx="42" cy="19" r="3"/><path d="M11.6 29.5 17.4 26.5"/><path d="M23 25h5" stroke="var(--accent)"/><path d="M33.6 23.5 39.4 20.5"/><path d="M13 39c4-3 9-6 13-9s9-6 13-9M39 21v-6h-6" stroke="var(--good)"/>',
  'imp-2-alien-dictionary':
    '<circle cx="24" cy="13" r="6"/><path d="M20 6l-2-3M28 6l2-3"/><circle cx="21" cy="13" r="1.4" fill="var(--accent)" stroke="none"/><circle cx="27" cy="13" r="1.4" fill="var(--accent)" stroke="none"/><path d="M24 28c-6-3-11-1-11-1v13s5-2 11 1c6-3 11 1 11 1V27s-5-2-11 1z"/><path d="M24 28v14"/>',
  'imp-20-course-schedule':
    '<path d="M24 12 8 18l16 6 16-6z"/><path d="M16 21v6c0 2 4 4 8 4s8-2 8-4v-6"/><path d="M40 18v7" stroke="var(--accent)"/><circle cx="40" cy="27" r="1.6" fill="var(--accent)" stroke="none"/><path d="M10 36h24M13 40h18"/><path d="M34 40l4-2-4-2" stroke="var(--accent)"/>',
  'imp-22-find-degree-of-vertex':
    '<circle cx="24" cy="28" r="5"/><path d="M15 16h18l-9-4z"/><path d="M24 16v4"/><path d="M30 12v4a1.5 1.5 0 0 0 1.5 1.5"/><path d="M19.7 31.5 11 38M28.3 31.5 37 38M22 23 14 14M26 23 34 14" stroke="var(--accent)"/>',
  'imp-23-detect-cycle':
    '<path d="M14 34c-4-3-4-10 1-13s11-2 14 3 1 10-4 13" stroke="var(--accent)"/><path d="M21 38l-4-2 4-3" stroke="var(--accent)"/><circle cx="31" cy="18" r="7"/><path d="M36 23l5 5"/>',
  'imp-24-number-of-islands':
    '<path d="M4 38c3-2 6-2 9 0s6 2 9 0 6-2 9 0 6 2 9 0" stroke="var(--good)"/><path d="M16 35c4 1 8 1 12 0"/><path d="M21 35c-1-6 0-10 1-13"/><path d="M22 22c-4-2-8 0-9 3M22 22c4-2 8 0 9 3M22 22c-2-4 0-7 3-8" stroke="var(--accent)"/>',
  'imp-25-critical-connections-in-a-network':
    '<path d="M6 33c0-4 3-7 7-7s7 3 7 7M28 33c0-4 3-7 7-7s7 3 7 7"/><path d="M20 31h8" stroke="var(--accent)"/><path d="M24 28l-2 3 3 1-2 3" stroke="var(--accent)"/><path d="M6 38h14M28 38h14"/>',
  'imp-26-subsets':
    '<rect x="7" y="9" width="18" height="14" rx="2"/><path d="M7 13h18"/><path d="M22 22l6 7M18 23l1 7"/><rect x="28" y="28" width="8" height="8" rx="1.5" stroke="var(--accent)"/><rect x="14" y="30" width="7" height="7" rx="1.5"/>',
  'imp-27-combinations':
    '<circle cx="21" cy="19" r="11"/><circle cx="18" cy="17" r="2.5"/><circle cx="25" cy="21" r="2.5"/><path d="M14 30v4h16v-4"/><circle cx="19" cy="38" r="2.5" fill="var(--accent)" stroke="none"/><circle cx="26" cy="38" r="2.5"/>',
  'imp-28-combination-of-subset-strings':
    '<rect x="6" y="15" width="16" height="12" rx="2"/><circle cx="11" cy="21" r="1.6"/><circle cx="17" cy="21" r="1.6"/><path d="M22 21h6"/><rect x="28" y="16" width="7" height="7" rx="1" stroke="var(--accent)"/><rect x="35" y="16" width="7" height="7" rx="1"/><path d="M30 23v5M37 23v5" stroke="var(--accent)"/>',
  'imp-29-combination-sum-ii':
    '<path d="M24 8v6"/><path d="M12 14h24"/><path d="M12 14l-5 9h10z"/><path d="M36 14l5 9h-10z"/><path d="M24 14v22M17 38h14"/><path d="M20 16l8 6M28 16l-8 6" stroke="var(--accent)"/>',
  'imp-3-remove-invalid-parentheses':
    '<path d="M19 13c-6 5-6 17 0 22"/><path d="M29 13c6 5 6 17 0 22"/><circle cx="12" cy="19" r="3"/><circle cx="12" cy="27" r="3"/><path d="M14.5 20.5 29 14" stroke="var(--accent)"/><path d="M14.5 25.5 27 32" stroke="var(--accent)"/>',
  'imp-30-decode-numbers':
    '<rect x="11" y="22" width="19" height="15" rx="2"/><path d="M15 22v-4a5.5 5.5 0 0 1 11 0v4"/><path d="M20.5 28v4"/><path d="M35 13l5 5-9 9-5-5z" stroke="var(--accent)"/><path d="M35 13l2-2 5 5-2 2" stroke="var(--accent)"/>',
  'imp-31-expression-add-operators':
    '<rect x="6" y="19" width="9" height="13" rx="1.5"/><rect x="19.5" y="19" width="9" height="13" rx="1.5"/><rect x="33" y="19" width="9" height="13" rx="1.5"/><path d="M9 25.5h3M23 25.5h2M36 25.5h3"/><path d="M15.5 14l5 5M20.5 14l-5 5" stroke="var(--accent)"/><path d="M29.5 37h4"/>',
  'imp-32-generate-binary-strings':
    '<circle cx="24" cy="11" r="4"/><path d="M21 14l-8 8M27 14l8 8"/><circle cx="12" cy="26" r="4"/><circle cx="36" cy="26" r="4"/><path d="M12 22v8"/><path d="M34 24l4 4" stroke="var(--accent)"/><path d="M12 36v4M36 36v4"/>',
  'imp-33-strobogrammatic-number-ii':
    '<rect x="10" y="15" width="28" height="18" rx="3"/><circle cx="19" cy="22" r="3" stroke="var(--accent)"/><path d="M22 22v5" stroke="var(--accent)"/><circle cx="29" cy="26" r="3" stroke="var(--accent)"/><path d="M26 26v-5" stroke="var(--accent)"/><path d="M16 39c3 2 13 2 16 0"/><path d="M30 36l3 2-1 3"/>',
  'imp-34-generate-parentheses':
    '<path d="M18 10c-8 6-8 22 0 28"/><path d="M30 10c8 6 8 22 0 28"/><path d="M20 25l3 4 6-9" stroke="var(--accent)"/>',
  'imp-36-letter-combinations-of-a-phone-number':
    '<rect x="13" y="7" width="22" height="34" rx="3"/><circle cx="19" cy="15" r="2"/><circle cx="29" cy="15" r="2" stroke="var(--accent)"/><circle cx="19" cy="24" r="2"/><circle cx="29" cy="24" r="2"/><circle cx="19" cy="33" r="2"/><circle cx="29" cy="33" r="2"/><path d="M34 12l5-3M34 15h6M34 18l5 3" stroke="var(--accent)"/>',
  'imp-37-maximum-length-of-a-concatenated-string-with-uni':
    '<path d="M7 18h11v3a2 2 0 004 0v-3h2v12h-2a2 2 0 00-4 0v0h-11z"/><path d="M41 18h-11v3a2 2 0 01-4 0v-3" fill="none"/><rect x="26" y="18" width="15" height="12" rx="0"/><circle cx="24" cy="24" r="2.4" fill="var(--accent)" stroke="none"/>',
  'imp-38-nested-list-weight-sum':
    '<rect x="7" y="9" width="34" height="30" rx="2"/><rect x="14" y="15" width="22" height="19" rx="2"/><rect x="21" y="21" width="11" height="8" rx="1.5" stroke="var(--accent)"/><path d="M24.5 25h4" stroke="var(--accent)"/><path d="M10 13h2M17 19h2"/>',
  'imp-39-different-ways-to-add-parentheses':
    '<path d="M8 30h12M28 30h12"/><circle cx="14" cy="32" r="2.5"/><circle cx="34" cy="32" r="2.5"/><circle cx="22" cy="19" r="2.6" stroke="var(--accent)"/><circle cx="22" cy="27" r="2.6" stroke="var(--accent)"/><path d="M23.5 21l9 8M23.5 25l9-8" stroke="var(--accent)"/>',
  'imp-4-floyd-city-of-blinding-lights':
    '<path d="M7 41V25h8v16M19 41V15h9v26M32 41V21h9v20"/><path d="M11 30v2M11 35v2M23 21v2M23 27v2M23 33v2M36 27v2M36 33v2" stroke-opacity="0.5"/><circle cx="23" cy="9" r="3" fill="var(--accent)" stroke="none"/><path d="M23 2v3M16 6l2 2M30 6l-2 2M14 11h3M29 11h3" stroke="var(--accent)"/>',
  'imp-40-restore-ip-addresses':
    '<rect x="6" y="19" width="36" height="12" rx="2"/><path d="M15 21v8M24 21v8M33 21v8"/><path d="M9 25h3M18 25h3M27 25h3M36 25h3"/><circle cx="15" cy="36" r="1.6" fill="var(--accent)" stroke="none"/><circle cx="24" cy="36" r="1.6" fill="var(--accent)" stroke="none"/><circle cx="33" cy="36" r="1.6" fill="var(--accent)" stroke="none"/>',
  'imp-41-permutations':
    '<circle cx="15" cy="13" r="3"/><path d="M15 16v8M11 19l4 1 4-1M15 24l-3 7M15 24l3 7"/><circle cx="33" cy="13" r="3"/><path d="M33 16v8M29 19l4 1 4-1M33 24l-3 7M33 24l3 7"/><path d="M19 9c3-3 7-3 10 0" stroke="var(--accent)"/><path d="M29 9l1-3-3 0" stroke="var(--accent)"/><path d="M29 11c-3 3-7 3-10 0" stroke="var(--accent)"/><path d="M19 11l-1 3 3 0" stroke="var(--accent)"/>',
  'imp-42-cartesian-product-of-multiple-arrays':
    '<rect x="8" y="9" width="32" height="30" rx="2"/><line x1="8" y1="19" x2="40" y2="19"/><line x1="8" y1="29" x2="40" y2="29"/><line x1="19" y1="9" x2="19" y2="39"/><line x1="29" y1="9" x2="29" y2="39"/><circle cx="13.5" cy="14" r="2.4" fill="var(--accent)" stroke="none"/><circle cx="24" cy="24" r="2.4" fill="var(--accent)" stroke="none"/><circle cx="34.5" cy="34" r="2.4" fill="var(--accent)" stroke="none"/>',
  'imp-43-permutations':
    '<rect x="7" y="20" width="9" height="9" rx="1.5"/><rect x="19" y="20" width="9" height="9" rx="1.5"/><rect x="31" y="20" width="9" height="9" rx="1.5"/><path d="M12 18c5-5 19-5 24 0" stroke="var(--accent)"/><path d="M36 18l0-3-3 1" stroke="var(--accent)"/><path d="M36 31c-5 5-19 5-24 0" stroke="var(--accent)"/><path d="M12 31l0 3 3-1" stroke="var(--accent)"/>',
  'imp-44-word-search':
    '<rect x="7" y="7" width="24" height="24" rx="2"/><line x1="15" y1="7" x2="15" y2="31"/><line x1="23" y1="7" x2="23" y2="31"/><line x1="7" y1="15" x2="31" y2="15"/><line x1="7" y1="23" x2="31" y2="23"/><path d="M11 11l8 8 4 8" stroke="var(--accent)"/><circle cx="33" cy="33" r="6" stroke="var(--accent)"/><line x1="37.5" y1="37.5" x2="42" y2="42" stroke="var(--accent)"/>',
  'imp-45-word-search-ii':
    '<rect x="6" y="28" width="30" height="14" rx="2"/><line x1="16" y1="28" x2="16" y2="42"/><line x1="26" y1="28" x2="26" y2="42"/><line x1="6" y1="35" x2="36" y2="35"/><circle cx="21" cy="8" r="2.5" fill="var(--accent)" stroke="none"/><path d="M21 10.5l-7 7M21 10.5l7 7" stroke="var(--accent)"/><circle cx="14" cy="20" r="2.2"/><circle cx="28" cy="20" r="2.2"/><path d="M14 22v6M28 22v6"/><path d="M39 8h3v8M39 16h3" stroke="var(--accent)"/>',
  'imp-46-search-in-rotated-sorted-array':
    '<circle cx="22" cy="24" r="15"/><path d="M22 9v15l8 5"/><path d="M22 9l-3-5M22 9l3-5" stroke="var(--accent)"/><circle cx="35" cy="32" r="4" stroke="var(--accent)"/><path d="M35 28v8M31 32h8" stroke="var(--accent)"/>',
  'imp-47-maximum-length-of-ribbon-cut':
    '<path d="M6 24h36"/><path d="M16 21v6M26 21v6" stroke="var(--accent)"/><circle cx="36" cy="17" r="3"/><circle cx="36" cy="31" r="3"/><path d="M33.5 19l-7 4M33.5 29l-7-4" stroke="var(--accent)"/>',
  'imp-48-find-smallest-letter-greater-than-target':
    '<path d="M6 38h6v-6h6v-6h6v-6h6v-6h6"/><circle cx="21" cy="29" r="2.3"/><path d="M21 29c4-5 6-6 9-7" stroke="var(--accent)"/><circle cx="30" cy="21" r="3" fill="var(--accent)" stroke="none"/><path d="M27 14l3-3 3 3M30 11v7" stroke="var(--accent)"/>',
  'imp-49-kth-largest-element-in-an-array':
    '<rect x="19" y="14" width="10" height="25" rx="1"/><rect x="6" y="24" width="10" height="15" rx="1"/><rect x="32" y="28" width="10" height="11" rx="1"/><circle cx="24" cy="8" r="4" stroke="var(--accent)"/><path d="M22.5 8h3M24 6.5v3" stroke="var(--accent)"/>',
  'imp-5-swim-in-rising-water':
    '<rect x="8" y="11" width="32" height="27" rx="2"/><path d="M18 11v27M29 11v27M8 24h32" stroke-opacity="0.35"/><path d="M8 31c4-3 8-3 12 0s8 3 12 0 4-2 8-1" stroke="var(--good)"/><circle cx="24" cy="23" r="3.2" fill="var(--accent)" stroke="none"/><path d="M20.5 27c2 1.6 5 1.6 7 0" stroke="var(--accent)"/>',
  'imp-50-find-right-interval':
    '<line x1="6" y1="13" x2="14" y2="13"/><line x1="17" y1="13" x2="25" y2="13"/><line x1="29" y1="13" x2="40" y2="13" stroke="var(--accent)"/><circle cx="22" cy="30" r="8"/><line x1="28" y1="36" x2="40" y2="42"/><path d="M18 30h7M22 26l4 4-4 4" stroke="var(--accent)"/>',
  'imp-51-missing-number-in-arithmetic-progression':
    '<line x1="7" y1="38" x2="43" y2="38"/><line x1="11" y1="38" x2="11" y2="21"/><line x1="19" y1="38" x2="19" y2="21"/><line x1="27" y1="38" x2="27" y2="21" stroke="var(--accent)" stroke-dasharray="2 3"/><line x1="35" y1="38" x2="35" y2="21"/><path d="M24 17l3-4 3 4" stroke="var(--accent)"/>',
  'imp-52-missing-number':
    '<line x1="7" y1="38" x2="41" y2="38"/><circle cx="12" cy="31" r="4"/><circle cx="21" cy="31" r="4"/><circle cx="30" cy="31" r="4" stroke="var(--accent)" stroke-dasharray="2 2"/><circle cx="39" cy="31" r="4"/><path d="M27 25l3-4 3 4" stroke="var(--accent)"/>',
  'imp-53-find-first-and-last-position-of-element-in-sorte':
    '<rect x="9" y="26" width="7" height="8" rx="1"/><rect x="18" y="26" width="7" height="8" rx="1"/><rect x="27" y="26" width="7" height="8" rx="1"/><path d="M12.5 26V13l6 2.5-6 2.5" stroke="var(--accent)"/><path d="M30.5 26V13l6 2.5-6 2.5" stroke="var(--accent)"/>',
  'imp-54-find-peak-element':
    '<path d="M6 40l11-20 7 11 4-6 14 15"/><path d="M17 20V8l6 2.5-6 2.5" stroke="var(--accent)"/><line x1="6" y1="40" x2="42" y2="40"/>',
  'imp-55-leftmost-column-with-at-least-a-one':
    '<rect x="10" y="12" width="28" height="24" rx="1.5"/><line x1="17" y1="12" x2="17" y2="36"/><line x1="10" y1="20" x2="38" y2="20"/><line x1="10" y1="28" x2="38" y2="28"/><rect x="10" y="12" width="7" height="24" fill="var(--accent)" fill-opacity="0.18" stroke="var(--accent)"/><path d="M35 16h-9M29 13l-3 3 3 3" stroke="var(--accent)"/>',
  'imp-56-squares-of-a-sorted-array':
    '<line x1="6" y1="22" x2="42" y2="22"/><path d="M6 22l5-3M6 22l5 3"/><path d="M42 22l-5-3M42 22l-5 3"/><rect x="30" y="30" width="11" height="11" rx="1.5" stroke="var(--accent)"/><rect x="9" y="34" width="6" height="6" rx="1"/>',
  'imp-57-check-if-an-original-string-exists-given-two-enc':
    '<rect x="7" y="11" width="13" height="22" rx="2"/><rect x="28" y="11" width="13" height="22" rx="2"/><line x1="10" y1="17" x2="17" y2="17"/><line x1="10" y1="22" x2="17" y2="22"/><line x1="31" y1="17" x2="38" y2="17"/><line x1="31" y1="22" x2="38" y2="22"/><path d="M21 39c0-2 4-2 4-4.5s-3-3-3-3" stroke="var(--accent)"/><circle cx="21" cy="43" r="0.6" fill="var(--accent)" stroke="var(--accent)"/>',
  'imp-58-climbing-stairs':
    '<path d="M6 40h7v-7h7v-7h7v-7h8"/><circle cx="32" cy="15" r="2.3" fill="var(--accent)" stroke="none"/><path d="M32 17.3v4.5M28.5 19.5 32 21l3.5-1.5M32 21.8 29.5 26M32 21.8 34.5 26" stroke="var(--accent)"/>',
  'imp-59-coin-change':
    '<path d="M10 31c0-6 5-11 13-11s13 5 13 11-5 9-13 9-13-3-13-9z"/><path d="M10 31c-2 .2-4-1-4-3.5S8 24 10 25"/><path d="M33 23c1-1 2-1 3-2M34 28h3"/><circle cx="32" cy="31" r="1.4"/><rect x="18" y="18" width="9" height="2" rx="1"/><circle cx="22" cy="9" r="5" stroke="var(--accent)"/><path d="M22 6v6M20 9h4" stroke="var(--accent)"/>',
  'imp-6-find-shortest-path-with-dijkstra-s':
    '<circle cx="10" cy="35" r="3"/><path d="M13 33 29 16"/><path d="M30 9v9"/><path d="M30 11h8l-2.5 3L38 17h-8z" fill="var(--accent)" stroke="var(--accent)"/><path d="M33 33c0-2-3-2-3 0s3 5 3 5 3-3 3-5-3-2-3 0z"/><circle cx="33" cy="33" r="1"/>',
  'imp-60-coin-change-ii':
    '<circle cx="15" cy="27" r="7"/><circle cx="24" cy="23" r="7"/><circle cx="33" cy="27" r="7" stroke="var(--accent)"/><path d="M30 27l2 2 4-4" stroke="var(--accent)"/><path d="M12 27h4M21 23h4"/>',
  'imp-61-edit-distance':
    '<rect x="7" y="31" width="9" height="9" rx="1"/><rect x="16" y="31" width="9" height="9" rx="1"/><path d="M16 40l9-9" stroke="var(--accent)"/><path d="M31 11l7 7-15 15-8 1 1-8z"/><path d="M29 13l7 7"/><path d="M16 26l-1 8 8-1" stroke="var(--accent)"/>',
  'imp-62-filling-bookcase-shelves':
    '<path d="M7 22h34M7 39h34"/><path d="M11 22V12M16 22l-1-9 3 1 1 8M21 22v-9M25 22l1-9"/><path d="M11 39v-9M15 39v-10M20 39v-8M25 39l-1-11" stroke="var(--accent)"/><path d="M30 39v-9M34 39v-8"/>',
  'imp-63-0-1-knapsack':
    '<path d="M14 19c0-6 4-10 10-10s10 4 10 10"/><path d="M11 19h26c1 0 2 1 2 2v15c0 2-1 4-3 4H12c-2 0-3-2-3-4V21c0-1 1-2 2-2z"/><path d="M18 19v-4c0-3 2-5 6-5s6 2 6 5v4"/><path d="M9 28h30"/><rect x="19" y="32" width="10" height="5" rx="2.5" stroke="var(--accent)"/><circle cx="24" cy="34.5" r="1.3" fill="var(--accent)" stroke="var(--accent)"/>',
  'imp-64-perfect-squares':
    '<rect x="8" y="24" width="15" height="15" rx="1"/><rect x="26" y="30" width="9" height="9" rx="1"/><rect x="36" y="34" width="5" height="5" rx="1" stroke="var(--accent)"/><path d="M8 31h15M15 24v15" stroke="var(--accent)"/>',
  'imp-65-longest-common-subsequence':
    '<circle cx="10" cy="12" r="2.5"/><circle cx="20" cy="12" r="2.5"/><circle cx="30" cy="12" r="2.5"/><circle cx="40" cy="12" r="2.5"/><circle cx="13" cy="36" r="2.5"/><circle cx="23" cy="36" r="2.5"/><circle cx="33" cy="36" r="2.5"/><path d="M11 14l2 20M31 14l2 20" stroke="var(--accent)"/>',
  'imp-66-longest-increasing-subsequence':
    '<path d="M7 41h34"/><rect x="9" y="33" width="5" height="8"/><rect x="17" y="27" width="5" height="14"/><rect x="25" y="19" width="5" height="22"/><rect x="33" y="11" width="5" height="30"/><path d="M11 31l8-6 8-8 8-8" stroke="var(--accent)"/><path d="M31 9h4v4" stroke="var(--accent)"/>',
  'imp-67-longest-palindromic-subsequence':
    '<path d="M24 8v32" stroke="var(--accent)"/><path d="M10 16h8M10 24h6M10 32h8"/><path d="M38 16h-8M38 24h-6M38 32h-8"/><path d="M21 10l3 3 3-3M21 38l3-3 3 3" stroke="var(--accent)"/>',
  'imp-68-longest-string-chain':
    '<rect x="6" y="31" width="7" height="6" rx="1"/><rect x="18" y="28" width="9" height="6" rx="1"/><rect x="31" y="24" width="11" height="6" rx="1"/><path d="M13 34h5"/><path d="M27 31h4" stroke="var(--accent)"/><path d="M29 27c0-3 3-3 3 0v4" stroke="var(--accent)"/>',
  'imp-69-longest-valid-parentheses':
    '<path d="M19 12c-6 4-6 16 0 20" stroke="var(--accent)"/><path d="M29 12c6 4 6 16 0 20" stroke="var(--accent)"/><path d="M13 39h22"/><path d="M13 36v6M35 36v6"/><path d="M19 39v3M24 39v3M29 39v3"/>',
  'imp-7-is-graph-bipartite':
    '<circle cx="14" cy="31" r="6"/><circle cx="34" cy="31" r="6" fill="var(--accent)" stroke="var(--accent)" fill-opacity="0.25"/><path d="M20 31h8"/><path d="M20 13c0-3 5-3 5 0 0 2.5-2.5 2-2.5 4.5" stroke="var(--accent)"/><circle cx="22.5" cy="21" r="0.7" fill="var(--accent)" stroke="var(--accent)"/>',
  'imp-70-maximal-rectangle':
    '<path d="M7 40V28M13 40V19M19 40V14M25 40V22M31 40V17M37 40V25"/><path d="M7 40h32"/><rect x="12" y="20" width="20" height="20" rx="1" stroke="var(--accent)"/>',
  'imp-71-maximal-square':
    '<rect x="8" y="8" width="32" height="32" rx="2"/><path d="M8 19h32M8 30h32M19 8v32M30 8v32"/><rect x="19" y="19" width="21" height="21" fill="var(--accent)" fill-opacity="0.18" stroke="var(--accent)"/><path d="M22 30l3 3 6-6" stroke="var(--accent)"/>',
  'imp-72-maximum-and-sum-of-array':
    '<rect x="8" y="24" width="10" height="15" rx="1.5"/><rect x="22" y="24" width="10" height="15" rx="1.5"/><circle cx="13" cy="30" r="2.5"/><circle cx="13" cy="35" r="2.5"/><circle cx="27" cy="35" r="2.5"/><path d="M41 14c-3 0-4 4-1 6s2 5-1 5" stroke="var(--accent)"/><circle cx="39" cy="18" r="1.4" fill="var(--accent)" stroke="none"/>',
  'imp-73-maximum-number-of-points-with-cost':
    '<circle cx="12" cy="14" r="2"/><circle cx="24" cy="14" r="2"/><circle cx="36" cy="14" r="2"/><circle cx="12" cy="34" r="2"/><circle cx="24" cy="34" r="2"/><circle cx="36" cy="34" r="2"/><path d="M24 16c-8 3-10 9-12 16" stroke="var(--accent)"/><circle cx="36" cy="24" r="4" stroke="var(--accent)"/><path d="M34.3 24h3.4M36 22.3v3.4" stroke="var(--accent)"/>',
  'imp-74-minimum-path-sum':
    '<rect x="8" y="8" width="32" height="32" rx="2"/><path d="M8 19h32M8 30h32M19 8v32M30 8v32"/><path d="M13 13h6v11h11v8" stroke="var(--accent)" stroke-dasharray="2 2.5"/><path d="M34 31v8M34 31l5 1.5-5 1.5" stroke="var(--accent)"/>',
  'imp-75-minimum-deletions-to-make-string-balanced':
    '<path d="M7 33h25"/><circle cx="12" cy="33" r="2.4"/><circle cx="22" cy="33" r="2.4"/><circle cx="32" cy="33" r="2.4" stroke="var(--accent)"/><circle cx="40" cy="16" r="2.5" stroke="var(--accent)"/><circle cx="40" cy="24" r="2.5" stroke="var(--accent)"/><path d="M38 17.5l-6 7M38 22.5l-6-7" stroke="var(--accent)"/>',
  'imp-76-distinct-subsequences':
    '<rect x="29" y="30" width="13" height="9" rx="1.5" stroke="var(--accent)"/><circle cx="9" cy="12" r="2"/><circle cx="19" cy="12" r="2"/><circle cx="29" cy="12" r="2"/><circle cx="39" cy="12" r="2"/><path d="M9 14l24 15M19 14l16 15M29 14l8 15" stroke="var(--accent)" stroke-dasharray="2 2.5"/>',
  'imp-77-unique-paths':
    '<rect x="8" y="8" width="32" height="32" rx="2"/><path d="M8 18.7h32M8 29.3h32M18.7 8v32M29.3 8v32" stroke-width="0.9" opacity="0.45"/><path d="M13 13h11v11h11" stroke="var(--accent)" stroke-dasharray="0.1 3.4"/><circle cx="13" cy="13" r="2.4"/><path d="M33 35v-6"/><polygon points="33,29 33,33 38,31" fill="var(--accent)" stroke="none"/>',
  'imp-78-decode-ways':
    '<rect x="7" y="13" width="19" height="22" rx="2"/><path d="M11 19h11M11 24h8M11 29h11" stroke-width="1.2"/><path d="M27 24h7" stroke="var(--accent)"/><polygon points="34,24 30,21 30,27" fill="var(--accent)" stroke="none"/><path d="M37 31l3.5-12 3.5 12M38 27h5" stroke="var(--accent)"/>',
  'imp-79-partition-array-into-two-arrays-to-minimize-sum-':
    '<path d="M24 9v6"/><path d="M11 16h26"/><circle cx="24" cy="15" r="1.6"/><path d="M13 16l-4 9h8z"/><path d="M35 16l-4 9h8z"/><path d="M9 25a4 4 0 0 0 8 0M31 25a4 4 0 0 0 8 0" stroke="var(--accent)"/><path d="M18 40h12M24 36v4"/>',
  'imp-8-merging-communities':
    '<circle cx="11" cy="16" r="3"/><circle cx="14" cy="26" r="3"/><circle cx="37" cy="16" r="3"/><circle cx="34" cy="26" r="3"/><path d="M19 21h11" stroke="var(--accent)"/><path d="M26 17l5 4-5 4" stroke="var(--accent)"/>',
  'imp-80-race-car':
    '<path d="M13 30h4l3-5h9l4 5h2a2 2 0 0 1 2 2v3H11v-3a2 2 0 0 1 2-2z"/><circle cx="17" cy="35" r="2.4"/><circle cx="33" cy="35" r="2.4"/><path d="M5 24h7M5 29h5" stroke="var(--accent)"/><path d="M41 13v18"/><rect x="41" y="14" width="5" height="5" fill="var(--accent)" fill-opacity="0.3" stroke="var(--accent)"/>',
  'imp-81-range-sum-query-2d-immutable':
    '<rect x="8" y="8" width="26" height="26" rx="2"/><path d="M8 16.6h26M8 25.3h26M16.6 8v26M25.3 8v26" stroke-width="0.9" opacity="0.45"/><rect x="16.6" y="16.6" width="8.7" height="8.7" fill="var(--accent)" fill-opacity="0.25" stroke="var(--accent)"/><circle cx="33" cy="33" r="6" stroke="var(--accent)"/><path d="M37.5 37.5 43 43" stroke="var(--accent)"/>',
  'imp-82-regular-expression-matching':
    '<rect x="6" y="14" width="19" height="20" rx="2"/><path d="M15.5 19v9M11.5 21l8 5M19.5 21l-8 5" stroke="var(--accent)"/><circle cx="30" cy="31" r="1.6" fill="var(--accent)" stroke="none"/><path d="M28 19h14" stroke-dasharray="0.1 3.2"/><path d="M34 30h8M34 34h6"/>',
  'imp-83-sentence-screen-fitting':
    '<rect x="7" y="10" width="34" height="22" rx="2"/><path d="M19 32v4M29 32v4M16 36h16"/><path d="M11 16h14M11 21h18M11 26h8"/><path d="M22 26h8" stroke="var(--accent)"/><path d="M31 22a3.5 3.5 0 1 1-3 5.5" stroke="var(--accent)"/><path d="M28 24.5l-1 3 3 0.4" stroke="var(--accent)"/>',
  'imp-84-student-attendance-record-ii':
    '<rect x="11" y="7" width="26" height="34" rx="2"/><path d="M16 7v-1a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v1"/><path d="M15 15l2 2 4-4" stroke="var(--good)"/><path d="M25 15h7"/><path d="M16 23l4 4M20 23l-4 4" stroke="var(--bad)"/><path d="M25 25h7"/><path d="M17 33v4M20 33v4M23 33v4" stroke="var(--accent)"/><path d="M27 35h5"/>',
  'imp-85-valid-palindrome-iii':
    '<path d="M24 9v30" stroke="var(--accent)" stroke-dasharray="2 2.5"/><path d="M14 17h6M14 24h6M14 31h5"/><path d="M34 17h-6M34 24h-6M34 31h-5"/><circle cx="9" cy="12" r="2.3"/><circle cx="9" cy="17" r="2.3"/><path d="M11 13.3 21 22M11 15.7 21 17" stroke="var(--accent)"/>',
  'imp-9-similar-string-groups':
    '<rect x="7" y="12" width="34" height="9" rx="2"/><rect x="7" y="28" width="34" height="9" rx="2"/><path d="M12 16.5h4M22 16.5h11M12 32.5h11M30 32.5h4" stroke-opacity="0.5"/><circle cx="19" cy="16.5" r="1.5" fill="var(--accent)" stroke="var(--accent)"/><circle cx="27" cy="32.5" r="1.5" fill="var(--accent)" stroke="var(--accent)"/><path d="M19 19c6 2 2 9 8 11" stroke="var(--accent)"/>',
  'insertion-sort':
    '<rect x="7" y="22" width="7" height="14" rx="1"/><rect x="15" y="22" width="7" height="14" rx="1"/><rect x="27" y="22" width="7" height="14" rx="1"/><rect x="34" y="9" width="7" height="14" rx="1" stroke="var(--accent)"/><path d="M37.5 25v9" stroke="var(--accent)"/><path d="M34.5 31l3 3 3-3" stroke="var(--accent)"/>',
  'interval-scheduling':
    '<path d="M8 14h13M8 24h17M8 34h11"/><path d="M28 12l3 3 6-7" stroke="var(--accent)"/><path d="M28 24l3 3 6-7" stroke="var(--accent)"/>',
  'linked-list-cycle':
    '<path d="M11 31c0-7 26-7 26 0s-26 7-26 0" stroke-dasharray="1 3"/><ellipse cx="15" cy="31" rx="4" ry="3"/><path d="M11 33l-2 1.5M19 32l1.5 2"/><circle cx="33" cy="22" r="2.5" fill="var(--accent)" stroke="none"/><path d="M33.5 24.5c3.5 2 3.5 6 0 6.5M31 20l-1.5-3M35 20l1.5-3" stroke="var(--accent)"/>',
  'longest-substring':
    '<rect x="6" y="22" width="7" height="9" rx="1"/><rect x="14" y="22" width="7" height="9" rx="1"/><rect x="22" y="22" width="7" height="9" rx="1"/><rect x="30" y="22" width="7" height="9" rx="1"/><path d="M14 17h25M14 14v6M39 14v6" stroke="var(--accent)"/><path d="M31 34l2.5 3 4-6" stroke="var(--bad)"/>',
  'max-subarray-sum-k':
    '<path d="M8 34V26M14 34V20M20 34V24M26 34V18M32 34V28M38 34V22"/><rect x="17" y="13" width="19" height="25" rx="2" stroke="var(--accent)"/><path d="M39 9v6M36 12h6" stroke="var(--accent)"/><path d="M11 12h6"/>',
  'merge-sort':
    '<path d="M9 10v8M17 10v8M31 10v8M39 10v8"/><path d="M9 18l8 8M17 18l7 7M39 18l-8 8M31 18l-7 7"/><path d="M24 25v9" stroke="var(--accent)"/><path d="M18 34h12l-6 6z" stroke="var(--accent)"/>',
  'n-queens':
    '<rect x="6" y="31" width="36" height="8" rx="1"/><path d="M6 35h36M15 31v8M24 31v8M33 31v8" stroke-width="1" opacity="0.45"/><path d="M19 31c-2-3-1-6 1-7-1 4 4 4 4 0 0 4 5 4 4 0 2 1 3 4 1 7z"/><path d="M19 31h10"/><circle cx="21" cy="21" r="0.9" fill="var(--accent)" stroke="none"/><circle cx="24" cy="20" r="0.9" fill="var(--accent)" stroke="none"/><circle cx="27" cy="21" r="0.9" fill="var(--accent)" stroke="none"/><path d="M15 27 8 20M33 27l7-7" stroke="var(--accent)" opacity="0.75"/>',
  'quick-sort':
    '<path d="M24 7v27" stroke="var(--accent)"/><path d="M24 7l-3 5h6z" fill="var(--accent)" stroke="var(--accent)"/><path d="M8 40h32"/><circle cx="13" cy="23" r="2"/><circle cx="18" cy="28" r="1.5"/><circle cx="31" cy="21" r="2.6"/><circle cx="37" cy="27" r="3.2"/>',
  'reverse-linked-list':
    '<rect x="7" y="27" width="8" height="8" rx="1.5"/><rect x="20" y="27" width="8" height="8" rx="1.5"/><rect x="33" y="27" width="8" height="8" rx="1.5"/><path d="M11 27c0-11 26-11 26 0" stroke="var(--accent)"/><path d="M11 27l-2.5-3M11 27l3.5-2" stroke="var(--accent)"/>',
  'selection-sort':
    '<path d="M8 38V30M14 38V34M20 38V22M26 38V32M32 38V28M38 38V25"/><circle cx="20" cy="15" r="6" stroke="var(--accent)"/><path d="M24.5 19.5l5 5" stroke="var(--accent)"/><path d="M20 22v-2" stroke="var(--accent)"/>',
  'tree-traversals':
    '<circle cx="24" cy="9" r="3"/><circle cx="14" cy="23" r="3"/><circle cx="34" cy="23" r="3"/><path d="M21.7 11 16.3 21M26.3 11 31.7 21"/><path d="M10 40c5 0 5-9 10-9s5 9 10 9" stroke="var(--accent)" stroke-dasharray="1 3"/>',
  trie: '<path d="M24 42V25"/><path d="M24 25 14 15M24 25l10-10M24 30 18 23M24 30l6-7"/><circle cx="14" cy="15" r="2"/><circle cx="34" cy="15" r="2" fill="var(--accent)" stroke="none"/><circle cx="18" cy="23" r="2"/><circle cx="30" cy="23" r="2"/>',
  'two-sum-sorted':
    '<path d="M6 24h36"/><path d="M12 19v10M20 21v6M28 21v6M36 19v10"/><path d="M9 14l4 4-4 4" stroke="var(--accent)"/><path d="M39 14l-4 4 4 4" stroke="var(--accent)"/><circle cx="24" cy="24" r="3" fill="var(--accent)" stroke="none"/>',
  'union-find':
    '<circle cx="12" cy="14" r="3"/><circle cx="9" cy="24" r="3"/><circle cx="17" cy="25" r="3"/><path d="M12 17l-2 4M13 16l3 6"/><circle cx="36" cy="14" r="3"/><circle cx="39" cy="24" r="3"/><path d="M36 17l2 5"/><path d="M19 23 33 16" stroke="var(--accent)"/><path d="M11 31l16 5m0-5-16 5" stroke="var(--bad)" opacity="0.8"/>',
};
