// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: canvases.sql

package arcadedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCanvas = `-- name: CreateCanvas :one
insert into public.canvases (owner_profile_id, title, doc, room_code)
values (
  $1::uuid,
  $2,
  $3::jsonb,
  $4
)
returning id::text, updated_at
`

type CreateCanvasParams struct {
	OwnerProfileID pgtype.UUID `json:"owner_profile_id"`
	Title          string      `json:"title"`
	Doc            []byte      `json:"doc"`
	RoomCode       pgtype.Text `json:"room_code"`
}

type CreateCanvasRow struct {
	ID        string             `json:"id"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateCanvas(ctx context.Context, arg CreateCanvasParams) (CreateCanvasRow, error) {
	row := q.db.QueryRow(ctx, createCanvas,
		arg.OwnerProfileID,
		arg.Title,
		arg.Doc,
		arg.RoomCode,
	)
	var i CreateCanvasRow
	err := row.Scan(&i.ID, &i.UpdatedAt)
	return i, err
}

const deleteCanvas = `-- name: DeleteCanvas :execrows
delete from public.canvases
where id = $1::uuid and owner_profile_id = $2::uuid
`

type DeleteCanvasParams struct {
	ID             pgtype.UUID `json:"id"`
	OwnerProfileID pgtype.UUID `json:"owner_profile_id"`
}

func (q *Queries) DeleteCanvas(ctx context.Context, arg DeleteCanvasParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCanvas, arg.ID, arg.OwnerProfileID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCanvas = `-- name: GetCanvas :one
select
  id::text,
  owner_profile_id,
  room_code,
  title,
  doc,
  updated_at
from public.canvases
where id = $1::uuid
`

type GetCanvasRow struct {
	ID             string             `json:"id"`
	OwnerProfileID pgtype.UUID        `json:"owner_profile_id"`
	RoomCode       pgtype.Text        `json:"room_code"`
	Title          string             `json:"title"`
	Doc            []byte             `json:"doc"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetCanvas(ctx context.Context, id pgtype.UUID) (GetCanvasRow, error) {
	row := q.db.QueryRow(ctx, getCanvas, id)
	var i GetCanvasRow
	err := row.Scan(
		&i.ID,
		&i.OwnerProfileID,
		&i.RoomCode,
		&i.Title,
		&i.Doc,
		&i.UpdatedAt,
	)
	return i, err
}

const listCanvases = `-- name: ListCanvases :many
select id::text, title, room_code, updated_at
from public.canvases
where owner_profile_id = $1::uuid
order by updated_at desc
limit 100
`

type ListCanvasesRow struct {
	ID        string             `json:"id"`
	Title     string             `json:"title"`
	RoomCode  pgtype.Text        `json:"room_code"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListCanvases(ctx context.Context, ownerProfileID pgtype.UUID) ([]ListCanvasesRow, error) {
	rows, err := q.db.Query(ctx, listCanvases, ownerProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCanvasesRow{}
	for rows.Next() {
		var i ListCanvasesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.RoomCode,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCanvas = `-- name: UpdateCanvas :one
update public.canvases
set doc = $1::jsonb,
    title = coalesce($2, title),
    room_code = coalesce($3, room_code),
    updated_at = now()
where id = $4::uuid and owner_profile_id = $5::uuid
returning updated_at
`

type UpdateCanvasParams struct {
	Doc            []byte      `json:"doc"`
	Title          pgtype.Text `json:"title"`
	RoomCode       pgtype.Text `json:"room_code"`
	ID             pgtype.UUID `json:"id"`
	OwnerProfileID pgtype.UUID `json:"owner_profile_id"`
}

func (q *Queries) UpdateCanvas(ctx context.Context, arg UpdateCanvasParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, updateCanvas,
		arg.Doc,
		arg.Title,
		arg.RoomCode,
		arg.ID,
		arg.OwnerProfileID,
	)
	var updated_at pgtype.Timestamptz
	err := row.Scan(&updated_at)
	return updated_at, err
}
