// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: daily.sql

package arcadedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOrCreateDailyChallenge = `-- name: GetOrCreateDailyChallenge :one
select challenge_date, game_id, seed, config, created_at
from public.get_or_create_daily_challenge($1::date)
`

func (q *Queries) GetOrCreateDailyChallenge(ctx context.Context, challengeDate pgtype.Date) (DailyChallenge, error) {
	row := q.db.QueryRow(ctx, getOrCreateDailyChallenge, challengeDate)
	var i DailyChallenge
	err := row.Scan(
		&i.ChallengeDate,
		&i.GameID,
		&i.Seed,
		&i.Config,
		&i.CreatedAt,
	)
	return i, err
}

const submitDailyScore = `-- name: SubmitDailyScore :exec
select public.submit_daily_score($1::uuid, $2::date, $3)
`

type SubmitDailyScoreParams struct {
	ProfileID     pgtype.UUID `json:"profile_id"`
	ChallengeDate pgtype.Date `json:"challenge_date"`
	Score         int32       `json:"score"`
}

func (q *Queries) SubmitDailyScore(ctx context.Context, arg SubmitDailyScoreParams) error {
	_, err := q.db.Exec(ctx, submitDailyScore, arg.ProfileID, arg.ChallengeDate, arg.Score)
	return err
}
