// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package arcadedb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Achievement struct {
	ID          string `json:"id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Icon        string `json:"icon"`
	Points      int32  `json:"points"`
	SortOrder   int32  `json:"sort_order"`
}

// Saved collaborative canvas snapshot (opaque ProjectState doc).
type Canvase struct {
	ID             pgtype.UUID        `json:"id"`
	OwnerProfileID pgtype.UUID        `json:"owner_profile_id"`
	RoomCode       pgtype.Text        `json:"room_code"`
	Title          string             `json:"title"`
	Doc            []byte             `json:"doc"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

// Learning courses mirrored from the frontend catalog.
type Course struct {
	ID      string      `json:"id"`
	Title   string      `json:"title"`
	Summary pgtype.Text `json:"summary"`
	Icon    pgtype.Text `json:"icon"`
	// Plugin group: curated | imported | prep | go-course | openrtb
	Group     string             `json:"group"`
	Family    string             `json:"family"`
	SortOrder int32              `json:"sort_order"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type DailyChallenge struct {
	ChallengeDate pgtype.Date        `json:"challenge_date"`
	GameID        string             `json:"game_id"`
	Seed          string             `json:"seed"`
	Config        []byte             `json:"config"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type DailyChallengeScore struct {
	ChallengeDate pgtype.Date        `json:"challenge_date"`
	ProfileID     pgtype.UUID        `json:"profile_id"`
	Score         int32              `json:"score"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Friend struct {
	ProfileID       pgtype.UUID        `json:"profile_id"`
	FriendProfileID pgtype.UUID        `json:"friend_profile_id"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Game struct {
	ID        string             `json:"id"`
	Title     string             `json:"title"`
	SortOrder int32              `json:"sort_order"`
	Active    bool               `json:"active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type GameStat struct {
	ProfileID     pgtype.UUID        `json:"profile_id"`
	GameID        string             `json:"game_id"`
	Mmr           int32              `json:"mmr"`
	Wins          int32              `json:"wins"`
	Losses        int32              `json:"losses"`
	Draws         int32              `json:"draws"`
	Streak        int32              `json:"streak"`
	BestStreak    int32              `json:"best_streak"`
	MatchesPlayed int32              `json:"matches_played"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

// Durable interview whiteboard session (opaque canvas/questions/rubric JSON) with a guest link; real-time sync via room_code relay.
type InterviewSession struct {
	ID               pgtype.UUID        `json:"id"`
	OwnerProfileID   pgtype.UUID        `json:"owner_profile_id"`
	RoomCode         pgtype.Text        `json:"room_code"`
	Title            string             `json:"title"`
	Status           string             `json:"status"`
	GuestToken       string             `json:"guest_token"`
	GuestLinkEnabled bool               `json:"guest_link_enabled"`
	CanvasLocked     bool               `json:"canvas_locked"`
	Canvas           []byte             `json:"canvas"`
	Questions        []byte             `json:"questions"`
	Notes            string             `json:"notes"`
	Rubric           []byte             `json:"rubric"`
	Recommendation   string             `json:"recommendation"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	EndedAt          pgtype.Timestamptz `json:"ended_at"`
}

type Item struct {
	ID               string      `json:"id"`
	CourseID         string      `json:"course_id"`
	TopicID          pgtype.Text `json:"topic_id"`
	ProblemID        pgtype.Text `json:"problem_id"`
	Kind             string      `json:"kind"`
	Title            pgtype.Text `json:"title"`
	Summary          pgtype.Text `json:"summary"`
	Difficulty       pgtype.Text `json:"difficulty"`
	EstimatedMinutes pgtype.Int4 `json:"estimated_minutes"`
	Prereqs          []string    `json:"prereqs"`
	SortOrder        int32       `json:"sort_order"`
}

type Match struct {
	ID              pgtype.UUID        `json:"id"`
	GameID          string             `json:"game_id"`
	RoomCode        pgtype.Text        `json:"room_code"`
	Mode            string             `json:"mode"`
	WinnerProfileID pgtype.UUID        `json:"winner_profile_id"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	EndedAt         pgtype.Timestamptz `json:"ended_at"`
	Metadata        []byte             `json:"metadata"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type MatchParticipant struct {
	ID          pgtype.UUID        `json:"id"`
	MatchID     pgtype.UUID        `json:"match_id"`
	ProfileID   pgtype.UUID        `json:"profile_id"`
	DisplayName string             `json:"display_name"`
	Placement   int32              `json:"placement"`
	Score       int32              `json:"score"`
	MmrBefore   pgtype.Int4        `json:"mmr_before"`
	MmrAfter    pgtype.Int4        `json:"mmr_after"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

// Named interview prep plan owned by one profile; ordered item list stored in prep_plan_items.
type PrepPlan struct {
	ID             pgtype.UUID        `json:"id"`
	OwnerProfileID pgtype.UUID        `json:"owner_profile_id"`
	Title          string             `json:"title"`
	Notes          string             `json:"notes"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

// Ordered problem items within a prep plan; item_id is an opaque frontend catalog id.
type PrepPlanItem struct {
	PlanID    pgtype.UUID `json:"plan_id"`
	ItemID    string      `json:"item_id"`
	Position  int32       `json:"position"`
	Completed bool        `json:"completed"`
}

type Problem struct {
	ID              string             `json:"id"`
	Title           string             `json:"title"`
	Difficulty      string             `json:"difficulty"`
	Summary         pgtype.Text        `json:"summary"`
	Pattern         pgtype.Text        `json:"pattern"`
	Visual          pgtype.Text        `json:"visual"`
	TimeComplexity  pgtype.Text        `json:"time_complexity"`
	SpaceComplexity pgtype.Text        `json:"space_complexity"`
	SourceUrl       pgtype.Text        `json:"source_url"`
	RegionID        pgtype.Text        `json:"region_id"`
	Narrative       pgtype.Text        `json:"narrative"`
	Extra           []byte             `json:"extra"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type ProblemTag struct {
	ProblemID string `json:"problem_id"`
	TagID     string `json:"tag_id"`
}

// Player profile (guest or upgraded).
type Profile struct {
	ID           pgtype.UUID        `json:"id"`
	SessionToken pgtype.Text        `json:"session_token"`
	DisplayName  string             `json:"display_name"`
	AvatarSeed   string             `json:"avatar_seed"`
	IsAnonymous  bool               `json:"is_anonymous"`
	Xp           int32              `json:"xp"`
	Level        pgtype.Int4        `json:"level"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	// Stable room code for this profile; friends can always join via this code.
	PersonalRoomCode pgtype.Text `json:"personal_room_code"`
	// Unique login email; null for guest-only profiles.
	Email pgtype.Text `json:"email"`
	// bcrypt hash; null for guest-only profiles.
	PasswordHash pgtype.Text `json:"password_hash"`
	// Platform admin; set via PLATFORM_ADMIN_EMAIL on server start.
	IsAdmin bool `json:"is_admin"`
}

type ProfileAchievement struct {
	ProfileID     pgtype.UUID        `json:"profile_id"`
	AchievementID string             `json:"achievement_id"`
	UnlockedAt    pgtype.Timestamptz `json:"unlocked_at"`
}

type QuizChoice struct {
	ID         string `json:"id"`
	QuestionID string `json:"question_id"`
	Label      string `json:"label"`
	IsCorrect  bool   `json:"is_correct"`
	SortOrder  int32  `json:"sort_order"`
}

type QuizQuestion struct {
	ID        string      `json:"id"`
	ProblemID pgtype.Text `json:"problem_id"`
	Prompt    string      `json:"prompt"`
	Explain   pgtype.Text `json:"explain"`
	SortOrder int32       `json:"sort_order"`
}

type Room struct {
	Code          string             `json:"code"`
	HostProfileID pgtype.UUID        `json:"host_profile_id"`
	Title         pgtype.Text        `json:"title"`
	GameID        pgtype.Text        `json:"game_id"`
	Mode          string             `json:"mode"`
	Capacity      int32              `json:"capacity"`
	IsPublic      bool               `json:"is_public"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	LastActiveAt  pgtype.Timestamptz `json:"last_active_at"`
}

type Session struct {
	Token  string             `json:"token"`
	Data   []byte             `json:"data"`
	Expiry pgtype.Timestamptz `json:"expiry"`
}

type Solution struct {
	ID        pgtype.UUID `json:"id"`
	ProblemID string      `json:"problem_id"`
	Language  string      `json:"language"`
	File      string      `json:"file"`
	Code      string      `json:"code"`
	IsPrimary bool        `json:"is_primary"`
	SortOrder int32       `json:"sort_order"`
}

type StoryRegion struct {
	ID        string      `json:"id"`
	CourseID  string      `json:"course_id"`
	CodeName  pgtype.Text `json:"code_name"`
	Title     string      `json:"title"`
	Subtitle  pgtype.Text `json:"subtitle"`
	Blurb     pgtype.Text `json:"blurb"`
	SortOrder int32       `json:"sort_order"`
}

type Tag struct {
	ID    string      `json:"id"`
	Label pgtype.Text `json:"label"`
	Color pgtype.Text `json:"color"`
}

type Topic struct {
	ID        string      `json:"id"`
	CourseID  string      `json:"course_id"`
	Title     string      `json:"title"`
	Summary   pgtype.Text `json:"summary"`
	SortOrder int32       `json:"sort_order"`
}
