export const authStrings = {
  signIn: 'Sign in',
  logIn: 'Log in',
  signUp: 'Sign up',
  welcomeBack: 'Welcome back',
  createAccount: 'Create account',
  displayName: 'Display name',
  email: 'Email',
  password: 'Password',
  createAccountCta: 'Create account',
  noAccount: "Don't have an account?",
  hasAccount: 'Already have an account?',
  profileStats: 'Profile & stats',
  signOut: 'Sign out',
  admin: 'Admin',
  stats: 'Stats',
  namePlaceholder: 'Ahmed',
  emailPlaceholder: 'you@example.com',
  passwordLoginPlaceholder: 'Your password',
  passwordSignupPlaceholder: 'At least 8 characters',
} as const;
