export const authStrings = {
  signIn: 'Sign in',
  logIn: 'Log in',
  signUp: 'Sign up',
  welcomeBack: 'Welcome back',
  createAccount: 'Create account',
  loginSubtitle: 'Pick up where you left off — stats, streaks, and rooms sync to your account.',
  signupSubtitle: 'Free account. Keep progress across devices and play with friends.',
  displayName: 'Display name',
  email: 'Email',
  password: 'Password',
  createAccountCta: 'Create account',
  noAccount: "Don't have an account?",
  hasAccount: 'Already have an account?',
  profileStats: 'Profile & stats',
  profile: 'Profile',
  signOut: 'Sign out',
  admin: 'Admin',
  stats: 'Stats',
  namePlaceholder: 'Ahmed',
  emailPlaceholder: 'you@example.com',
  passwordLoginPlaceholder: 'Your password',
  passwordSignupPlaceholder: 'At least 8 characters',
  showPassword: 'Show password',
  hidePassword: 'Hide password',
  signingIn: 'Signing in…',
  creatingAccount: 'Creating account…',
  passwordStrength: {
    weak: 'Weak — add length and mixed characters',
    fair: 'Fair — add numbers or symbols',
    strong: 'Strong password',
  },
  invalidEmail: 'Enter a valid email address.',
  close: 'Close',
} as const;
