/**
 * Shared prep problem record shape — kept separate from prepFactory so manifest,
 * quiz, and scene modules can import types without circular deps.
 */
export interface PrepProblem {
  id: string;
  topic: string;
  topicTitle: string;
  course: string;
  courseIcon: string;
  slug: string;
  number: string;
  title: string;
  /** One-line problem ask — generated by import-prep.mjs. */
  ask?: string;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  tags: string[];
  pattern: string;
  visual: string;
  memorize: string;
  scene: string;
  acquired: string;
  time: string;
  space: string;
  code: string;
  notes: string;
  approaches: string;
  variants: { file: string; text: string }[];
}
