import type { ComponentType } from 'react';
import { definePlugin, type InspectorProps, type ProblemPlugin } from '../../core/types';
import { wireTeachingStack, codePiecesFromSource } from '../_shared/pluginKit';
import { withInspectorNotes } from '../_shared/withInspectorNotes';
import { prepCodePieces } from './prepCodePieces';
import { recordScene, SceneView, SceneInspector, sceneVerdict } from './prepScene';
import { resolvePrepSimulator } from './prepSimulators';
import { defaultPrepQuiz } from './prepQuiz';
import { PROBLEM_PORTS } from './languagePorts';

/**
 * One record in the generated prep manifest (see scripts/import-prep.mjs). These
 * are the 16 "non-big4" topics of the prep study collection — imported with the
 * cinematic `scene`, `visual` (how it runs) and `memorize` line, plus the real Go
 * `solution.go`. Each renders as the animated Scene unless a hand-built simulator
 * exists for its id.
 */
export interface PrepProblem {
  id: string;
  topic: string;
  topicTitle: string;
  course: string;
  courseIcon: string;
  slug: string;
  number: string;
  title: string;
  /** One-line problem ask — generated by import-prep.mjs. */
  ask?: string;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  tags: string[];
  pattern: string;
  visual: string;
  memorize: string;
  scene: string;
  acquired: string;
  time: string;
  space: string;
  code: string;
  notes: string;
  approaches: string;
  variants: { file: string; text: string }[];
}

/** Append the prep NOTES.md / Approaches under a simulator's own inspector. */
function withNotes(
  Inspector: ComponentType<InspectorProps<any>>,
  p: PrepProblem,
): ComponentType<InspectorProps<any>> {
  return withInspectorNotes(Inspector, [
    ...(p.notes ? [{ title: 'Notes (NOTES.md)', body: p.notes }] : []),
    ...(p.approaches ? [{ title: 'Approaches', body: p.approaches }] : []),
  ]);
}

export function makePrepPlugin(p: PrepProblem): ProblemPlugin<any, any> {
  const meta = {
    id: p.id,
    title: p.title,
    number: p.number,
    difficulty: p.difficulty,
    tags: p.tags,
    summary: p.pattern || p.visual || `${p.topicTitle} problem.`,
  };
  const code = { text: p.code, lang: 'go', file: 'solution.go' };
  const extraCode = p.variants.map((v) => ({ text: v.text, lang: 'go', file: `variants/${v.file}` }));
  const ports = PROBLEM_PORTS[p.id];
  if (ports?.python) extraCode.push({ text: ports.python, lang: 'python', file: 'solution.py' });
  if (ports?.java) extraCode.push({ text: ports.java, lang: 'java', file: 'Solution.java' });
  const codePieces = codePiecesFromSource(p.code) ?? prepCodePieces(p.code) ?? undefined;
  const fallbackQuiz = defaultPrepQuiz(p);

  const sim = resolvePrepSimulator(p.id);

  if (sim) {
    const verdict = sim.verdict ?? (() => ({ ok: true, label: p.difficulty.toLowerCase() }));
    const teaching = sim.practice
      ? wireTeachingStack({
          record: sim.record,
          View: sim.View,
          inputs: sim.inputs,
          verdict,
          practice: sim.practice,
        })
      : null;
    return definePlugin<any, any>({
      meta,
      inputs: sim.inputs,
      record: sim.record,
      View: sim.View,
      Inspector: withNotes(sim.Inspector ?? SceneInspector, p),
      verdict,
      code,
      extraCode,
      quiz: sim.practice?.quiz ?? fallbackQuiz,
      codePieces: sim.practice?.codePieces ?? codePieces,
      tabs: teaching?.tabs,
      wires: teaching?.wires,
    });
  }

  return definePlugin<PrepProblem, any>({
    meta,
    inputs: [{ id: 'scene', label: 'Scene', value: p }],
    record: recordScene,
    View: SceneView,
    Inspector: withNotes(SceneInspector, p),
    verdict: sceneVerdict,
    code,
    extraCode,
    quiz: fallbackQuiz,
    codePieces,
  });
}
