import React from 'react';
import ReactDOM from 'react-dom/client';
import '@/shell/panels/registerPanelNode';
import { markDraftSoftReloadExpected } from '@/store/persistence/draftPersistence';
import App from './App';
import '@xyflow/react/dist/style.css';
import './index.css';
import './styles/theme.css';
import './styles/themes/index.css';
import './styles/theme-cb-layer.css';
import './styles/learn-studio.css';
import './styles/reassemble-puzzle.css';
import './styles/mobile.css';
import './styles/assemble-games.css';
import './styles/assemble/snap-call.css';
import './styles/assemble/imposter.css';
import './styles/assemble/one-stroke.css';

// Register the Workbox service worker generated by vite-plugin-pwa.
// Only active in production builds to avoid stale-cache issues in dev.
if (import.meta.env.PROD) {
  import('virtual:pwa-register').then(({ registerSW }) => {
    registerSW({ immediate: true });
  });
}

if (typeof window !== 'undefined') {
  window.addEventListener('beforeunload', () => {
    markDraftSoftReloadExpected();
  });
}

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
);
