import React from 'react';
import ReactDOM from 'react-dom/client';
import '@/shell/panels/registerPanelNode';
import { markDraftSoftReloadExpected } from '@/store/persistence/draftPersistence';
import App from './App';
import '@xyflow/react/dist/style.css';
import './index.css';
import './styles/theme.css';
import './styles/themes/index.css';
import './styles/theme-cb-layer.css';
import './styles/learn-studio.css';
import './styles/reassemble-puzzle.css';
import './styles/mobile.css';
import './styles/assemble-games.css';
import './styles/assemble/snap-call.css';
import './styles/assemble/imposter.css';
import './styles/assemble/one-stroke.css';

// Register the Workbox service worker generated by vite-plugin-pwa.
// Only active in production builds to avoid stale-cache issues in dev.
if (import.meta.env.PROD) {
  import('virtual:pwa-register')
    .then(({ registerSW }) => {
      registerSW({ immediate: true });
    })
    .catch((error: unknown) => {
      console.error('Unable to register Algo Moves service worker.', error);
    });
}

if (typeof window !== 'undefined') {
  window.addEventListener('beforeunload', () => {
    markDraftSoftReloadExpected();
  });
}

type BootErrorBoundaryState = {
  error: Error | null;
};

class BootErrorBoundary extends React.Component<React.PropsWithChildren, BootErrorBoundaryState> {
  override state: BootErrorBoundaryState = { error: null };

  static getDerivedStateFromError(error: Error): BootErrorBoundaryState {
    return { error };
  }

  override componentDidCatch(error: Error) {
    console.error('Algo Moves render failed.', error);
  }

  override render() {
    if (this.state.error) {
      return (
        <main className="boot-shell" aria-label="Algo Moves could not start">
          <section className="boot-card">
            <span className="boot-mark" aria-hidden="true">
              AM
            </span>
            <h1>Algo Moves needs a reload</h1>
            <p>The workspace hit a startup error. Refresh the page to restore the session.</p>
          </section>
        </main>
      );
    }

    return this.props.children;
  }
}

const rootElement = document.getElementById('root');

if (!rootElement) {
  throw new Error('Algo Moves could not find the #root element.');
}

ReactDOM.createRoot(rootElement).render(
  <React.StrictMode>
    <BootErrorBoundary>
      <App />
    </BootErrorBoundary>
  </React.StrictMode>,
);
