// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: content.sql

package arcadedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const contentCourses = `-- name: ContentCourses :many
select
  c.id,
  c.title,
  coalesce(c.summary, '') as summary,
  coalesce(c.icon, '') as icon,
  c."group",
  c.family,
  (select count(*)::int from public.items i where i.course_id = c.id and i.kind = 'problem') as problem_count
from public.courses c
order by c.sort_order, c.id
`

type ContentCoursesRow struct {
	ID           string `json:"id"`
	Title        string `json:"title"`
	Summary      string `json:"summary"`
	Icon         string `json:"icon"`
	Group        string `json:"group"`
	Family       string `json:"family"`
	ProblemCount int32  `json:"problem_count"`
}

func (q *Queries) ContentCourses(ctx context.Context) ([]ContentCoursesRow, error) {
	rows, err := q.db.Query(ctx, contentCourses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContentCoursesRow{}
	for rows.Next() {
		var i ContentCoursesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Icon,
			&i.Group,
			&i.Family,
			&i.ProblemCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const contentItems = `-- name: ContentItems :many
select id, topic_id, kind, problem_id, coalesce(title, '') as title, difficulty
from public.items
order by topic_id, sort_order, id
`

type ContentItemsRow struct {
	ID         string      `json:"id"`
	TopicID    pgtype.Text `json:"topic_id"`
	Kind       string      `json:"kind"`
	ProblemID  pgtype.Text `json:"problem_id"`
	Title      string      `json:"title"`
	Difficulty pgtype.Text `json:"difficulty"`
}

func (q *Queries) ContentItems(ctx context.Context) ([]ContentItemsRow, error) {
	rows, err := q.db.Query(ctx, contentItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContentItemsRow{}
	for rows.Next() {
		var i ContentItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.TopicID,
			&i.Kind,
			&i.ProblemID,
			&i.Title,
			&i.Difficulty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const contentProblemByID = `-- name: ContentProblemByID :one
select
  p.id,
  p.title,
  p.difficulty,
  coalesce(p.summary, '') as summary,
  coalesce(p.pattern, '') as pattern,
  coalesce(p.source_url, '') as source_url,
  coalesce(p.narrative, '') as narrative,
  coalesce(p.region_id, '') as region_id,
  coalesce(r.title, '') as region_title
from public.problems p
left join public.story_regions r on r.id = p.region_id
where p.id = $1
`

type ContentProblemByIDRow struct {
	ID          string `json:"id"`
	Title       string `json:"title"`
	Difficulty  string `json:"difficulty"`
	Summary     string `json:"summary"`
	Pattern     string `json:"pattern"`
	SourceUrl   string `json:"source_url"`
	Narrative   string `json:"narrative"`
	RegionID    string `json:"region_id"`
	RegionTitle string `json:"region_title"`
}

func (q *Queries) ContentProblemByID(ctx context.Context, id string) (ContentProblemByIDRow, error) {
	row := q.db.QueryRow(ctx, contentProblemByID, id)
	var i ContentProblemByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Difficulty,
		&i.Summary,
		&i.Pattern,
		&i.SourceUrl,
		&i.Narrative,
		&i.RegionID,
		&i.RegionTitle,
	)
	return i, err
}

const contentProblemQuizChoices = `-- name: ContentProblemQuizChoices :many
select ch.question_id, ch.label, ch.is_correct
from public.quiz_choices ch
join public.quiz_questions q on q.id = ch.question_id
where q.problem_id = $1
order by ch.question_id, ch.sort_order
`

type ContentProblemQuizChoicesRow struct {
	QuestionID string `json:"question_id"`
	Label      string `json:"label"`
	IsCorrect  bool   `json:"is_correct"`
}

func (q *Queries) ContentProblemQuizChoices(ctx context.Context, problemID pgtype.Text) ([]ContentProblemQuizChoicesRow, error) {
	rows, err := q.db.Query(ctx, contentProblemQuizChoices, problemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContentProblemQuizChoicesRow{}
	for rows.Next() {
		var i ContentProblemQuizChoicesRow
		if err := rows.Scan(&i.QuestionID, &i.Label, &i.IsCorrect); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const contentProblemQuizQuestions = `-- name: ContentProblemQuizQuestions :many
select id, prompt, coalesce(explain, '') as explain
from public.quiz_questions
where problem_id = $1
order by sort_order, id
`

type ContentProblemQuizQuestionsRow struct {
	ID      string `json:"id"`
	Prompt  string `json:"prompt"`
	Explain string `json:"explain"`
}

func (q *Queries) ContentProblemQuizQuestions(ctx context.Context, problemID pgtype.Text) ([]ContentProblemQuizQuestionsRow, error) {
	rows, err := q.db.Query(ctx, contentProblemQuizQuestions, problemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContentProblemQuizQuestionsRow{}
	for rows.Next() {
		var i ContentProblemQuizQuestionsRow
		if err := rows.Scan(&i.ID, &i.Prompt, &i.Explain); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const contentProblemSolutions = `-- name: ContentProblemSolutions :many
select language, file, code, is_primary
from public.solutions
where problem_id = $1
order by is_primary desc, language, sort_order
`

type ContentProblemSolutionsRow struct {
	Language  string `json:"language"`
	File      string `json:"file"`
	Code      string `json:"code"`
	IsPrimary bool   `json:"is_primary"`
}

func (q *Queries) ContentProblemSolutions(ctx context.Context, problemID string) ([]ContentProblemSolutionsRow, error) {
	rows, err := q.db.Query(ctx, contentProblemSolutions, problemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContentProblemSolutionsRow{}
	for rows.Next() {
		var i ContentProblemSolutionsRow
		if err := rows.Scan(
			&i.Language,
			&i.File,
			&i.Code,
			&i.IsPrimary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const contentProblemTags = `-- name: ContentProblemTags :many
select tag_id
from public.problem_tags
where problem_id = $1
order by tag_id
`

func (q *Queries) ContentProblemTags(ctx context.Context, problemID string) ([]string, error) {
	rows, err := q.db.Query(ctx, contentProblemTags, problemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var tag_id string
		if err := rows.Scan(&tag_id); err != nil {
			return nil, err
		}
		items = append(items, tag_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const contentTopics = `-- name: ContentTopics :many
select id, course_id, title, coalesce(summary, '') as summary
from public.topics
order by course_id, sort_order, id
`

type ContentTopicsRow struct {
	ID       string `json:"id"`
	CourseID string `json:"course_id"`
	Title    string `json:"title"`
	Summary  string `json:"summary"`
}

func (q *Queries) ContentTopics(ctx context.Context) ([]ContentTopicsRow, error) {
	rows, err := q.db.Query(ctx, contentTopics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContentTopicsRow{}
	for rows.Next() {
		var i ContentTopicsRow
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Title,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
