// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: interview.sql

package arcadedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInterviewSession = `-- name: CreateInterviewSession :one
insert into public.interview_sessions (owner_profile_id, title, guest_token)
values ($1::uuid, $2, $3)
returning
  id::text,
  owner_profile_id,
  room_code,
  title,
  status,
  guest_token,
  guest_link_enabled,
  canvas_locked,
  canvas,
  questions,
  notes,
  rubric,
  recommendation,
  created_at,
  updated_at,
  ended_at
`

type CreateInterviewSessionParams struct {
	OwnerProfileID pgtype.UUID `json:"owner_profile_id"`
	Title          string      `json:"title"`
	GuestToken     string      `json:"guest_token"`
}

type CreateInterviewSessionRow struct {
	ID               string             `json:"id"`
	OwnerProfileID   pgtype.UUID        `json:"owner_profile_id"`
	RoomCode         pgtype.Text        `json:"room_code"`
	Title            string             `json:"title"`
	Status           string             `json:"status"`
	GuestToken       string             `json:"guest_token"`
	GuestLinkEnabled bool               `json:"guest_link_enabled"`
	CanvasLocked     bool               `json:"canvas_locked"`
	Canvas           []byte             `json:"canvas"`
	Questions        []byte             `json:"questions"`
	Notes            string             `json:"notes"`
	Rubric           []byte             `json:"rubric"`
	Recommendation   string             `json:"recommendation"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	EndedAt          pgtype.Timestamptz `json:"ended_at"`
}

func (q *Queries) CreateInterviewSession(ctx context.Context, arg CreateInterviewSessionParams) (CreateInterviewSessionRow, error) {
	row := q.db.QueryRow(ctx, createInterviewSession, arg.OwnerProfileID, arg.Title, arg.GuestToken)
	var i CreateInterviewSessionRow
	err := row.Scan(
		&i.ID,
		&i.OwnerProfileID,
		&i.RoomCode,
		&i.Title,
		&i.Status,
		&i.GuestToken,
		&i.GuestLinkEnabled,
		&i.CanvasLocked,
		&i.Canvas,
		&i.Questions,
		&i.Notes,
		&i.Rubric,
		&i.Recommendation,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EndedAt,
	)
	return i, err
}

const endInterviewSession = `-- name: EndInterviewSession :one
update public.interview_sessions
set status = 'ended', ended_at = now(), updated_at = now()
where id = $1::uuid and owner_profile_id = $2::uuid
returning
  id::text,
  owner_profile_id,
  room_code,
  title,
  status,
  guest_token,
  guest_link_enabled,
  canvas_locked,
  canvas,
  questions,
  notes,
  rubric,
  recommendation,
  created_at,
  updated_at,
  ended_at
`

type EndInterviewSessionParams struct {
	ID             pgtype.UUID `json:"id"`
	OwnerProfileID pgtype.UUID `json:"owner_profile_id"`
}

type EndInterviewSessionRow struct {
	ID               string             `json:"id"`
	OwnerProfileID   pgtype.UUID        `json:"owner_profile_id"`
	RoomCode         pgtype.Text        `json:"room_code"`
	Title            string             `json:"title"`
	Status           string             `json:"status"`
	GuestToken       string             `json:"guest_token"`
	GuestLinkEnabled bool               `json:"guest_link_enabled"`
	CanvasLocked     bool               `json:"canvas_locked"`
	Canvas           []byte             `json:"canvas"`
	Questions        []byte             `json:"questions"`
	Notes            string             `json:"notes"`
	Rubric           []byte             `json:"rubric"`
	Recommendation   string             `json:"recommendation"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	EndedAt          pgtype.Timestamptz `json:"ended_at"`
}

func (q *Queries) EndInterviewSession(ctx context.Context, arg EndInterviewSessionParams) (EndInterviewSessionRow, error) {
	row := q.db.QueryRow(ctx, endInterviewSession, arg.ID, arg.OwnerProfileID)
	var i EndInterviewSessionRow
	err := row.Scan(
		&i.ID,
		&i.OwnerProfileID,
		&i.RoomCode,
		&i.Title,
		&i.Status,
		&i.GuestToken,
		&i.GuestLinkEnabled,
		&i.CanvasLocked,
		&i.Canvas,
		&i.Questions,
		&i.Notes,
		&i.Rubric,
		&i.Recommendation,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EndedAt,
	)
	return i, err
}

const getInterviewSession = `-- name: GetInterviewSession :one
select
  id::text,
  owner_profile_id,
  room_code,
  title,
  status,
  guest_token,
  guest_link_enabled,
  canvas_locked,
  canvas,
  questions,
  notes,
  rubric,
  recommendation,
  created_at,
  updated_at,
  ended_at
from public.interview_sessions
where id = $1::uuid
`

type GetInterviewSessionRow struct {
	ID               string             `json:"id"`
	OwnerProfileID   pgtype.UUID        `json:"owner_profile_id"`
	RoomCode         pgtype.Text        `json:"room_code"`
	Title            string             `json:"title"`
	Status           string             `json:"status"`
	GuestToken       string             `json:"guest_token"`
	GuestLinkEnabled bool               `json:"guest_link_enabled"`
	CanvasLocked     bool               `json:"canvas_locked"`
	Canvas           []byte             `json:"canvas"`
	Questions        []byte             `json:"questions"`
	Notes            string             `json:"notes"`
	Rubric           []byte             `json:"rubric"`
	Recommendation   string             `json:"recommendation"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	EndedAt          pgtype.Timestamptz `json:"ended_at"`
}

func (q *Queries) GetInterviewSession(ctx context.Context, id pgtype.UUID) (GetInterviewSessionRow, error) {
	row := q.db.QueryRow(ctx, getInterviewSession, id)
	var i GetInterviewSessionRow
	err := row.Scan(
		&i.ID,
		&i.OwnerProfileID,
		&i.RoomCode,
		&i.Title,
		&i.Status,
		&i.GuestToken,
		&i.GuestLinkEnabled,
		&i.CanvasLocked,
		&i.Canvas,
		&i.Questions,
		&i.Notes,
		&i.Rubric,
		&i.Recommendation,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EndedAt,
	)
	return i, err
}

const getInterviewSessionByToken = `-- name: GetInterviewSessionByToken :one
select
  id::text,
  owner_profile_id,
  room_code,
  title,
  status,
  guest_token,
  guest_link_enabled,
  canvas_locked,
  canvas,
  questions,
  notes,
  rubric,
  recommendation,
  created_at,
  updated_at,
  ended_at
from public.interview_sessions
where guest_token = $1
`

type GetInterviewSessionByTokenRow struct {
	ID               string             `json:"id"`
	OwnerProfileID   pgtype.UUID        `json:"owner_profile_id"`
	RoomCode         pgtype.Text        `json:"room_code"`
	Title            string             `json:"title"`
	Status           string             `json:"status"`
	GuestToken       string             `json:"guest_token"`
	GuestLinkEnabled bool               `json:"guest_link_enabled"`
	CanvasLocked     bool               `json:"canvas_locked"`
	Canvas           []byte             `json:"canvas"`
	Questions        []byte             `json:"questions"`
	Notes            string             `json:"notes"`
	Rubric           []byte             `json:"rubric"`
	Recommendation   string             `json:"recommendation"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	EndedAt          pgtype.Timestamptz `json:"ended_at"`
}

func (q *Queries) GetInterviewSessionByToken(ctx context.Context, guestToken string) (GetInterviewSessionByTokenRow, error) {
	row := q.db.QueryRow(ctx, getInterviewSessionByToken, guestToken)
	var i GetInterviewSessionByTokenRow
	err := row.Scan(
		&i.ID,
		&i.OwnerProfileID,
		&i.RoomCode,
		&i.Title,
		&i.Status,
		&i.GuestToken,
		&i.GuestLinkEnabled,
		&i.CanvasLocked,
		&i.Canvas,
		&i.Questions,
		&i.Notes,
		&i.Rubric,
		&i.Recommendation,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EndedAt,
	)
	return i, err
}

const listInterviewSummaries = `-- name: ListInterviewSummaries :many
select
  id::text,
  title,
  status,
  room_code,
  guest_link_enabled,
  canvas_locked,
  updated_at
from public.interview_sessions
where owner_profile_id = $1::uuid
order by created_at desc
limit 200
`

type ListInterviewSummariesRow struct {
	ID               string             `json:"id"`
	Title            string             `json:"title"`
	Status           string             `json:"status"`
	RoomCode         pgtype.Text        `json:"room_code"`
	GuestLinkEnabled bool               `json:"guest_link_enabled"`
	CanvasLocked     bool               `json:"canvas_locked"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListInterviewSummaries(ctx context.Context, ownerProfileID pgtype.UUID) ([]ListInterviewSummariesRow, error) {
	rows, err := q.db.Query(ctx, listInterviewSummaries, ownerProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInterviewSummariesRow{}
	for rows.Next() {
		var i ListInterviewSummariesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Status,
			&i.RoomCode,
			&i.GuestLinkEnabled,
			&i.CanvasLocked,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reopenInterviewSession = `-- name: ReopenInterviewSession :one
update public.interview_sessions
set status = 'active', ended_at = null, updated_at = now()
where id = $1::uuid and owner_profile_id = $2::uuid
returning
  id::text,
  owner_profile_id,
  room_code,
  title,
  status,
  guest_token,
  guest_link_enabled,
  canvas_locked,
  canvas,
  questions,
  notes,
  rubric,
  recommendation,
  created_at,
  updated_at,
  ended_at
`

type ReopenInterviewSessionParams struct {
	ID             pgtype.UUID `json:"id"`
	OwnerProfileID pgtype.UUID `json:"owner_profile_id"`
}

type ReopenInterviewSessionRow struct {
	ID               string             `json:"id"`
	OwnerProfileID   pgtype.UUID        `json:"owner_profile_id"`
	RoomCode         pgtype.Text        `json:"room_code"`
	Title            string             `json:"title"`
	Status           string             `json:"status"`
	GuestToken       string             `json:"guest_token"`
	GuestLinkEnabled bool               `json:"guest_link_enabled"`
	CanvasLocked     bool               `json:"canvas_locked"`
	Canvas           []byte             `json:"canvas"`
	Questions        []byte             `json:"questions"`
	Notes            string             `json:"notes"`
	Rubric           []byte             `json:"rubric"`
	Recommendation   string             `json:"recommendation"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	EndedAt          pgtype.Timestamptz `json:"ended_at"`
}

func (q *Queries) ReopenInterviewSession(ctx context.Context, arg ReopenInterviewSessionParams) (ReopenInterviewSessionRow, error) {
	row := q.db.QueryRow(ctx, reopenInterviewSession, arg.ID, arg.OwnerProfileID)
	var i ReopenInterviewSessionRow
	err := row.Scan(
		&i.ID,
		&i.OwnerProfileID,
		&i.RoomCode,
		&i.Title,
		&i.Status,
		&i.GuestToken,
		&i.GuestLinkEnabled,
		&i.CanvasLocked,
		&i.Canvas,
		&i.Questions,
		&i.Notes,
		&i.Rubric,
		&i.Recommendation,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EndedAt,
	)
	return i, err
}

const rotateInterviewToken = `-- name: RotateInterviewToken :one
update public.interview_sessions
set guest_token = $1, updated_at = now()
where id = $2::uuid and owner_profile_id = $3::uuid
returning
  id::text,
  owner_profile_id,
  room_code,
  title,
  status,
  guest_token,
  guest_link_enabled,
  canvas_locked,
  canvas,
  questions,
  notes,
  rubric,
  recommendation,
  created_at,
  updated_at,
  ended_at
`

type RotateInterviewTokenParams struct {
	GuestToken     string      `json:"guest_token"`
	ID             pgtype.UUID `json:"id"`
	OwnerProfileID pgtype.UUID `json:"owner_profile_id"`
}

type RotateInterviewTokenRow struct {
	ID               string             `json:"id"`
	OwnerProfileID   pgtype.UUID        `json:"owner_profile_id"`
	RoomCode         pgtype.Text        `json:"room_code"`
	Title            string             `json:"title"`
	Status           string             `json:"status"`
	GuestToken       string             `json:"guest_token"`
	GuestLinkEnabled bool               `json:"guest_link_enabled"`
	CanvasLocked     bool               `json:"canvas_locked"`
	Canvas           []byte             `json:"canvas"`
	Questions        []byte             `json:"questions"`
	Notes            string             `json:"notes"`
	Rubric           []byte             `json:"rubric"`
	Recommendation   string             `json:"recommendation"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	EndedAt          pgtype.Timestamptz `json:"ended_at"`
}

func (q *Queries) RotateInterviewToken(ctx context.Context, arg RotateInterviewTokenParams) (RotateInterviewTokenRow, error) {
	row := q.db.QueryRow(ctx, rotateInterviewToken, arg.GuestToken, arg.ID, arg.OwnerProfileID)
	var i RotateInterviewTokenRow
	err := row.Scan(
		&i.ID,
		&i.OwnerProfileID,
		&i.RoomCode,
		&i.Title,
		&i.Status,
		&i.GuestToken,
		&i.GuestLinkEnabled,
		&i.CanvasLocked,
		&i.Canvas,
		&i.Questions,
		&i.Notes,
		&i.Rubric,
		&i.Recommendation,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EndedAt,
	)
	return i, err
}
