// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resumes.sql

package arcadedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createResume = `-- name: CreateResume :one
insert into public.resumes (
  owner_profile_id,
  title,
  original_filename,
  content_type,
  file_bytes,
  raw_text,
  mapping,
  is_public
)
values (
  $1::uuid,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8
)
returning
  id::text,
  owner_profile_id::text,
  title,
  original_filename,
  content_type,
  raw_text,
  mapping,
  is_public,
  created_at,
  updated_at
`

type CreateResumeParams struct {
	OwnerProfileID   pgtype.UUID `json:"owner_profile_id"`
	Title            string      `json:"title"`
	OriginalFilename string      `json:"original_filename"`
	ContentType      string      `json:"content_type"`
	FileBytes        []byte      `json:"file_bytes"`
	RawText          string      `json:"raw_text"`
	Mapping          []byte      `json:"mapping"`
	IsPublic         bool        `json:"is_public"`
}

type CreateResumeRow struct {
	ID               string             `json:"id"`
	OwnerProfileID   string             `json:"owner_profile_id"`
	Title            string             `json:"title"`
	OriginalFilename string             `json:"original_filename"`
	ContentType      string             `json:"content_type"`
	RawText          string             `json:"raw_text"`
	Mapping          []byte             `json:"mapping"`
	IsPublic         bool               `json:"is_public"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateResume(ctx context.Context, arg CreateResumeParams) (CreateResumeRow, error) {
	row := q.db.QueryRow(ctx, createResume,
		arg.OwnerProfileID,
		arg.Title,
		arg.OriginalFilename,
		arg.ContentType,
		arg.FileBytes,
		arg.RawText,
		arg.Mapping,
		arg.IsPublic,
	)
	var i CreateResumeRow
	err := row.Scan(
		&i.ID,
		&i.OwnerProfileID,
		&i.Title,
		&i.OriginalFilename,
		&i.ContentType,
		&i.RawText,
		&i.Mapping,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createResumeVariant = `-- name: CreateResumeVariant :one
insert into public.resume_variants (
  resume_id,
  owner_profile_id,
  label,
  focus,
  target_role,
  mode,
  mapping
)
values (
  $1::uuid,
  $2::uuid,
  $3,
  $4,
  $5,
  $6,
  $7
)
returning
  id::text,
  resume_id::text,
  owner_profile_id::text,
  label,
  focus,
  target_role,
  mode,
  mapping,
  created_at
`

type CreateResumeVariantParams struct {
	ResumeID       pgtype.UUID `json:"resume_id"`
	OwnerProfileID pgtype.UUID `json:"owner_profile_id"`
	Label          string      `json:"label"`
	Focus          string      `json:"focus"`
	TargetRole     string      `json:"target_role"`
	Mode           string      `json:"mode"`
	Mapping        []byte      `json:"mapping"`
}

type CreateResumeVariantRow struct {
	ID             string             `json:"id"`
	ResumeID       string             `json:"resume_id"`
	OwnerProfileID string             `json:"owner_profile_id"`
	Label          string             `json:"label"`
	Focus          string             `json:"focus"`
	TargetRole     string             `json:"target_role"`
	Mode           string             `json:"mode"`
	Mapping        []byte             `json:"mapping"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateResumeVariant(ctx context.Context, arg CreateResumeVariantParams) (CreateResumeVariantRow, error) {
	row := q.db.QueryRow(ctx, createResumeVariant,
		arg.ResumeID,
		arg.OwnerProfileID,
		arg.Label,
		arg.Focus,
		arg.TargetRole,
		arg.Mode,
		arg.Mapping,
	)
	var i CreateResumeVariantRow
	err := row.Scan(
		&i.ID,
		&i.ResumeID,
		&i.OwnerProfileID,
		&i.Label,
		&i.Focus,
		&i.TargetRole,
		&i.Mode,
		&i.Mapping,
		&i.CreatedAt,
	)
	return i, err
}

const deleteResume = `-- name: DeleteResume :execrows
delete from public.resumes
where id = $1::uuid and owner_profile_id = $2::uuid
`

type DeleteResumeParams struct {
	ID             pgtype.UUID `json:"id"`
	OwnerProfileID pgtype.UUID `json:"owner_profile_id"`
}

func (q *Queries) DeleteResume(ctx context.Context, arg DeleteResumeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteResume, arg.ID, arg.OwnerProfileID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getResumeByID = `-- name: GetResumeByID :one
select
  id::text,
  owner_profile_id::text,
  title,
  original_filename,
  content_type,
  raw_text,
  mapping,
  is_public,
  created_at,
  updated_at
from public.resumes
where id = $1::uuid
`

type GetResumeByIDRow struct {
	ID               string             `json:"id"`
	OwnerProfileID   string             `json:"owner_profile_id"`
	Title            string             `json:"title"`
	OriginalFilename string             `json:"original_filename"`
	ContentType      string             `json:"content_type"`
	RawText          string             `json:"raw_text"`
	Mapping          []byte             `json:"mapping"`
	IsPublic         bool               `json:"is_public"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetResumeByID(ctx context.Context, id pgtype.UUID) (GetResumeByIDRow, error) {
	row := q.db.QueryRow(ctx, getResumeByID, id)
	var i GetResumeByIDRow
	err := row.Scan(
		&i.ID,
		&i.OwnerProfileID,
		&i.Title,
		&i.OriginalFilename,
		&i.ContentType,
		&i.RawText,
		&i.Mapping,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getResumeByIDForOwner = `-- name: GetResumeByIDForOwner :one
select
  id::text,
  owner_profile_id::text,
  title,
  original_filename,
  content_type,
  raw_text,
  mapping,
  is_public,
  created_at,
  updated_at
from public.resumes
where id = $1::uuid and owner_profile_id = $2::uuid
`

type GetResumeByIDForOwnerParams struct {
	ID             pgtype.UUID `json:"id"`
	OwnerProfileID pgtype.UUID `json:"owner_profile_id"`
}

type GetResumeByIDForOwnerRow struct {
	ID               string             `json:"id"`
	OwnerProfileID   string             `json:"owner_profile_id"`
	Title            string             `json:"title"`
	OriginalFilename string             `json:"original_filename"`
	ContentType      string             `json:"content_type"`
	RawText          string             `json:"raw_text"`
	Mapping          []byte             `json:"mapping"`
	IsPublic         bool               `json:"is_public"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetResumeByIDForOwner(ctx context.Context, arg GetResumeByIDForOwnerParams) (GetResumeByIDForOwnerRow, error) {
	row := q.db.QueryRow(ctx, getResumeByIDForOwner, arg.ID, arg.OwnerProfileID)
	var i GetResumeByIDForOwnerRow
	err := row.Scan(
		&i.ID,
		&i.OwnerProfileID,
		&i.Title,
		&i.OriginalFilename,
		&i.ContentType,
		&i.RawText,
		&i.Mapping,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPublicResumeDirectory = `-- name: ListPublicResumeDirectory :many
select
  r.id::text as id,
  r.title,
  r.original_filename,
  r.updated_at,
  p.id::text as owner_profile_id,
  p.display_name as owner_display_name,
  p.avatar_seed as owner_avatar_seed
from public.resumes r
join public.profiles p on p.id = r.owner_profile_id
where r.is_public = true
order by r.updated_at desc
limit 500
`

type ListPublicResumeDirectoryRow struct {
	ID               string             `json:"id"`
	Title            string             `json:"title"`
	OriginalFilename string             `json:"original_filename"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	OwnerProfileID   string             `json:"owner_profile_id"`
	OwnerDisplayName string             `json:"owner_display_name"`
	OwnerAvatarSeed  string             `json:"owner_avatar_seed"`
}

func (q *Queries) ListPublicResumeDirectory(ctx context.Context) ([]ListPublicResumeDirectoryRow, error) {
	rows, err := q.db.Query(ctx, listPublicResumeDirectory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublicResumeDirectoryRow{}
	for rows.Next() {
		var i ListPublicResumeDirectoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.OriginalFilename,
			&i.UpdatedAt,
			&i.OwnerProfileID,
			&i.OwnerDisplayName,
			&i.OwnerAvatarSeed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResumeSummaries = `-- name: ListResumeSummaries :many
select
  r.id::text as id,
  r.title,
  r.original_filename,
  r.is_public,
  r.updated_at
from public.resumes r
where r.owner_profile_id = $1::uuid
order by r.created_at desc
limit 200
`

type ListResumeSummariesRow struct {
	ID               string             `json:"id"`
	Title            string             `json:"title"`
	OriginalFilename string             `json:"original_filename"`
	IsPublic         bool               `json:"is_public"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListResumeSummaries(ctx context.Context, ownerProfileID pgtype.UUID) ([]ListResumeSummariesRow, error) {
	rows, err := q.db.Query(ctx, listResumeSummaries, ownerProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListResumeSummariesRow{}
	for rows.Next() {
		var i ListResumeSummariesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.OriginalFilename,
			&i.IsPublic,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResumeVariants = `-- name: ListResumeVariants :many
select
  id::text,
  resume_id::text,
  owner_profile_id::text,
  label,
  focus,
  target_role,
  mode,
  mapping,
  created_at
from public.resume_variants
where resume_id = $1::uuid and owner_profile_id = $2::uuid
order by created_at desc
limit 100
`

type ListResumeVariantsParams struct {
	ResumeID       pgtype.UUID `json:"resume_id"`
	OwnerProfileID pgtype.UUID `json:"owner_profile_id"`
}

type ListResumeVariantsRow struct {
	ID             string             `json:"id"`
	ResumeID       string             `json:"resume_id"`
	OwnerProfileID string             `json:"owner_profile_id"`
	Label          string             `json:"label"`
	Focus          string             `json:"focus"`
	TargetRole     string             `json:"target_role"`
	Mode           string             `json:"mode"`
	Mapping        []byte             `json:"mapping"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListResumeVariants(ctx context.Context, arg ListResumeVariantsParams) ([]ListResumeVariantsRow, error) {
	rows, err := q.db.Query(ctx, listResumeVariants, arg.ResumeID, arg.OwnerProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListResumeVariantsRow{}
	for rows.Next() {
		var i ListResumeVariantsRow
		if err := rows.Scan(
			&i.ID,
			&i.ResumeID,
			&i.OwnerProfileID,
			&i.Label,
			&i.Focus,
			&i.TargetRole,
			&i.Mode,
			&i.Mapping,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateResume = `-- name: UpdateResume :one
update public.resumes
set
  title = coalesce($1, title),
  mapping = coalesce($2, mapping),
  is_public = coalesce($3, is_public),
  updated_at = now()
where id = $4::uuid and owner_profile_id = $5::uuid
returning
  id::text,
  owner_profile_id::text,
  title,
  original_filename,
  content_type,
  raw_text,
  mapping,
  is_public,
  created_at,
  updated_at
`

type UpdateResumeParams struct {
	Title          pgtype.Text `json:"title"`
	Mapping        []byte      `json:"mapping"`
	IsPublic       pgtype.Bool `json:"is_public"`
	ID             pgtype.UUID `json:"id"`
	OwnerProfileID pgtype.UUID `json:"owner_profile_id"`
}

type UpdateResumeRow struct {
	ID               string             `json:"id"`
	OwnerProfileID   string             `json:"owner_profile_id"`
	Title            string             `json:"title"`
	OriginalFilename string             `json:"original_filename"`
	ContentType      string             `json:"content_type"`
	RawText          string             `json:"raw_text"`
	Mapping          []byte             `json:"mapping"`
	IsPublic         bool               `json:"is_public"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateResume(ctx context.Context, arg UpdateResumeParams) (UpdateResumeRow, error) {
	row := q.db.QueryRow(ctx, updateResume,
		arg.Title,
		arg.Mapping,
		arg.IsPublic,
		arg.ID,
		arg.OwnerProfileID,
	)
	var i UpdateResumeRow
	err := row.Scan(
		&i.ID,
		&i.OwnerProfileID,
		&i.Title,
		&i.OriginalFilename,
		&i.ContentType,
		&i.RawText,
		&i.Mapping,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
