const KIND_ACCENT: Record<string, string> = {
  workbench: 'var(--edge-active)',
  problem: 'var(--edge-active)',
  viz: 'var(--team1-stroke)',
  replay: 'var(--accent)',
  inspector: 'var(--ring)',
  metrics: 'var(--text-3)',
  bigo: 'var(--edge-active)',
  bookmarks: 'var(--accent)',
  editor: 'var(--team1-stroke)',
  copy: 'var(--good)',
  cases: 'var(--good)',
  code: 'var(--team2-stroke)',
  reassemble: 'var(--team2-stroke)',
  recall: 'var(--team2-stroke)',
  quiz: 'var(--accent)',
  simulate: 'var(--team1-stroke)',
  predict: 'var(--accent)',
  mastery: 'var(--good)',
  mistakes: 'var(--bad)',
  explain: 'var(--edge-active)',
  badges: 'var(--ring)',
  pattern: 'var(--team1-stroke)',
  glossary: 'var(--accent)',
  diff: 'var(--edge-active)',
  watch: 'var(--team2-stroke)',
  hints: 'var(--accent)',
  path: 'var(--team1-stroke)',
  cheatsheet: 'var(--text-3)',
  projects: 'var(--accent)',
  notes: 'var(--edge-active)',
  whiteboard: 'var(--team1-stroke)',
  'collab-code': 'var(--team2-stroke)',
  complexity: 'var(--accent)',
  edgecases: 'var(--edge-active)',
};

export function panelAccent(kind: string): string {
  return KIND_ACCENT[kind] ?? 'var(--accent)';
}
