// AUTO-GENERATED — Go→Python+Java ports, differentially verified. Do not edit by hand.
export const IMPORTED_LIBS_PORTS: Record<string, { python?: string; java?: string }> = {
  'imp-26-subsets': {
    python:
      'from typing import List\n\n\ndef all_subsets(a: List[int]) -> List[List[int]]:\n    res: List[List[int]] = []\n    _bt_subsets(a, 0, [], res)\n    return res\n\n\ndef _bt_subsets(a: List[int], idx: int, path: List[int], res: List[List[int]]) -> None:\n    res.append(list(path))\n    for i in range(idx, len(a)):\n        path.append(a[i])\n        _bt_subsets(a, i + 1, path, res)\n        path.pop()',
    java: 'class Solution {\n    public java.util.List<java.util.List<Integer>> allSubsets(int[] a) {\n        java.util.List<java.util.List<Integer>> res = new java.util.ArrayList<>();\n        btSubsets(a, 0, new java.util.ArrayList<>(), res);\n        return res;\n    }\n\n    private void btSubsets(int[] a, int idx, java.util.List<Integer> path,\n                           java.util.List<java.util.List<Integer>> res) {\n        res.add(new java.util.ArrayList<>(path));\n        for (int i = idx; i < a.length; i++) {\n            path.add(a[i]);\n            btSubsets(a, i + 1, path, res);\n            path.remove(path.size() - 1);\n        }\n    }\n}',
  },
  'imp-27-combinations': {
    python:
      'from typing import List\n\n\ndef combination_nums(n: int, k: int) -> List[List[int]]:\n    res: List[List[int]] = []\n    _bt_comb(1, n, k, [], res)\n    return res\n\n\ndef _bt_comb(idx: int, n: int, k: int, path: List[int], res: List[List[int]]) -> None:\n    if len(path) == k:\n        res.append(path[:])\n        return\n    for num in range(idx, n + 1):\n        _bt_comb(num + 1, n, k, path + [num], res)',
    java: 'import java.util.ArrayList;\nimport java.util.List;\n\nclass Solution {\n\n    List<List<Integer>> combinationNums(int n, int k) {\n        List<List<Integer>> res = new ArrayList<>();\n        btComb(1, n, k, new ArrayList<>(), res);\n        return res;\n    }\n\n    private void btComb(int idx, int n, int k, List<Integer> path, List<List<Integer>> res) {\n        if (path.size() == k) {\n            res.add(new ArrayList<>(path));\n            return;\n        }\n        for (int num = idx; num <= n; num++) {\n            path.add(num);\n            btComb(num + 1, n, k, path, res);\n            path.remove(path.size() - 1);\n        }\n    }\n}',
  },
  'imp-28-combination-of-subset-strings': {
    python:
      'from typing import List\n\n\ndef combination_subset_str(s: str, k: int) -> List[str]:\n    res: List[str] = []\n    _bt_subset_str(list(s), k, [], res)\n    return res\n\n\ndef _bt_subset_str(chars: List[str], k: int, path: List[str], res: List[str]) -> None:\n    if len(path) == k:\n        res.append("".join(path))\n        return\n    for ch in chars:\n        _bt_subset_str(chars, k, path + [ch], res)',
    java: 'import java.util.ArrayList;\nimport java.util.List;\n\nclass Solution {\n\n    List<String> combinationSubsetStr(String str, int k) {\n        List<String> res = new ArrayList<>();\n        btSubsetStr(str.toCharArray(), k, new StringBuilder(), res);\n        return res;\n    }\n\n    private void btSubsetStr(char[] chars, int k, StringBuilder path, List<String> res) {\n        if (path.length() == k) {\n            res.add(path.toString());\n            return;\n        }\n        for (char ch : chars) {\n            path.append(ch);\n            btSubsetStr(chars, k, path, res);\n            path.deleteCharAt(path.length() - 1);\n        }\n    }\n}',
  },
  'imp-29-combination-sum-ii': {
    python:
      'from typing import List\n\n\ndef combination_sum_k(a: List[int], target: int) -> List[List[int]]:\n    sorted_a = sorted(a)\n    res: List[List[int]] = []\n    _bt_comb_sum(sorted_a, 0, target, [], res)\n    return res\n\n\ndef _bt_comb_sum(a: List[int], idx: int, target: int, path: List[int], res: List[List[int]]) -> None:\n    if target < 0:\n        return\n    if target == 0:\n        res.append(list(path))\n        return\n    i = idx\n    while i < len(a) and target >= a[i]:\n        if i > idx and a[i] == a[i - 1]:\n            i += 1\n            continue\n        _bt_comb_sum(a, i + 1, target - a[i], path + [a[i]], res)\n        i += 1',
    java: 'import java.util.ArrayList;\nimport java.util.Arrays;\nimport java.util.List;\n\nclass Solution {\n\n    static List<List<Integer>> combinationSumK(int[] a, int target) {\n        int[] sorted = a.clone();\n        Arrays.sort(sorted);\n        List<List<Integer>> res = new ArrayList<>();\n        btCombSum(sorted, 0, target, new ArrayList<>(), res);\n        return res;\n    }\n\n    static void btCombSum(int[] a, int idx, int target, List<Integer> path, List<List<Integer>> res) {\n        if (target < 0) {\n            return;\n        }\n        if (target == 0) {\n            res.add(new ArrayList<>(path));\n            return;\n        }\n        for (int i = idx; i < a.length && target >= a[i]; i++) {\n            if (i > idx && a[i] == a[i - 1]) {\n                continue;\n            }\n            path.add(a[i]);\n            btCombSum(a, i + 1, target - a[i], path, res);\n            path.remove(path.size() - 1);\n        }\n    }\n}',
  },
  'imp-30-decode-numbers': {
    python:
      'from typing import Dict, List\n\n\ndef decode_numbers(digits: str, dict_map: Dict[str, str]) -> List[str]:\n    res: List[str] = []\n    _bt_decode(digits, 0, "", dict_map, res)\n    return res\n\n\ndef _bt_decode(s: str, idx: int, path: str, dict_map: Dict[str, str], res: List[str]) -> None:\n    if idx == len(s):\n        res.append(path)\n        return\n    for key, ch in dict_map.items():\n        if idx + len(key) <= len(s) and s[idx:idx + len(key)] == key:\n            _bt_decode(s, idx + len(key), path + ch, dict_map, res)',
    java: 'import java.util.ArrayList;\nimport java.util.List;\nimport java.util.Map;\n\nclass Solution {\n    public List<String> decodeNumbers(String digits, Map<String, Character> dict) {\n        List<String> res = new ArrayList<>();\n        btDecode(digits, 0, "", dict, res);\n        return res;\n    }\n\n    private void btDecode(String s, int idx, String path, Map<String, Character> dict, List<String> res) {\n        if (idx == s.length()) {\n            res.add(path);\n            return;\n        }\n        for (Map.Entry<String, Character> e : dict.entrySet()) {\n            String key = e.getKey();\n            char ch = e.getValue();\n            if (idx + key.length() <= s.length() && s.substring(idx, idx + key.length()).equals(key)) {\n                btDecode(s, idx + key.length(), path + ch, dict, res);\n            }\n        }\n    }\n}',
  },
  'imp-31-expression-add-operators': {
    python:
      'from typing import List\n\n\ndef add_operators(num: str, target: int) -> List[str]:\n    res: List[str] = []\n    _bt_add_operators(num, target, 0, "", 0, 0, res)\n    return res\n\n\ndef _bt_add_operators(\n    num: str,\n    target: int,\n    idx: int,\n    path: str,\n    eval_: int,\n    prev: int,\n    res: List[str],\n) -> None:\n    if idx == len(num):\n        if eval_ == target:\n            res.append(path)\n        return\n    for i in range(idx, len(num)):\n        if i > idx and num[idx] == "0":\n            break\n        sub = num[idx : i + 1]\n        val = int(sub)\n        if idx == 0:\n            _bt_add_operators(num, target, i + 1, sub, val, val, res)\n        else:\n            _bt_add_operators(num, target, i + 1, path + "+" + sub, eval_ + val, val, res)\n            _bt_add_operators(num, target, i + 1, path + "-" + sub, eval_ - val, -val, res)\n            _bt_add_operators(\n                num, target, i + 1, path + "*" + sub, eval_ - prev + prev * val, prev * val, res\n            )',
    java: 'import java.util.ArrayList;\nimport java.util.List;\n\nclass Solution {\n\n    public List<String> addOperators(String num, long target) {\n        List<String> res = new ArrayList<>();\n        bt(num, target, 0, "", 0L, 0L, res);\n        return res;\n    }\n\n    private void bt(String num, long target, int idx, String path, long eval, long prev, List<String> res) {\n        if (idx == num.length()) {\n            if (eval == target) {\n                res.add(path);\n            }\n            return;\n        }\n        for (int i = idx; i < num.length(); i++) {\n            if (i > idx && num.charAt(idx) == \'0\') {\n                break;\n            }\n            String sub = num.substring(idx, i + 1);\n            long val = Long.parseLong(sub);\n            if (idx == 0) {\n                bt(num, target, i + 1, sub, val, val, res);\n            } else {\n                bt(num, target, i + 1, path + "+" + sub, eval + val, val, res);\n                bt(num, target, i + 1, path + "-" + sub, eval - val, -val, res);\n                bt(num, target, i + 1, path + "*" + sub, eval - prev + prev * val, prev * val, res);\n            }\n        }\n    }\n}',
  },
  'imp-33-strobogrammatic-number-ii': {
    python:
      "from typing import List\n\n\ndef gen_strobo_nums(n: int) -> List[str]:\n    res: List[str] = []\n    if n == 0:\n        return res\n    path = ['\\0'] * n\n    _bt_strobo(path, 0, n - 1, res)\n    return res\n\n\ndef _bt_strobo(path: List[str], low: int, high: int, res: List[str]) -> None:\n    if low > high:\n        res.append(''.join(path))\n        return\n    if low == high:\n        for c in ['0', '1', '8']:\n            path[low] = c\n            res.append(''.join(path))\n        return\n    pairs = [('0', '0'), ('1', '1'), ('8', '8'), ('6', '9'), ('9', '6')]\n    for pair in pairs:\n        if low == 0 and pair[0] == '0':\n            continue\n        path[low] = pair[0]\n        path[high] = pair[1]\n        _bt_strobo(path, low + 1, high - 1, res)",
    java: "import java.util.ArrayList;\nimport java.util.List;\n\nclass Solution {\n\n    List<String> genStroboNums(int n) {\n        List<String> res = new ArrayList<>();\n        if (n == 0) {\n            return res;\n        }\n        char[] path = new char[n];\n        btStrobo(path, 0, n - 1, res);\n        return res;\n    }\n\n    void btStrobo(char[] path, int low, int high, List<String> res) {\n        if (low > high) {\n            res.add(new String(path));\n            return;\n        }\n        if (low == high) {\n            for (char c : new char[]{'0', '1', '8'}) {\n                path[low] = c;\n                res.add(new String(path));\n            }\n            return;\n        }\n        char[][] pairs = {{'0', '0'}, {'1', '1'}, {'8', '8'}, {'6', '9'}, {'9', '6'}};\n        for (char[] pair : pairs) {\n            if (low == 0 && pair[0] == '0') {\n                continue;\n            }\n            path[low] = pair[0];\n            path[high] = pair[1];\n            btStrobo(path, low + 1, high - 1, res);\n        }\n    }\n}",
  },
  'imp-34-generate-parentheses': {
    python:
      'from typing import List\n\n\ndef gen_valid_paren(n: int) -> List[str]:\n    res: List[str] = []\n    _bt_paren(n, 0, 0, "", res)\n    return res\n\n\ndef _bt_paren(n: int, open_: int, close_: int, path: str, res: List[str]) -> None:\n    if len(path) == 2 * n:\n        res.append(path)\n        return\n    if open_ < n:\n        _bt_paren(n, open_ + 1, close_, path + "(", res)\n    if close_ < open_:\n        _bt_paren(n, open_, close_ + 1, path + ")", res)',
    java: 'import java.util.ArrayList;\nimport java.util.List;\n\nclass Solution {\n    public List<String> genValidParen(int n) {\n        List<String> res = new ArrayList<>();\n        btParen(n, 0, 0, "", res);\n        return res;\n    }\n\n    private void btParen(int n, int open, int close, String path, List<String> res) {\n        if (path.length() == 2 * n) {\n            res.add(path);\n            return;\n        }\n        if (open < n) {\n            btParen(n, open + 1, close, path + "(", res);\n        }\n        if (close < open) {\n            btParen(n, open, close + 1, path + ")", res);\n        }\n    }\n}',
  },
  'imp-36-letter-combinations-of-a-phone-number': {
    python:
      'from typing import List\n\nPHONE_PAD = ["0", "1", "abc", "def", "ghi", "jkl", "mno", "pqrs", "tuv", "wxyz"]\n\n\ndef letter_combinations(digits: str) -> List[str]:\n    if len(digits) == 0:\n        return []\n    res: List[str] = []\n    _bt_letters(digits, 0, "", res)\n    return res\n\n\ndef _bt_letters(digits: str, idx: int, path: str, res: List[str]) -> None:\n    if idx == len(digits):\n        res.append(path)\n        return\n    letters = PHONE_PAD[ord(digits[idx]) - ord("0")]\n    for ch in letters:\n        _bt_letters(digits, idx + 1, path + ch, res)',
    java: 'class Solution {\n\n    static final String[] PHONE_PAD = {"0", "1", "abc", "def", "ghi", "jkl", "mno", "pqrs", "tuv", "wxyz"};\n\n    public java.util.List<String> letterCombinations(String digits) {\n        if (digits.length() == 0) {\n            return new java.util.ArrayList<>();\n        }\n        java.util.List<String> res = new java.util.ArrayList<>();\n        btLetters(digits, 0, "", res);\n        return res;\n    }\n\n    private void btLetters(String digits, int idx, String path, java.util.List<String> res) {\n        if (idx == digits.length()) {\n            res.add(path);\n            return;\n        }\n        String letters = PHONE_PAD[digits.charAt(idx) - \'0\'];\n        for (int i = 0; i < letters.length(); i++) {\n            btLetters(digits, idx + 1, path + letters.charAt(i), res);\n        }\n    }\n}',
  },
  'imp-37-maximum-length-of-a-concatenated-string-with-uni': {
    python:
      'from typing import List\n\n\ndef max_length(arr: List[str]) -> int:\n    masks: List[int] = []\n    for s in arr:\n        mask = 0\n        dup = False\n        for ch in s:\n            bit = 1 << (ord(ch) - ord(\'a\'))\n            if mask & bit:\n                dup = True\n                break\n            mask |= bit\n        if not dup:\n            masks.append(mask)\n    res = [0]\n    _bt_max_length(masks, 0, 0, res)\n    return res[0]\n\n\ndef _bt_max_length(masks: List[int], idx: int, path: int, res: List[int]) -> None:\n    cnt = bin(path).count("1")\n    if cnt > res[0]:\n        res[0] = cnt\n    for i in range(idx, len(masks)):\n        if path & masks[i] == 0:\n            _bt_max_length(masks, i + 1, path | masks[i], res)',
    java: "import java.util.ArrayList;\nimport java.util.List;\n\nclass Solution {\n\n    public int maxLength(List<String> arr) {\n        List<Integer> masks = new ArrayList<>();\n        for (String s : arr) {\n            int mask = 0;\n            boolean dup = false;\n            for (int i = 0; i < s.length(); i++) {\n                int bit = 1 << (s.charAt(i) - 'a');\n                if ((mask & bit) > 0) {\n                    dup = true;\n                    break;\n                }\n                mask |= bit;\n            }\n            if (!dup) {\n                masks.add(mask);\n            }\n        }\n        int[] res = new int[]{0};\n        btMaxLength(masks, 0, 0, res);\n        return res[0];\n    }\n\n    private void btMaxLength(List<Integer> masks, int idx, int path, int[] res) {\n        int cnt = Integer.bitCount(path);\n        if (cnt > res[0]) {\n            res[0] = cnt;\n        }\n        for (int i = idx; i < masks.size(); i++) {\n            if ((path & masks.get(i)) == 0) {\n                btMaxLength(masks, i + 1, path | masks.get(i), res);\n            }\n        }\n    }\n}",
  },
  'imp-38-nested-list-weight-sum': {
    python:
      'from typing import List, Optional\n\n\nclass NestedInteger:\n    def __init__(self, integer: bool, val: int = 0,\n                 lst: Optional[List["NestedInteger"]] = None):\n        self.integer = integer\n        self.val = val\n        self.list = lst if lst is not None else []\n\n\ndef depth_sum(nested_list: List[NestedInteger]) -> int:\n    return _bt_depth_sum(nested_list, 1)\n\n\ndef _bt_depth_sum(nested_list: List[NestedInteger], depth: int) -> int:\n    total = 0\n    for item in nested_list:\n        if item.integer:\n            total += item.val * depth\n        else:\n            total += _bt_depth_sum(item.list, depth + 1)\n    return total',
    java: 'import java.util.ArrayList;\nimport java.util.List;\n\nclass Solution {\n\n    static class NestedInteger {\n        boolean integer;\n        int val;\n        List<NestedInteger> list;\n\n        NestedInteger(boolean integer, int val, List<NestedInteger> list) {\n            this.integer = integer;\n            this.val = val;\n            this.list = (list != null) ? list : new ArrayList<>();\n        }\n    }\n\n    public int depthSum(List<NestedInteger> nestedList) {\n        return btDepthSum(nestedList, 1);\n    }\n\n    private int btDepthSum(List<NestedInteger> nestedList, int depth) {\n        int sum = 0;\n        for (NestedInteger item : nestedList) {\n            if (item.integer) {\n                sum += item.val * depth;\n            } else {\n                sum += btDepthSum(item.list, depth + 1);\n            }\n        }\n        return sum;\n    }\n}',
  },
  'imp-39-different-ways-to-add-parentheses': {
    python:
      'from typing import List, Dict\n\n\ndef operator_combinations(tokens: List[int]) -> List[int]:\n    memo: Dict[str, List[int]] = {}\n    return _bt_ops(tokens, memo)\n\n\ndef _int_div_trunc(a: int, b: int) -> int:\n    q = abs(a) // abs(b)\n    if (a < 0) != (b < 0):\n        q = -q\n    return q\n\n\ndef _bt_ops(t: List[int], memo: Dict[str, List[int]]) -> List[int]:\n    key = _bt_ints_key(t)\n    if key in memo:\n        return memo[key]\n    if len(t) == 1:\n        return [t[0]]\n    res: List[int] = []\n    for i in range(1, len(t)):\n        left = _bt_ops(t[:i], memo)\n        right = _bt_ops(t[i:], memo)\n        for a in left:\n            for b in right:\n                res.append(a + b)\n                res.append(a - b)\n                res.append(a * b)\n                if b != 0:\n                    res.append(_int_div_trunc(a, b))\n    memo[key] = res\n    return res\n\n\ndef _bt_ints_key(a: List[int]) -> str:\n    return ",".join(str(v) for v in a)',
    java: 'import java.util.*;\n\nclass Solution {\n\n    List<Integer> operatorCombinations(int[] tokens) {\n        Map<String, List<Integer>> memo = new HashMap<>();\n        return btOps(tokens, memo);\n    }\n\n    private List<Integer> btOps(int[] t, Map<String, List<Integer>> memo) {\n        String key = btIntsKey(t);\n        List<Integer> cached = memo.get(key);\n        if (cached != null) {\n            return cached;\n        }\n        if (t.length == 1) {\n            List<Integer> single = new ArrayList<>();\n            single.add(t[0]);\n            return single;\n        }\n        List<Integer> res = new ArrayList<>();\n        for (int i = 1; i < t.length; i++) {\n            List<Integer> left = btOps(Arrays.copyOfRange(t, 0, i), memo);\n            List<Integer> right = btOps(Arrays.copyOfRange(t, i, t.length), memo);\n            for (int a : left) {\n                for (int b : right) {\n                    res.add(a + b);\n                    res.add(a - b);\n                    res.add(a * b);\n                    if (b != 0) {\n                        res.add(a / b);\n                    }\n                }\n            }\n        }\n        memo.put(key, res);\n        return res;\n    }\n\n    private String btIntsKey(int[] a) {\n        StringBuilder sb = new StringBuilder();\n        for (int i = 0; i < a.length; i++) {\n            if (i > 0) {\n                sb.append(",");\n            }\n            sb.append(a[i]);\n        }\n        return sb.toString();\n    }\n}',
  },
  'imp-40-restore-ip-addresses': {
    python:
      'from typing import List\n\n\ndef partition_combinations(digits: str) -> List[str]:\n    if len(digits) > 12:\n        return []\n    res: List[str] = []\n    _bt_ip(digits, 0, 0, "", res)\n    return res\n\n\ndef _bt_ip(s: str, idx: int, dots: int, path: str, res: List[str]) -> None:\n    if dots == 3:\n        if _bt_valid_ip_part(s[idx:]):\n            res.append(path + "." + s[idx:])\n        return\n    for i in range(idx, len(s)):\n        if i > idx and s[idx] == \'0\':\n            break\n        part = s[idx:i + 1]\n        if not _bt_valid_ip_part(part):\n            continue\n        sep = "." if path != "" else ""\n        _bt_ip(s, i + 1, dots + 1, path + sep + part, res)\n\n\ndef _bt_valid_ip_part(part: str) -> bool:\n    if len(part) == 0 or len(part) > 3:\n        return False\n    if len(part) > 1 and part[0] == \'0\':\n        return False\n    val = 0\n    for ch in part:\n        val = val * 10 + (ord(ch) - ord(\'0\'))\n    return val <= 255',
    java: 'import java.util.ArrayList;\nimport java.util.List;\n\nclass Solution {\n    public List<String> partitionCombinations(String digits) {\n        List<String> res = new ArrayList<>();\n        if (digits.length() > 12) {\n            return res;\n        }\n        btIP(digits, 0, 0, "", res);\n        return res;\n    }\n\n    private void btIP(String s, int idx, int dots, String path, List<String> res) {\n        if (dots == 3) {\n            if (btValidIPPart(s.substring(idx))) {\n                res.add(path + "." + s.substring(idx));\n            }\n            return;\n        }\n        for (int i = idx; i < s.length(); i++) {\n            if (i > idx && s.charAt(idx) == \'0\') {\n                break;\n            }\n            String part = s.substring(idx, i + 1);\n            if (!btValidIPPart(part)) {\n                continue;\n            }\n            String sep = path.isEmpty() ? "" : ".";\n            btIP(s, i + 1, dots + 1, path + sep + part, res);\n        }\n    }\n\n    private boolean btValidIPPart(String part) {\n        if (part.length() == 0 || part.length() > 3) {\n            return false;\n        }\n        if (part.length() > 1 && part.charAt(0) == \'0\') {\n            return false;\n        }\n        int val = 0;\n        for (int i = 0; i < part.length(); i++) {\n            val = val * 10 + (part.charAt(i) - \'0\');\n        }\n        return val <= 255;\n    }\n}',
  },
  'imp-41-permutations': {
    python:
      'from typing import List\n\n\ndef perm_array(a: List[int]) -> List[List[int]]:\n    res: List[List[int]] = []\n    nums = list(a)\n    _bt_perm(nums, 0, res)\n    return res\n\n\ndef _bt_perm(a: List[int], idx: int, res: List[List[int]]) -> None:\n    if idx == len(a):\n        res.append(list(a))\n        return\n    for i in range(idx, len(a)):\n        a[idx], a[i] = a[i], a[idx]\n        _bt_perm(a, idx + 1, res)\n        a[idx], a[i] = a[i], a[idx]',
    java: 'import java.util.ArrayList;\nimport java.util.List;\n\nclass Solution {\n\n    static List<List<Integer>> permArray(int[] a) {\n        List<List<Integer>> res = new ArrayList<>();\n        int[] nums = a.clone();\n        btPerm(nums, 0, res);\n        return res;\n    }\n\n    static void btPerm(int[] a, int idx, List<List<Integer>> res) {\n        if (idx == a.length) {\n            List<Integer> row = new ArrayList<>(a.length);\n            for (int v : a) row.add(v);\n            res.add(row);\n            return;\n        }\n        for (int i = idx; i < a.length; i++) {\n            int tmp = a[idx];\n            a[idx] = a[i];\n            a[i] = tmp;\n            btPerm(a, idx + 1, res);\n            tmp = a[idx];\n            a[idx] = a[i];\n            a[i] = tmp;\n        }\n    }\n}',
  },
  'imp-42-cartesian-product-of-multiple-arrays': {
    python:
      'from typing import List\n\n\ndef perm_multiple_arrays(lists: List[List[str]]) -> List[List[str]]:\n    res: List[List[str]] = []\n    seen = set()\n    _bt_perm_lists(lists, [], res, seen)\n    return res\n\n\ndef _bt_perm_lists(lists, path, res, seen):\n    if len(lists) == 0:\n        key = ",".join(path)\n        if key in seen:\n            return\n        seen.add(key)\n        res.append(list(path))\n        return\n    for s in lists[0]:\n        _bt_perm_lists(lists[1:], path + [s], res, seen)',
    java: 'import java.util.ArrayList;\nimport java.util.HashSet;\nimport java.util.List;\nimport java.util.Set;\n\nclass Solution {\n    public List<List<String>> permMultipleArrays(List<List<String>> lists) {\n        List<List<String>> res = new ArrayList<>();\n        Set<String> seen = new HashSet<>();\n        btPermLists(lists, new ArrayList<>(), res, seen);\n        return res;\n    }\n\n    private void btPermLists(List<List<String>> lists, List<String> path,\n                             List<List<String>> res, Set<String> seen) {\n        if (lists.isEmpty()) {\n            String key = String.join(",", path);\n            if (seen.contains(key)) {\n                return;\n            }\n            seen.add(key);\n            res.add(new ArrayList<>(path));\n            return;\n        }\n        for (String s : lists.get(0)) {\n            List<String> next = new ArrayList<>(path);\n            next.add(s);\n            btPermLists(lists.subList(1, lists.size()), next, res, seen);\n        }\n    }\n}',
  },
  'imp-43-permutations': {
    python:
      'def perm_string(s):\n    res = []\n    path = list(s)\n    _bt_perm_str(path, 0, len(path) - 1, res)\n    return res\n\n\ndef _bt_perm_str(path, low, high, res):\n    if low == high:\n        res.append("".join(path))\n        return\n    for i in range(low, high + 1):\n        path[low], path[i] = path[i], path[low]\n        _bt_perm_str(path, low + 1, high, res)\n        path[low], path[i] = path[i], path[low]',
    java: 'import java.util.ArrayList;\nimport java.util.List;\n\nclass Solution {\n\n    List<String> permString(String str) {\n        List<String> res = new ArrayList<>();\n        char[] path = str.toCharArray();\n        btPermStr(path, 0, path.length - 1, res);\n        return res;\n    }\n\n    void btPermStr(char[] path, int low, int high, List<String> res) {\n        if (low == high) {\n            res.add(new String(path));\n            return;\n        }\n        for (int i = low; i <= high; i++) {\n            char tmp = path[low];\n            path[low] = path[i];\n            path[i] = tmp;\n            btPermStr(path, low + 1, high, res);\n            tmp = path[low];\n            path[low] = path[i];\n            path[i] = tmp;\n        }\n    }\n}',
  },
  'imp-44-word-search': {
    python:
      "from typing import List\n\n\ndef exist(board: List[List[str]], word: str) -> bool:\n    m, n = len(board), len(board[0])\n\n    def bt(r: int, c: int, idx: int) -> bool:\n        if idx == len(word):\n            return True\n        if r < 0 or r >= m or c < 0 or c >= n or board[r][c] != word[idx]:\n            return False\n        tmp = board[r][c]\n        board[r][c] = '#'\n        found = (\n            bt(r + 1, c, idx + 1)\n            or bt(r - 1, c, idx + 1)\n            or bt(r, c + 1, idx + 1)\n            or bt(r, c - 1, idx + 1)\n        )\n        board[r][c] = tmp\n        return found\n\n    for r in range(m):\n        for c in range(n):\n            if bt(r, c, 0):\n                return True\n    return False",
    java: "class Solution {\n    public boolean exist(char[][] board, String word) {\n        int m = board.length, n = board[0].length;\n        for (int r = 0; r < m; r++) {\n            for (int c = 0; c < n; c++) {\n                if (bt(board, word, m, n, r, c, 0)) {\n                    return true;\n                }\n            }\n        }\n        return false;\n    }\n\n    private boolean bt(char[][] board, String word, int m, int n, int r, int c, int idx) {\n        if (idx == word.length()) {\n            return true;\n        }\n        if (r < 0 || r >= m || c < 0 || c >= n || board[r][c] != word.charAt(idx)) {\n            return false;\n        }\n        char tmp = board[r][c];\n        board[r][c] = '#';\n        boolean found = bt(board, word, m, n, r + 1, c, idx + 1)\n                || bt(board, word, m, n, r - 1, c, idx + 1)\n                || bt(board, word, m, n, r, c + 1, idx + 1)\n                || bt(board, word, m, n, r, c - 1, idx + 1);\n        board[r][c] = tmp;\n        return found;\n    }\n}",
  },
  'imp-45-word-search-ii': {
    python:
      'from typing import List\n\n\nclass TrieNode:\n    __slots__ = ("children", "word")\n\n    def __init__(self):\n        self.children = [None] * 26\n        self.word = ""\n\n\ndef findWords(board: List[List[str]], words: List[str]) -> List[str]:\n    root = TrieNode()\n    for w in words:\n        cur = root\n        for ch in w:\n            idx = ord(ch) - ord(\'a\')\n            if cur.children[idx] is None:\n                cur.children[idx] = TrieNode()\n            cur = cur.children[idx]\n        cur.word = w\n    m = len(board)\n    n = len(board[0])\n    res: List[str] = []\n    for r in range(m):\n        for c in range(n):\n            _bt(board, m, n, r, c, root, res)\n    return res\n\n\ndef _bt(board, m, n, r, c, node, res):\n    if r < 0 or r >= m or c < 0 or c >= n or board[r][c] == \'#\':\n        return\n    ch = board[r][c]\n    child = node.children[ord(ch) - ord(\'a\')]\n    if child is None:\n        return\n    if child.word != "":\n        res.append(child.word)\n        child.word = ""\n    board[r][c] = \'#\'\n    _bt(board, m, n, r + 1, c, child, res)\n    _bt(board, m, n, r - 1, c, child, res)\n    _bt(board, m, n, r, c + 1, child, res)\n    _bt(board, m, n, r, c - 1, child, res)\n    board[r][c] = ch',
    java: "import java.util.ArrayList;\nimport java.util.List;\n\nclass Solution {\n\n    static class TrieNode {\n        TrieNode[] children = new TrieNode[26];\n        String word = \"\";\n    }\n\n    public List<String> findWords(char[][] board, String[] words) {\n        TrieNode root = new TrieNode();\n        for (String w : words) {\n            TrieNode cur = root;\n            for (int i = 0; i < w.length(); i++) {\n                int idx = w.charAt(i) - 'a';\n                if (cur.children[idx] == null) {\n                    cur.children[idx] = new TrieNode();\n                }\n                cur = cur.children[idx];\n            }\n            cur.word = w;\n        }\n        int m = board.length;\n        int n = board[0].length;\n        List<String> res = new ArrayList<>();\n        for (int r = 0; r < m; r++) {\n            for (int c = 0; c < n; c++) {\n                bt(board, m, n, r, c, root, res);\n            }\n        }\n        return res;\n    }\n\n    private void bt(char[][] board, int m, int n, int r, int c, TrieNode node, List<String> res) {\n        if (r < 0 || r >= m || c < 0 || c >= n || board[r][c] == '#') {\n            return;\n        }\n        char ch = board[r][c];\n        TrieNode child = node.children[ch - 'a'];\n        if (child == null) {\n            return;\n        }\n        if (!child.word.isEmpty()) {\n            res.add(child.word);\n            child.word = \"\";\n        }\n        board[r][c] = '#';\n        bt(board, m, n, r + 1, c, child, res);\n        bt(board, m, n, r - 1, c, child, res);\n        bt(board, m, n, r, c + 1, child, res);\n        bt(board, m, n, r, c - 1, child, res);\n        board[r][c] = ch;\n    }\n}",
  },
  'imp-46-search-in-rotated-sorted-array': {
    python:
      'from typing import List\n\n\ndef search_rotated(a: List[int], key: int) -> int:\n    low, high = 0, len(a) - 1\n    while low <= high:\n        mid = low + (high - low) // 2\n        if a[mid] == key:\n            return mid\n        if a[low] <= a[mid]:\n            if a[low] <= key < a[mid]:\n                high = mid - 1\n            else:\n                low = mid + 1\n        else:\n            if a[mid] < key <= a[high]:\n                low = mid + 1\n            else:\n                high = mid - 1\n    return -1',
    java: 'class Solution {\n    public int searchRotated(int[] a, int key) {\n        int low = 0, high = a.length - 1;\n        while (low <= high) {\n            int mid = low + (high - low) / 2;\n            if (a[mid] == key) {\n                return mid;\n            }\n            if (a[low] <= a[mid]) {\n                if (a[low] <= key && key < a[mid]) {\n                    high = mid - 1;\n                } else {\n                    low = mid + 1;\n                }\n            } else {\n                if (a[mid] < key && key <= a[high]) {\n                    low = mid + 1;\n                } else {\n                    high = mid - 1;\n                }\n            }\n        }\n        return -1;\n    }\n}',
  },
  'imp-47-maximum-length-of-ribbon-cut': {
    python:
      'from typing import List\n\n\ndef cut_ribbons(ribbons: List[int], k: int) -> int:\n    low, high = 1, 0\n    for r in ribbons:\n        if r > high:\n            high = r\n    res = 0\n    while low <= high:\n        mid = low + (high - low) // 2\n        cnt = 0\n        for r in ribbons:\n            cnt += r // mid\n        if cnt >= k:\n            res = mid\n            low = mid + 1\n        else:\n            high = mid - 1\n    return res',
    java: 'class Solution {\n    public int cutRibbons(int[] ribbons, int k) {\n        int low = 1, high = 0;\n        for (int r : ribbons) {\n            if (r > high) {\n                high = r;\n            }\n        }\n        int res = 0;\n        while (low <= high) {\n            int mid = low + (high - low) / 2;\n            int cnt = 0;\n            for (int r : ribbons) {\n                cnt += r / mid;\n            }\n            if (cnt >= k) {\n                res = mid;\n                low = mid + 1;\n            } else {\n                high = mid - 1;\n            }\n        }\n        return res;\n    }\n}',
  },
  'imp-48-find-smallest-letter-greater-than-target': {
    python:
      'from typing import List\n\n\ndef first_larger_than(a: List[int], key: int) -> int:\n    low, high = 0, len(a) - 1\n    res = -1\n    while low <= high:\n        mid = low + (high - low) // 2\n        if a[mid] > key:\n            res = mid\n            high = mid - 1\n        else:\n            low = mid + 1\n    if res == -1:\n        return -1\n    return a[res]',
    java: 'class Solution {\n    int firstLargerThan(int[] a, int key) {\n        int low = 0, high = a.length - 1;\n        int res = -1;\n        while (low <= high) {\n            int mid = low + (high - low) / 2;\n            if (a[mid] > key) {\n                res = mid;\n                high = mid - 1;\n            } else {\n                low = mid + 1;\n            }\n        }\n        if (res == -1) {\n            return -1;\n        }\n        return a[res];\n    }\n}',
  },
  'imp-49-kth-largest-element-in-an-array': {
    python:
      'from typing import List\n\n\ndef kth_largest(a: List[int], k: int) -> int:\n    n = len(a)\n    arr = a[:]\n    return bt_quick_select(arr, 0, n - 1, n + 1 - k)\n\n\ndef kth_smallest(a: List[int], k: int) -> int:\n    n = len(a)\n    arr = a[:]\n    return bt_quick_select(arr, 0, n - 1, k)\n\n\ndef bt_quick_select(a: List[int], start: int, end: int, k: int) -> int:\n    if start == end:\n        return a[start]\n    pivot_idx = bt_partition(a, start, end)\n    if pivot_idx == k - 1:\n        return a[pivot_idx]\n    if k - 1 < pivot_idx:\n        return bt_quick_select(a, start, pivot_idx - 1, k)\n    return bt_quick_select(a, pivot_idx + 1, end, k)\n\n\ndef bt_partition(a: List[int], start: int, end: int) -> int:\n    pivot = a[start]\n    pos = start\n    for i in range(start + 1, end + 1):\n        if a[i] < pivot:\n            pos += 1\n            a[pos], a[i] = a[i], a[pos]\n    a[start], a[pos] = a[pos], a[start]\n    return pos\n',
    java: 'class Solution {\n\n    int kthLargest(int[] a, int k) {\n        int n = a.length;\n        int[] arr = new int[n];\n        System.arraycopy(a, 0, arr, 0, n);\n        return btQuickSelect(arr, 0, n - 1, n + 1 - k);\n    }\n\n    int kthSmallest(int[] a, int k) {\n        int n = a.length;\n        int[] arr = new int[n];\n        System.arraycopy(a, 0, arr, 0, n);\n        return btQuickSelect(arr, 0, n - 1, k);\n    }\n\n    int btQuickSelect(int[] a, int start, int end, int k) {\n        if (start == end) {\n            return a[start];\n        }\n        int pivotIdx = btPartition(a, start, end);\n        if (pivotIdx == k - 1) {\n            return a[pivotIdx];\n        }\n        if (k - 1 < pivotIdx) {\n            return btQuickSelect(a, start, pivotIdx - 1, k);\n        }\n        return btQuickSelect(a, pivotIdx + 1, end, k);\n    }\n\n    int btPartition(int[] a, int start, int end) {\n        int pivot = a[start];\n        int pos = start;\n        for (int i = start + 1; i <= end; i++) {\n            if (a[i] < pivot) {\n                pos++;\n                int tmp = a[pos];\n                a[pos] = a[i];\n                a[i] = tmp;\n            }\n        }\n        int tmp = a[start];\n        a[start] = a[pos];\n        a[pos] = tmp;\n        return pos;\n    }\n}\n',
  },
  'imp-50-find-right-interval': {
    python:
      'from typing import List\n\n\ndef first_smaller_than(a: List[int], key: int) -> int:\n    low, high = 0, len(a) - 1\n    res = -1\n    while low <= high:\n        mid = low + (high - low) // 2\n        if a[mid] < key:\n            res = mid\n            low = mid + 1\n        else:\n            high = mid - 1\n    if res == -1:\n        return -1\n    return a[res]',
    java: 'class Solution {\n    int firstSmallerThan(int[] a, int key) {\n        int low = 0, high = a.length - 1;\n        int res = -1;\n        while (low <= high) {\n            int mid = low + (high - low) / 2;\n            if (a[mid] < key) {\n                res = mid;\n                low = mid + 1;\n            } else {\n                high = mid - 1;\n            }\n        }\n        if (res == -1) {\n            return -1;\n        }\n        return a[res];\n    }\n}',
  },
  'imp-52-missing-number': {
    python:
      'def find_missing_in_consec_nums(a):\n    low, high = 0, len(a) - 1\n    while low <= high:\n        mid = low + (high - low) // 2\n        expected = a[0] + mid\n        if mid > 0 and a[mid - 1] == a[0] + mid - 1 and a[mid] != expected:\n            return expected\n        if a[mid] == expected:\n            low = mid + 1\n        else:\n            high = mid - 1\n    return a[0] + low',
    java: 'class Solution {\n    int findMissingInConsecNums(int[] a) {\n        int low = 0, high = a.length - 1;\n        while (low <= high) {\n            int mid = low + (high - low) / 2;\n            int expected = a[0] + mid;\n            if (mid > 0 && a[mid - 1] == a[0] + mid - 1 && a[mid] != expected) {\n                return expected;\n            }\n            if (a[mid] == expected) {\n                low = mid + 1;\n            } else {\n                high = mid - 1;\n            }\n        }\n        return a[0] + low;\n    }\n}',
  },
  'imp-53-find-first-and-last-position-of-element-in-sorte': {
    python:
      'from typing import List\n\n\ndef count_occurrence(a: List[int], key: int) -> int:\n    if len(a) == 0:\n        return 0\n    left = bt_first_greater_or_equal(a, key)\n    if left == len(a) or a[left] != key:\n        return 0\n    right = bt_first_greater(a, key)\n    return right - left\n\n\ndef bt_first_greater_or_equal(a: List[int], key: int) -> int:\n    low, high = 0, len(a) - 1\n    while low < high:\n        mid = low + (high - low) // 2\n        if a[mid] < key:\n            low = mid + 1\n        else:\n            high = mid\n    if a[low] < key:\n        return len(a)\n    return low\n\n\ndef bt_first_greater(a: List[int], key: int) -> int:\n    low, high = 0, len(a)\n    while low < high:\n        mid = low + (high - low) // 2\n        if a[mid] <= key:\n            low = mid + 1\n        else:\n            high = mid\n    return low\n\n\ndef search_range(a: List[int], key: int) -> List[int]:\n    cnt = count_occurrence(a, key)\n    if cnt == 0:\n        return [-1, -1]\n    left = bt_first_greater_or_equal(a, key)\n    return [left, left + cnt - 1]',
    java: 'class Solution {\n\n    int countOccurrence(int[] a, int key) {\n        if (a.length == 0) {\n            return 0;\n        }\n        int left = btFirstGreaterOrEqual(a, key);\n        if (left == a.length || a[left] != key) {\n            return 0;\n        }\n        int right = btFirstGreater(a, key);\n        return right - left;\n    }\n\n    int btFirstGreaterOrEqual(int[] a, int key) {\n        int low = 0, high = a.length - 1;\n        while (low < high) {\n            int mid = low + (high - low) / 2;\n            if (a[mid] < key) {\n                low = mid + 1;\n            } else {\n                high = mid;\n            }\n        }\n        if (a[low] < key) {\n            return a.length;\n        }\n        return low;\n    }\n\n    int btFirstGreater(int[] a, int key) {\n        int low = 0, high = a.length;\n        while (low < high) {\n            int mid = low + (high - low) / 2;\n            if (a[mid] <= key) {\n                low = mid + 1;\n            } else {\n                high = mid;\n            }\n        }\n        return low;\n    }\n\n    int[] searchRange(int[] a, int key) {\n        int cnt = countOccurrence(a, key);\n        if (cnt == 0) {\n            return new int[]{-1, -1};\n        }\n        int left = btFirstGreaterOrEqual(a, key);\n        return new int[]{left, left + cnt - 1};\n    }\n}',
  },
  'imp-54-find-peak-element': {
    python:
      'from typing import List\n\n\ndef find_peak_element(nums: List[int]) -> int:\n    low, high = 0, len(nums) - 1\n    while low < high:\n        mid = low + (high - low) // 2\n        if nums[mid] > nums[mid + 1]:\n            high = mid\n        else:\n            low = mid + 1\n    return low\n',
    java: 'class Solution {\n    public int findPeakElement(int[] nums) {\n        int low = 0, high = nums.length - 1;\n        while (low < high) {\n            int mid = low + (high - low) / 2;\n            if (nums[mid] > nums[mid + 1]) {\n                high = mid;\n            } else {\n                low = mid + 1;\n            }\n        }\n        return low;\n    }\n}\n',
  },
  'imp-55-leftmost-column-with-at-least-a-one': {
    python:
      'class BinaryMatrix:\n    def __init__(self, grid):\n        self.grid = grid\n\n    def get(self, row, col):\n        return self.grid[row][col]\n\n    def dimensions(self):\n        return [len(self.grid), len(self.grid[0])]\n\n\ndef left_most_column_with_one(bm):\n    dims = bm.dimensions()\n    m, n = dims[0], dims[1]\n    r, c = 0, n - 1\n    res = -1\n    while r < m and c >= 0:\n        if bm.get(r, c) == 1:\n            res = c\n            c -= 1\n        else:\n            r += 1\n    return res\n',
    java: 'class Solution {\n    static class BinaryMatrix {\n        int[][] grid;\n\n        BinaryMatrix(int[][] grid) {\n            this.grid = grid;\n        }\n\n        int get(int row, int col) {\n            return grid[row][col];\n        }\n\n        int[] dimensions() {\n            return new int[]{grid.length, grid[0].length};\n        }\n    }\n\n    int leftMostColumnWithOne(BinaryMatrix bm) {\n        int[] dims = bm.dimensions();\n        int m = dims[0], n = dims[1];\n        int r = 0, c = n - 1;\n        int res = -1;\n        while (r < m && c >= 0) {\n            if (bm.get(r, c) == 1) {\n                res = c;\n                c--;\n            } else {\n                r++;\n            }\n        }\n        return res;\n    }\n}\n',
  },
  'imp-57-check-if-an-original-string-exists-given-two-enc': {
    python:
      "from functools import lru_cache\n\n\ndef possibly_equals(s1: str, s2: str) -> bool:\n    m, n = len(s1), len(s2)\n    memo = {}\n\n    def bt(i: int, j: int, diff: int) -> bool:\n        if i == m and j == n:\n            return diff == 0\n        key = (i, j, diff)\n        if key in memo:\n            return memo[key]\n        res = False\n        if i < m and s1[i].isdigit():\n            num = 0\n            p = i\n            while p < m and s1[p].isdigit():\n                num = num * 10 + (ord(s1[p]) - ord('0'))\n                if bt(p + 1, j, diff + num):\n                    res = True\n                    break\n                p += 1\n        elif j < n and s2[j].isdigit():\n            num = 0\n            p = j\n            while p < n and s2[p].isdigit():\n                num = num * 10 + (ord(s2[p]) - ord('0'))\n                if bt(i, p + 1, diff - num):\n                    res = True\n                    break\n                p += 1\n        elif diff > 0 and j < n:\n            if 'a' <= s2[j] <= 'z':\n                res = bt(i, j + 1, diff - 1)\n        elif diff < 0 and i < m:\n            if 'a' <= s1[i] <= 'z':\n                res = bt(i + 1, j, diff + 1)\n        elif diff == 0 and i < m and j < n:\n            if 'a' <= s1[i] <= 'z' and 'a' <= s2[j] <= 'z':\n                res = s1[i] == s2[j] and bt(i + 1, j + 1, 0)\n        memo[key] = res\n        return res\n\n    return bt(0, 0, 0)",
    java: "import java.util.HashMap;\nimport java.util.Map;\n\nclass Solution {\n    public boolean possiblyEquals(String s1, String s2) {\n        int m = s1.length(), n = s2.length();\n        Map<Long, Boolean> memo = new HashMap<>();\n        return bt(s1, s2, 0, 0, 0, m, n, memo);\n    }\n\n    private long key(int i, int j, int diff) {\n        // diff is bounded (|diff| < ~1000 for valid inputs); encode three ints safely.\n        return ((long) i << 40) | ((long) j << 20) | ((long) (diff + 100000) & 0xFFFFF);\n    }\n\n    private boolean bt(String s1, String s2, int i, int j, int diff, int m, int n,\n                       Map<Long, Boolean> memo) {\n        if (i == m && j == n) {\n            return diff == 0;\n        }\n        long k = key(i, j, diff);\n        Boolean cached = memo.get(k);\n        if (cached != null) {\n            return cached;\n        }\n        boolean res = false;\n        if (i < m && s1.charAt(i) >= '0' && s1.charAt(i) <= '9') {\n            int num = 0;\n            for (int p = i; p < m && s1.charAt(p) >= '0' && s1.charAt(p) <= '9'; p++) {\n                num = num * 10 + (s1.charAt(p) - '0');\n                if (bt(s1, s2, p + 1, j, diff + num, m, n, memo)) {\n                    res = true;\n                    break;\n                }\n            }\n        } else if (j < n && s2.charAt(j) >= '0' && s2.charAt(j) <= '9') {\n            int num = 0;\n            for (int p = j; p < n && s2.charAt(p) >= '0' && s2.charAt(p) <= '9'; p++) {\n                num = num * 10 + (s2.charAt(p) - '0');\n                if (bt(s1, s2, i, p + 1, diff - num, m, n, memo)) {\n                    res = true;\n                    break;\n                }\n            }\n        } else if (diff > 0 && j < n) {\n            if (s2.charAt(j) >= 'a' && s2.charAt(j) <= 'z') {\n                res = bt(s1, s2, i, j + 1, diff - 1, m, n, memo);\n            }\n        } else if (diff < 0 && i < m) {\n            if (s1.charAt(i) >= 'a' && s1.charAt(i) <= 'z') {\n                res = bt(s1, s2, i + 1, j, diff + 1, m, n, memo);\n            }\n        } else if (diff == 0 && i < m && j < n) {\n            if (s1.charAt(i) >= 'a' && s1.charAt(i) <= 'z'\n                    && s2.charAt(j) >= 'a' && s2.charAt(j) <= 'z') {\n                res = s1.charAt(i) == s2.charAt(j)\n                        && bt(s1, s2, i + 1, j + 1, 0, m, n, memo);\n            }\n        }\n        memo.put(k, res);\n        return res;\n    }\n}",
  },
  'imp-59-coin-change': {
    python:
      'from typing import List\n\n\ndef coin_change(coins: List[int], amount: int) -> int:\n    INF = 1 << 30\n    dp = [0] * (amount + 1)\n    for i in range(1, amount + 1):\n        dp[i] = INF\n    for a in range(1, amount + 1):\n        for c in coins:\n            if c <= a and dp[a - c] + 1 < dp[a]:\n                dp[a] = dp[a - c] + 1\n    if dp[amount] == INF:\n        return -1\n    return dp[amount]',
    java: 'class Solution {\n    public int coinChange(int[] coins, int amount) {\n        final int INF = 1 << 30;\n        int[] dp = new int[amount + 1];\n        for (int i = 1; i <= amount; i++) {\n            dp[i] = INF;\n        }\n        for (int a = 1; a <= amount; a++) {\n            for (int c : coins) {\n                if (c <= a && dp[a - c] + 1 < dp[a]) {\n                    dp[a] = dp[a - c] + 1;\n                }\n            }\n        }\n        if (dp[amount] == INF) {\n            return -1;\n        }\n        return dp[amount];\n    }\n}',
  },
  'imp-60-coin-change-ii': {
    python:
      'from typing import List\n\n\ndef make_change(n: int, coins: List[int]) -> int:\n    if n < 0:\n        return 0\n    if n == 0:\n        return 1\n    if len(coins) == 0:\n        return 0\n    dp = [0] * (n + 1)\n    dp[0] = 1\n    for coin in coins:\n        for i in range(coin, n + 1):\n            dp[i] += dp[i - coin]\n    return dp[n]',
    java: 'class Solution {\n    public long makeChange(int n, int[] coins) {\n        if (n < 0) {\n            return 0;\n        }\n        if (n == 0) {\n            return 1;\n        }\n        if (coins.length == 0) {\n            return 0;\n        }\n        long[] dp = new long[n + 1];\n        dp[0] = 1;\n        for (int coin : coins) {\n            for (int i = coin; i <= n; i++) {\n                dp[i] += dp[i - coin];\n            }\n        }\n        return dp[n];\n    }\n}',
  },
  'imp-62-filling-bookcase-shelves': {
    python:
      'from typing import List\n\n\ndef minHeightShelves(books: List[List[int]], shelfWidth: int) -> int:\n    n = len(books)\n    dp = [0] * (n + 1)\n    for i in range(1, n + 1):\n        dp[i] = 1 << 30\n    for i in range(1, n + 1):\n        w, h = 0, 0\n        for j in range(i, 0, -1):\n            w += books[j - 1][0]\n            if w > shelfWidth:\n                break\n            if books[j - 1][1] > h:\n                h = books[j - 1][1]\n            if dp[j - 1] + h < dp[i]:\n                dp[i] = dp[j - 1] + h\n    return dp[n]',
    java: 'class Solution {\n    public int minHeightShelves(int[][] books, int shelfWidth) {\n        int n = books.length;\n        int[] dp = new int[n + 1];\n        for (int i = 1; i <= n; i++) {\n            dp[i] = 1 << 30;\n        }\n        for (int i = 1; i <= n; i++) {\n            int w = 0, h = 0;\n            for (int j = i; j >= 1; j--) {\n                w += books[j - 1][0];\n                if (w > shelfWidth) {\n                    break;\n                }\n                if (books[j - 1][1] > h) {\n                    h = books[j - 1][1];\n                }\n                if (dp[j - 1] + h < dp[i]) {\n                    dp[i] = dp[j - 1] + h;\n                }\n            }\n        }\n        return dp[n];\n    }\n}',
  },
  'imp-63-0-1-knapsack': {
    python:
      'from typing import List\n\n\ndef knapsack(weights: List[int], values: List[int], capacity: int) -> int:\n    dp = [0] * (capacity + 1)\n    for i in range(len(weights)):\n        w, v = weights[i], values[i]\n        for c in range(capacity, w - 1, -1):\n            if dp[c - w] + v > dp[c]:\n                dp[c] = dp[c - w] + v\n    return dp[capacity]',
    java: 'class Solution {\n    public int knapsack(int[] weights, int[] values, int capacity) {\n        int[] dp = new int[capacity + 1];\n        for (int i = 0; i < weights.length; i++) {\n            int w = weights[i], v = values[i];\n            for (int c = capacity; c >= w; c--) {\n                if (dp[c - w] + v > dp[c]) {\n                    dp[c] = dp[c - w] + v;\n                }\n            }\n        }\n        return dp[capacity];\n    }\n}',
  },
  'imp-64-perfect-squares': {
    python:
      'def least_square_numbers_sum_to_k(n: int) -> int:\n    dp = [0] * (n + 1)\n    for i in range(1, n + 1):\n        dp[i] = i\n        j = 1\n        while j * j <= i:\n            if dp[i - j * j] + 1 < dp[i]:\n                dp[i] = dp[i - j * j] + 1\n            j += 1\n    return dp[n]',
    java: 'class Solution {\n    public int leastSquareNumbersSumToK(int n) {\n        int[] dp = new int[n + 1];\n        for (int i = 1; i <= n; i++) {\n            dp[i] = i;\n            for (int j = 1; j * j <= i; j++) {\n                if (dp[i - j * j] + 1 < dp[i]) {\n                    dp[i] = dp[i - j * j] + 1;\n                }\n            }\n        }\n        return dp[n];\n    }\n}',
  },
  'imp-68-longest-string-chain': {
    python:
      'from typing import List\n\n\ndef longest_str_chain(words: List[str]) -> int:\n    words = sorted(words, key=len)\n    dp = {}\n    res = 1\n    for w in words:\n        dp[w] = 1\n        for i in range(len(w)):\n            pred = w[:i] + w[i + 1:]\n            v = dp.get(pred)\n            if v is not None and v + 1 > dp[w]:\n                dp[w] = v + 1\n        if dp[w] > res:\n            res = dp[w]\n    return res',
    java: 'import java.util.Arrays;\nimport java.util.HashMap;\nimport java.util.Map;\n\nclass Solution {\n    public int longestStrChain(String[] words) {\n        Arrays.sort(words, (a, b) -> Integer.compare(a.length(), b.length()));\n        Map<String, Integer> dp = new HashMap<>();\n        int res = 1;\n        for (String w : words) {\n            dp.put(w, 1);\n            for (int i = 0; i < w.length(); i++) {\n                String pred = w.substring(0, i) + w.substring(i + 1);\n                Integer v = dp.get(pred);\n                if (v != null && v + 1 > dp.get(w)) {\n                    dp.put(w, v + 1);\n                }\n            }\n            if (dp.get(w) > res) {\n                res = dp.get(w);\n            }\n        }\n        return res;\n    }\n}',
  },
  'imp-69-longest-valid-parentheses': {
    python:
      "def longest_valid_parentheses(s: str) -> int:\n    stack = [-1]\n    res = 0\n    for i in range(len(s)):\n        if s[i] == '(':\n            stack.append(i)\n        else:\n            stack.pop()\n            if not stack:\n                stack.append(i)\n            else:\n                l = i - stack[-1]\n                if l > res:\n                    res = l\n    return res",
    java: "import java.util.ArrayDeque;\nimport java.util.Deque;\n\nclass Solution {\n    public int longestValidParentheses(String s) {\n        Deque<Integer> stack = new ArrayDeque<>();\n        stack.push(-1);\n        int res = 0;\n        for (int i = 0; i < s.length(); i++) {\n            if (s.charAt(i) == '(') {\n                stack.push(i);\n            } else {\n                stack.pop();\n                if (stack.isEmpty()) {\n                    stack.push(i);\n                } else {\n                    int l = i - stack.peek();\n                    if (l > res) {\n                        res = l;\n                    }\n                }\n            }\n        }\n        return res;\n    }\n}",
  },
  'imp-70-maximal-rectangle': {
    python:
      "from typing import List\n\n\ndef max_rectangle_sum_in_matrix(matrix: List[List[str]]) -> int:\n    if len(matrix) == 0:\n        return 0\n    m, n = len(matrix), len(matrix[0])\n    heights = [0] * n\n    res = 0\n    for r in range(m):\n        for c in range(n):\n            if matrix[r][c] == '1':\n                heights[c] += 1\n            else:\n                heights[c] = 0\n        res = max(res, _bt_max_rect_histogram(heights))\n    return res\n\n\ndef _bt_max_rect_histogram(heights: List[int]) -> int:\n    stack: List[int] = []\n    res = 0\n    heights = heights + [0]\n    for i, h in enumerate(heights):\n        while stack and heights[stack[-1]] > h:\n            height = heights[stack[-1]]\n            stack.pop()\n            width = i\n            if stack:\n                width = i - stack[-1] - 1\n            res = max(res, height * width)\n        stack.append(i)\n    return res",
    java: "import java.util.ArrayDeque;\nimport java.util.Deque;\n\nclass Solution {\n\n    int maxRectangleSumInMatrix(byte[][] matrix) {\n        if (matrix.length == 0) {\n            return 0;\n        }\n        int m = matrix.length, n = matrix[0].length;\n        int[] heights = new int[n];\n        int res = 0;\n        for (int r = 0; r < m; r++) {\n            for (int c = 0; c < n; c++) {\n                if (matrix[r][c] == '1') {\n                    heights[c]++;\n                } else {\n                    heights[c] = 0;\n                }\n            }\n            res = Math.max(res, btMaxRectHistogram(heights));\n        }\n        return res;\n    }\n\n    int btMaxRectHistogram(int[] heights) {\n        Deque<Integer> stack = new ArrayDeque<>();\n        int res = 0;\n        int[] h2 = new int[heights.length + 1];\n        System.arraycopy(heights, 0, h2, 0, heights.length);\n        h2[heights.length] = 0;\n        for (int i = 0; i < h2.length; i++) {\n            int h = h2[i];\n            while (!stack.isEmpty() && h2[stack.peek()] > h) {\n                int height = h2[stack.peek()];\n                stack.pop();\n                int width = i;\n                if (!stack.isEmpty()) {\n                    width = i - stack.peek() - 1;\n                }\n                res = Math.max(res, height * width);\n            }\n            stack.push(i);\n        }\n        return res;\n    }\n}",
  },
  'imp-71-maximal-square': {
    python:
      "from typing import List\n\n\ndef max_square_area(matrix: List[List[str]]) -> int:\n    if len(matrix) == 0:\n        return 0\n    m, n = len(matrix), len(matrix[0])\n    dp = [[0] * (n + 1) for _ in range(m + 1)]\n    res = 0\n    for r in range(1, m + 1):\n        for c in range(1, n + 1):\n            if matrix[r - 1][c - 1] == '1':\n                side = min(dp[r - 1][c], dp[r][c - 1], dp[r - 1][c - 1]) + 1\n                dp[r][c] = side\n                if side > res:\n                    res = side\n    return res * res\n",
    java: "class Solution {\n    int maxSquareArea(char[][] matrix) {\n        if (matrix.length == 0) {\n            return 0;\n        }\n        int m = matrix.length, n = matrix[0].length;\n        int[][] dp = new int[m + 1][n + 1];\n        int res = 0;\n        for (int r = 1; r <= m; r++) {\n            for (int c = 1; c <= n; c++) {\n                if (matrix[r - 1][c - 1] == '1') {\n                    int side = Math.min(Math.min(dp[r - 1][c], dp[r][c - 1]), dp[r - 1][c - 1]) + 1;\n                    dp[r][c] = side;\n                    if (side > res) {\n                        res = side;\n                    }\n                }\n            }\n        }\n        return res * res;\n    }\n}\n",
  },
  'imp-72-maximum-and-sum-of-array': {
    python:
      'from typing import List, Dict\n\n\ndef maximumANDSum(nums: List[int], numSlots: int) -> int:\n    memo: Dict[int, int] = {}\n    return _bt_max_and_sum(nums, 0, 0, numSlots, memo)\n\n\ndef _bt_max_and_sum(nums: List[int], idx: int, state: int, numSlots: int, memo: Dict[int, int]) -> int:\n    if idx == len(nums):\n        return 0\n    if state in memo:\n        return memo[state]\n    res = 0\n    for slot in range(1, numSlots + 1):\n        occ = (state >> (2 * (slot - 1))) & 3\n        if occ < 2:\n            nxt = state + (1 << (2 * (slot - 1)))\n            val = (nums[idx] & slot) + _bt_max_and_sum(nums, idx + 1, nxt, numSlots, memo)\n            if val > res:\n                res = val\n    memo[state] = res\n    return res',
    java: 'import java.util.HashMap;\nimport java.util.Map;\n\nclass Solution {\n    public int maximumANDSum(int[] nums, int numSlots) {\n        Map<Integer, Integer> memo = new HashMap<>();\n        return btMaxAndSum(nums, 0, 0, numSlots, memo);\n    }\n\n    private int btMaxAndSum(int[] nums, int idx, int state, int numSlots, Map<Integer, Integer> memo) {\n        if (idx == nums.length) {\n            return 0;\n        }\n        Integer cached = memo.get(state);\n        if (cached != null) {\n            return cached;\n        }\n        int res = 0;\n        for (int slot = 1; slot <= numSlots; slot++) {\n            int occ = (state >> (2 * (slot - 1))) & 3;\n            if (occ < 2) {\n                int next = state + (1 << (2 * (slot - 1)));\n                int val = (nums[idx] & slot) + btMaxAndSum(nums, idx + 1, next, numSlots, memo);\n                if (val > res) {\n                    res = val;\n                }\n            }\n        }\n        memo.put(state, res);\n        return res;\n    }\n}',
  },
  'imp-73-maximum-number-of-points-with-cost': {
    python:
      'from typing import List\n\n\ndef maxPoints(points: List[List[int]]) -> int:\n    n = len(points[0])\n    dp = [points[0][j] for j in range(n)]\n    for i in range(1, len(points)):\n        left = [0] * n\n        left[0] = dp[0]\n        for j in range(1, n):\n            left[j] = dp[j]\n            if left[j - 1] - 1 > left[j]:\n                left[j] = left[j - 1] - 1\n        right = [0] * n\n        right[n - 1] = dp[n - 1]\n        for j in range(n - 2, -1, -1):\n            right[j] = dp[j]\n            if right[j + 1] - 1 > right[j]:\n                right[j] = right[j + 1] - 1\n        for j in range(n):\n            best = left[j]\n            if right[j] > best:\n                best = right[j]\n            dp[j] = points[i][j] + best\n    res = 0\n    for v in dp:\n        if v > res:\n            res = v\n    return res',
    java: 'class Solution {\n    public long maxPoints(int[][] points) {\n        int n = points[0].length;\n        long[] dp = new long[n];\n        for (int j = 0; j < n; j++) {\n            dp[j] = points[0][j];\n        }\n        for (int i = 1; i < points.length; i++) {\n            long[] left = new long[n];\n            left[0] = dp[0];\n            for (int j = 1; j < n; j++) {\n                left[j] = dp[j];\n                if (left[j - 1] - 1 > left[j]) {\n                    left[j] = left[j - 1] - 1;\n                }\n            }\n            long[] right = new long[n];\n            right[n - 1] = dp[n - 1];\n            for (int j = n - 2; j >= 0; j--) {\n                right[j] = dp[j];\n                if (right[j + 1] - 1 > right[j]) {\n                    right[j] = right[j + 1] - 1;\n                }\n            }\n            for (int j = 0; j < n; j++) {\n                long best = left[j];\n                if (right[j] > best) {\n                    best = right[j];\n                }\n                dp[j] = points[i][j] + best;\n            }\n        }\n        long res = 0;\n        for (long v : dp) {\n            if (v > res) {\n                res = v;\n            }\n        }\n        return res;\n    }\n}',
  },
  'imp-74-minimum-path-sum': {
    python:
      'from typing import List\n\n\ndef min_path_sum_in_matrix(grid: List[List[int]]) -> int:\n    m, n = len(grid), len(grid[0])\n    for r in range(1, m):\n        grid[r][0] += grid[r - 1][0]\n    for c in range(1, n):\n        grid[0][c] += grid[0][c - 1]\n    for r in range(1, m):\n        for c in range(1, n):\n            grid[r][c] += min(grid[r - 1][c], grid[r][c - 1])\n    return grid[m - 1][n - 1]',
    java: 'class Solution {\n    public int minPathSumInMatrix(int[][] grid) {\n        int m = grid.length, n = grid[0].length;\n        for (int r = 1; r < m; r++) {\n            grid[r][0] += grid[r - 1][0];\n        }\n        for (int c = 1; c < n; c++) {\n            grid[0][c] += grid[0][c - 1];\n        }\n        for (int r = 1; r < m; r++) {\n            for (int c = 1; c < n; c++) {\n                grid[r][c] += Math.min(grid[r - 1][c], grid[r][c - 1]);\n            }\n        }\n        return grid[m - 1][n - 1];\n    }\n}',
  },
  'imp-75-minimum-deletions-to-make-string-balanced': {
    python:
      "def minimum_deletions(s: str) -> int:\n    b_count = 0\n    dp = 0\n    for ch in s:\n        if ch == 'b':\n            b_count += 1\n        else:\n            if dp + 1 < b_count:\n                dp += 1\n            else:\n                dp = b_count\n    return dp",
    java: "class Solution {\n    public int minimumDeletions(String s) {\n        int bCount = 0;\n        int dp = 0;\n        for (int i = 0; i < s.length(); i++) {\n            if (s.charAt(i) == 'b') {\n                bCount++;\n            } else {\n                if (dp + 1 < bCount) {\n                    dp++;\n                } else {\n                    dp = bCount;\n                }\n            }\n        }\n        return dp;\n    }\n}",
  },
  'imp-76-distinct-subsequences': {
    python:
      'def number_of_distinct_subsequence(s: str, t: str) -> int:\n    m, n = len(s), len(t)\n    dp = [[0] * (n + 1) for _ in range(m + 1)]\n    for i in range(m + 1):\n        dp[i][0] = 1\n    for i in range(1, m + 1):\n        for j in range(1, n + 1):\n            dp[i][j] = dp[i - 1][j]\n            if s[i - 1] == t[j - 1]:\n                dp[i][j] += dp[i - 1][j - 1]\n    return dp[m][n]',
    java: 'class Solution {\n    public int numberOfDistinctSubsequence(String s, String t) {\n        int m = s.length(), n = t.length();\n        int[][] dp = new int[m + 1][n + 1];\n        for (int i = 0; i <= m; i++) {\n            dp[i][0] = 1;\n        }\n        for (int i = 1; i <= m; i++) {\n            for (int j = 1; j <= n; j++) {\n                dp[i][j] = dp[i - 1][j];\n                if (s.charAt(i - 1) == t.charAt(j - 1)) {\n                    dp[i][j] += dp[i - 1][j - 1];\n                }\n            }\n        }\n        return dp[m][n];\n    }\n}',
  },
  'imp-78-decode-ways': {
    python:
      "def number_of_ways_decoding_base26(s: str) -> int:\n    if len(s) == 0 or s[0] == '0':\n        return 0\n    prev, cur = 1, 1\n    for i in range(1, len(s)):\n        nxt = 0\n        if s[i] != '0':\n            nxt = cur\n        two = (ord(s[i - 1]) - ord('0')) * 10 + (ord(s[i]) - ord('0'))\n        if 10 <= two <= 26:\n            nxt += prev\n        prev, cur = cur, nxt\n    return cur",
    java: "class Solution {\n    public long numberOfWaysDecodingBase26(String s) {\n        if (s.length() == 0 || s.charAt(0) == '0') {\n            return 0;\n        }\n        long prev = 1, cur = 1;\n        for (int i = 1; i < s.length(); i++) {\n            long next = 0;\n            if (s.charAt(i) != '0') {\n                next = cur;\n            }\n            int two = (s.charAt(i - 1) - '0') * 10 + (s.charAt(i) - '0');\n            if (two >= 10 && two <= 26) {\n                next += prev;\n            }\n            prev = cur;\n            cur = next;\n        }\n        return cur;\n    }\n}",
  },
  'imp-80-race-car': {
    python:
      'from collections import deque\n\n\ndef racecar(target: int) -> int:\n    vis = {(0, 1)}\n    q = deque([(0, 1)])\n    steps = 0\n    while q:\n        steps += 1\n        for _ in range(len(q)):\n            pos, speed = q.popleft()\n            np, ns = pos + speed, speed * 2\n            if np == target:\n                return steps\n            if 0 < np < 2 * target and (np, ns) not in vis:\n                vis.add((np, ns))\n                q.append((np, ns))\n            rs = 1 if speed < 0 else -1\n            if (pos, rs) not in vis:\n                vis.add((pos, rs))\n                q.append((pos, rs))\n    return -1',
    java: 'import java.util.ArrayDeque;\nimport java.util.HashSet;\nimport java.util.Set;\n\nclass Solution {\n    public int racecar(int target) {\n        Set<Long> vis = new HashSet<>();\n        ArrayDeque<int[]> q = new ArrayDeque<>();\n        vis.add(key(0, 1));\n        q.add(new int[]{0, 1});\n        int steps = 0;\n        while (!q.isEmpty()) {\n            steps++;\n            int sz = q.size();\n            for (int i = 0; i < sz; i++) {\n                int[] cur = q.poll();\n                int pos = cur[0], speed = cur[1];\n                int np = pos + speed, ns = speed * 2;\n                if (np == target) {\n                    return steps;\n                }\n                if (np > 0 && np < 2 * target && !vis.contains(key(np, ns))) {\n                    vis.add(key(np, ns));\n                    q.add(new int[]{np, ns});\n                }\n                int rs = speed < 0 ? 1 : -1;\n                if (!vis.contains(key(pos, rs))) {\n                    vis.add(key(pos, rs));\n                    q.add(new int[]{pos, rs});\n                }\n            }\n        }\n        return -1;\n    }\n\n    private static long key(int a, int b) {\n        return ((long) a << 32) ^ (b & 0xffffffffL);\n    }\n}',
  },
  'imp-81-range-sum-query-2d-immutable': {
    python:
      'from typing import List\n\n\ndef new_range_sum_matrix(matrix: List[List[int]]) -> List[List[int]]:\n    m, n = len(matrix), len(matrix[0])\n    prefix = [[0] * (n + 1) for _ in range(m + 1)]\n    for r in range(m):\n        for c in range(n):\n            prefix[r + 1][c + 1] = (\n                matrix[r][c] + prefix[r][c + 1] + prefix[r + 1][c] - prefix[r][c]\n            )\n    return prefix\n\n\ndef range_sum_query_in_matrix(\n    prefix: List[List[int]], row1: int, col1: int, row2: int, col2: int\n) -> int:\n    return (\n        prefix[row2 + 1][col2 + 1]\n        - prefix[row1][col2 + 1]\n        - prefix[row2 + 1][col1]\n        + prefix[row1][col1]\n    )\n',
    java: 'class Solution {\n\n    int[][] newRangeSumMatrix(int[][] matrix) {\n        int m = matrix.length, n = matrix[0].length;\n        int[][] prefix = new int[m + 1][n + 1];\n        for (int r = 0; r < m; r++) {\n            for (int c = 0; c < n; c++) {\n                prefix[r + 1][c + 1] = matrix[r][c] + prefix[r][c + 1] + prefix[r + 1][c] - prefix[r][c];\n            }\n        }\n        return prefix;\n    }\n\n    int rangeSumQueryInMatrix(int[][] prefix, int row1, int col1, int row2, int col2) {\n        return prefix[row2 + 1][col2 + 1] - prefix[row1][col2 + 1] - prefix[row2 + 1][col1] + prefix[row1][col1];\n    }\n}\n',
  },
  'imp-82-regular-expression-matching': {
    python:
      "def is_match(s: str, p: str) -> bool:\n    memo = [[-1] * (len(p) + 1) for _ in range(len(s) + 1)]\n    return _bt_is_match(s, p, 0, 0, memo)\n\n\ndef _bt_is_match(s: str, p: str, i: int, j: int, memo) -> bool:\n    if memo[i][j] != -1:\n        return memo[i][j] == 1\n    if i == len(s) and j == len(p):\n        res = True\n    elif j == len(p):\n        res = False\n    else:\n        match = i < len(s) and (s[i] == p[j] or p[j] == '.')\n        if j + 1 < len(p) and p[j + 1] == '*':\n            res = _bt_is_match(s, p, i, j + 2, memo) or (\n                match and _bt_is_match(s, p, i + 1, j, memo)\n            )\n        else:\n            res = match and _bt_is_match(s, p, i + 1, j + 1, memo)\n    memo[i][j] = 1 if res else 0\n    return res",
    java: "class Solution {\n\n    public boolean isMatch(String s, String p) {\n        int[][] memo = new int[s.length() + 1][p.length() + 1];\n        for (int[] row : memo) {\n            java.util.Arrays.fill(row, -1);\n        }\n        return btIsMatch(s, p, 0, 0, memo);\n    }\n\n    private boolean btIsMatch(String s, String p, int i, int j, int[][] memo) {\n        if (memo[i][j] != -1) {\n            return memo[i][j] == 1;\n        }\n        boolean res;\n        if (i == s.length() && j == p.length()) {\n            res = true;\n        } else if (j == p.length()) {\n            res = false;\n        } else {\n            boolean match = i < s.length() && (s.charAt(i) == p.charAt(j) || p.charAt(j) == '.');\n            if (j + 1 < p.length() && p.charAt(j + 1) == '*') {\n                res = btIsMatch(s, p, i, j + 2, memo) || (match && btIsMatch(s, p, i + 1, j, memo));\n            } else {\n                res = match && btIsMatch(s, p, i + 1, j + 1, memo);\n            }\n        }\n        memo[i][j] = res ? 1 : 0;\n        return res;\n    }\n}",
  },
  'imp-83-sentence-screen-fitting': {
    python:
      'from typing import List\n\n\ndef wordsTyping(sentence: List[str], rows: int, cols: int) -> int:\n    s = " ".join(sentence) + " "\n    n = len(s)\n    start = 0\n    for _ in range(rows):\n        start += cols\n        if s[start % n] == " ":\n            start += 1\n        else:\n            while start > 0 and s[(start - 1) % n] != " ":\n                start -= 1\n    return start // n',
    java: 'class Solution {\n    public int wordsTyping(String[] sentence, int rows, int cols) {\n        String s = String.join(" ", sentence) + " ";\n        int n = s.length();\n        int start = 0;\n        for (int i = 0; i < rows; i++) {\n            start += cols;\n            if (s.charAt(start % n) == \' \') {\n                start++;\n            } else {\n                while (start > 0 && s.charAt((start - 1) % n) != \' \') {\n                    start--;\n                }\n            }\n        }\n        return start / n;\n    }\n}',
  },
  'imp-84-student-attendance-record-ii': {
    python:
      'def check_record(n):\n    mod = 1_000_000_007\n    dp = [[0, 0, 0], [0, 0, 0]]\n    dp[0][0] = 1\n    dp[0][1] = 1\n    dp[1][0] = 1\n    for _ in range(2, n + 1):\n        nd = [[0, 0, 0], [0, 0, 0]]\n        nd[0][0] = (dp[0][0] + dp[0][1] + dp[0][2]) % mod\n        nd[1][0] = (dp[1][0] + dp[1][1] + dp[1][2]) % mod\n        nd[0][1] = dp[0][0]\n        nd[0][2] = dp[0][1]\n        nd[1][1] = dp[1][0]\n        nd[1][2] = dp[1][1]\n        nd[1][0] = (nd[1][0] + dp[0][0] + dp[0][1] + dp[0][2]) % mod\n        dp = nd\n    res = 0\n    for a in range(2):\n        for l in range(3):\n            res = (res + dp[a][l]) % mod\n    return res',
    java: 'class Solution {\n    public int checkRecord(int n) {\n        final long mod = 1_000_000_007L;\n        long[][] dp = new long[2][3];\n        dp[0][0] = 1;\n        dp[0][1] = 1;\n        dp[1][0] = 1;\n        for (int i = 2; i <= n; i++) {\n            long[][] nd = new long[2][3];\n            nd[0][0] = (dp[0][0] + dp[0][1] + dp[0][2]) % mod;\n            nd[1][0] = (dp[1][0] + dp[1][1] + dp[1][2]) % mod;\n            nd[0][1] = dp[0][0];\n            nd[0][2] = dp[0][1];\n            nd[1][1] = dp[1][0];\n            nd[1][2] = dp[1][1];\n            nd[1][0] = (nd[1][0] + dp[0][0] + dp[0][1] + dp[0][2]) % mod;\n            dp = nd;\n        }\n        long res = 0;\n        for (int a = 0; a < 2; a++) {\n            for (int l = 0; l < 3; l++) {\n                res = (res + dp[a][l]) % mod;\n            }\n        }\n        return (int) res;\n    }\n}',
  },
  'imp-32-generate-binary-strings': {
    python:
      'def gen_bin_strings(n):\n    res = []\n    _bt_bin("", n, res)\n    return res\n\n\ndef _bt_bin(path, n, res):\n    if len(path.encode(\'utf-8\')) == n:\n        res.append(path)\n        return\n    _bt_bin(path + "0", n, res)\n    _bt_bin(path + "1", n, res)',
    java: 'import java.util.*;\nimport java.nio.charset.StandardCharsets;\n\nclass Solution {\n    List<String> genBinStrings(int n) {\n        List<String> res = new ArrayList<>();\n        btBin("", n, res);\n        return res;\n    }\n\n    void btBin(String path, int n, List<String> res) {\n        if (path.getBytes(StandardCharsets.UTF_8).length == n) {\n            res.add(path);\n            return;\n        }\n        btBin(path + "0", n, res);\n        btBin(path + "1", n, res);\n    }\n}',
  },
  'imp-51-missing-number-in-arithmetic-progression': {
    python:
      'def find_missing_in_ap(a):\n    n = len(a)\n    low, high = 0, n - 1\n    num = a[high] - a[low]\n    # Go integer division truncates toward zero\n    q = abs(num) // n\n    diff = q if num >= 0 else -q\n    while low <= high:\n        mid = low + (high - low) // 2\n        expected = a[0] + mid * diff\n        if a[mid] == expected:\n            low = mid + 1\n        else:\n            high = mid - 1\n    return a[0] + low * diff',
    java: 'import java.util.*;\n\nclass Solution {\n    public long findMissingInAp(long[] a) {\n        int n = a.length;\n        int low = 0, high = n - 1;\n        long diff = (a[high] - a[low]) / n; // Java long division truncates toward zero, like Go\n        while (low <= high) {\n            int mid = low + (high - low) / 2;\n            long expected = a[0] + (long) mid * diff;\n            if (a[mid] == expected) {\n                low = mid + 1;\n            } else {\n                high = mid - 1;\n            }\n        }\n        return a[0] + (long) low * diff;\n    }\n}',
  },
  'imp-56-squares-of-a-sorted-array': {
    python:
      'def _i64(x):\n    x &= (1 << 64) - 1\n    if x >= (1 << 63):\n        x -= (1 << 64)\n    return x\n\n\ndef sortSquares(a):\n    n = len(a)\n    res = [0] * n\n    i, j = 0, n - 1\n    for k in range(n - 1, -1, -1):\n        if abs(a[i]) > abs(a[j]):\n            res[k] = _i64(a[i] * a[i])\n            i += 1\n        else:\n            res[k] = _i64(a[j] * a[j])\n            j -= 1\n    return res',
    java: 'import java.util.*;\n\nclass Solution {\n    long[] sortSquares(long[] a) {\n        int n = a.length;\n        long[] res = new long[n];\n        int i = 0, j = n - 1;\n        for (int k = n - 1; k >= 0; k--) {\n            if (Math.abs(a[i]) > Math.abs(a[j])) {\n                res[k] = a[i] * a[i];\n                i++;\n            } else {\n                res[k] = a[j] * a[j];\n                j--;\n            }\n        }\n        return res;\n    }\n}',
  },
  'imp-58-climbing-stairs': {
    python:
      'def _i64(x):\n    x &= (1 << 64) - 1\n    return x - (1 << 64) if x >= (1 << 63) else x\n\n\nclass Solution:\n    def climbStairs(self, n: int) -> int:\n        if n <= 2:\n            return n\n        prev, cur = 1, 2\n        for _ in range(3, n + 1):\n            prev, cur = cur, _i64(prev + cur)\n        return cur',
    java: 'import java.util.*;\n\nclass Solution {\n    public long climbStairs(int n) {\n        if (n <= 2) {\n            return n;\n        }\n        long prev = 1, cur = 2;\n        for (int i = 3; i <= n; i++) {\n            long next = prev + cur;\n            prev = cur;\n            cur = next;\n        }\n        return cur;\n    }\n}',
  },
  'imp-61-edit-distance': {
    python:
      "def editDistance(word1: str, word2: str) -> int:\n    a = word1.encode('utf-8')\n    b = word2.encode('utf-8')\n    m, n = len(a), len(b)\n    dp = [[0] * (n + 1) for _ in range(m + 1)]\n    for i in range(m + 1):\n        dp[i][0] = i\n    for j in range(n + 1):\n        dp[0][j] = j\n    for i in range(1, m + 1):\n        for j in range(1, n + 1):\n            if a[i - 1] == b[j - 1]:\n                dp[i][j] = dp[i - 1][j - 1]\n            else:\n                dp[i][j] = 1 + min(dp[i - 1][j], dp[i][j - 1], dp[i - 1][j - 1])\n    return dp[m][n]",
    java: 'import java.nio.charset.StandardCharsets;\n\nclass Solution {\n    long editDistance(String word1, String word2) {\n        byte[] a = word1.getBytes(StandardCharsets.UTF_8);\n        byte[] b = word2.getBytes(StandardCharsets.UTF_8);\n        int m = a.length, n = b.length;\n        long[][] dp = new long[m + 1][n + 1];\n        for (int i = 0; i <= m; i++) dp[i][0] = i;\n        for (int j = 0; j <= n; j++) dp[0][j] = j;\n        for (int i = 1; i <= m; i++) {\n            for (int j = 1; j <= n; j++) {\n                if (a[i - 1] == b[j - 1]) {\n                    dp[i][j] = dp[i - 1][j - 1];\n                } else {\n                    dp[i][j] = 1 + Math.min(dp[i - 1][j], Math.min(dp[i][j - 1], dp[i - 1][j - 1]));\n                }\n            }\n        }\n        return dp[m][n];\n    }\n}',
  },
  'imp-65-longest-common-subsequence': {
    python:
      "def longest_common_sequence(text1, text2):\n    a = text1.encode('utf-8')\n    b = text2.encode('utf-8')\n    m, n = len(a), len(b)\n    dp = [[0] * (n + 1) for _ in range(m + 1)]\n    for i in range(1, m + 1):\n        for j in range(1, n + 1):\n            if a[i - 1] == b[j - 1]:\n                dp[i][j] = dp[i - 1][j - 1] + 1\n            else:\n                dp[i][j] = max(dp[i - 1][j], dp[i][j - 1])\n    return dp[m][n]",
    java: 'import java.nio.charset.StandardCharsets;\n\nclass Solution {\n    int longestCommonSequence(String text1, String text2) {\n        byte[] a = text1.getBytes(StandardCharsets.UTF_8);\n        byte[] b = text2.getBytes(StandardCharsets.UTF_8);\n        int m = a.length, n = b.length;\n        int[][] dp = new int[m + 1][n + 1];\n        for (int i = 1; i <= m; i++) {\n            for (int j = 1; j <= n; j++) {\n                if (a[i - 1] == b[j - 1]) {\n                    dp[i][j] = dp[i - 1][j - 1] + 1;\n                } else {\n                    dp[i][j] = Math.max(dp[i - 1][j], dp[i][j - 1]);\n                }\n            }\n        }\n        return dp[m][n];\n    }\n}',
  },
  'imp-66-longest-increasing-subsequence': {
    python:
      'def longest_increasing_subsequence(nums):\n    tails = []\n    for x in nums:\n        low, high = 0, len(tails)\n        while low < high:\n            mid = low + (high - low) // 2\n            if tails[mid] < x:\n                low = mid + 1\n            else:\n                high = mid\n        if low == len(tails):\n            tails.append(x)\n        else:\n            tails[low] = x\n    return len(tails)',
    java: 'import java.util.*;\n\nclass Solution {\n    int longestIncreasingSubsequence(long[] nums) {\n        long[] tails = new long[nums.length];\n        int size = 0;\n        for (long x : nums) {\n            int low = 0, high = size;\n            while (low < high) {\n                int mid = low + (high - low) / 2;\n                if (tails[mid] < x) {\n                    low = mid + 1;\n                } else {\n                    high = mid;\n                }\n            }\n            if (low == size) {\n                tails[size] = x;\n                size++;\n            } else {\n                tails[low] = x;\n            }\n        }\n        return size;\n    }\n}',
  },
  'imp-67-longest-palindromic-subsequence': {
    python:
      "def longest_palindromic_subsequence(s):\n    b = s.encode('utf-8')\n    n = len(b)\n    if n == 0:\n        return 0\n    dp = [[0] * n for _ in range(n)]\n    for i in range(n):\n        dp[i][i] = 1\n    for length in range(2, n + 1):\n        i = 0\n        while i + length - 1 < n:\n            j = i + length - 1\n            if b[i] == b[j]:\n                dp[i][j] = dp[i + 1][j - 1] + 2\n            else:\n                dp[i][j] = max(dp[i + 1][j], dp[i][j - 1])\n            i += 1\n    return dp[0][n - 1]",
    java: 'import java.nio.charset.StandardCharsets;\n\nclass Solution {\n    long longestPalindromicSubsequence(String s) {\n        byte[] b = s.getBytes(StandardCharsets.UTF_8);\n        int n = b.length;\n        if (n == 0) {\n            return 0;\n        }\n        long[][] dp = new long[n][n];\n        for (int i = 0; i < n; i++) {\n            dp[i][i] = 1;\n        }\n        for (int length = 2; length <= n; length++) {\n            for (int i = 0; i + length - 1 < n; i++) {\n                int j = i + length - 1;\n                if (b[i] == b[j]) {\n                    dp[i][j] = dp[i + 1][j - 1] + 2;\n                } else {\n                    dp[i][j] = Math.max(dp[i + 1][j], dp[i][j - 1]);\n                }\n            }\n        }\n        return dp[0][n - 1];\n    }\n}',
  },
  'imp-77-unique-paths': {
    python:
      'def numberOfUniquePathsIn(m, n):\n    dp = [1] * n\n    for i in range(1, m):\n        for j in range(1, n):\n            dp[j] += dp[j - 1]\n    return dp[n - 1]',
    java: 'import java.util.*;\n\nclass Solution {\n    long numberOfUniquePathsIn(int m, int n) {\n        long[] dp = new long[n];\n        for (int j = 0; j < n; j++) {\n            dp[j] = 1;\n        }\n        for (int i = 1; i < m; i++) {\n            for (int j = 1; j < n; j++) {\n                dp[j] += dp[j - 1];\n            }\n        }\n        return dp[n - 1];\n    }\n}',
  },
  'imp-79-partition-array-into-two-arrays-to-minimize-sum-': {
    python:
      'import bisect\n\n\ndef _abs_int(x):\n    return -x if x < 0 else x\n\n\ndef _gen_subset_sums(arr):\n    k = len(arr)\n    sums = [[] for _ in range(k + 1)]\n    for mask in range(1 << k):\n        s = 0\n        cnt = 0\n        for i in range(k):\n            if mask & (1 << i):\n                s += arr[i]\n                cnt += 1\n        sums[cnt].append(s)\n    return sums\n\n\ndef minimum_difference(nums):\n    n = len(nums) // 2\n    total = 0\n    for x in nums:\n        total += x\n    left, right = nums[:n], nums[n:]\n    ls = _gen_subset_sums(left)\n    rs = _gen_subset_sums(right)\n    for i in range(len(rs)):\n        rs[i].sort()\n    res = 1 << 30\n    target = _go_int_div(total, 2)\n    for sz in range(n + 1):\n        r_sz = n - sz\n        for l_sum in ls[sz]:\n            t = target - l_sum\n            arr = rs[r_sz]\n            idx = bisect.bisect_left(arr, t)\n            if idx < len(arr):\n                d = _abs_int(total - 2 * (l_sum + arr[idx]))\n                if d < res:\n                    res = d\n            if idx > 0:\n                d = _abs_int(total - 2 * (l_sum + arr[idx - 1]))\n                if d < res:\n                    res = d\n    return res\n\n\ndef _go_int_div(a, b):\n    # Go integer division truncates toward zero\n    q = a // b\n    if (a % b != 0) and ((a < 0) != (b < 0)):\n        q += 1\n    return q',
    java: 'import java.util.*;\n\nclass Solution {\n    public long minimumDifference(long[] nums) {\n        int n = nums.length / 2;\n        long total = 0;\n        for (long x : nums) total += x;\n        long[] left = Arrays.copyOfRange(nums, 0, n);\n        long[] right = Arrays.copyOfRange(nums, n, nums.length);\n        long[][] ls = genSubsetSums(left);\n        long[][] rs = genSubsetSums(right);\n        for (int i = 0; i < rs.length; i++) Arrays.sort(rs[i]);\n        long res = 1L << 30;\n        long target = total / 2; // long division truncates toward zero, matching Go\n        for (int sz = 0; sz <= n; sz++) {\n            int rSz = n - sz;\n            for (long lSum : ls[sz]) {\n                long t = target - lSum;\n                long[] arr = rs[rSz];\n                int idx = lowerBound(arr, t);\n                if (idx < arr.length) {\n                    long d = Math.abs(total - 2 * (lSum + arr[idx]));\n                    if (d < res) res = d;\n                }\n                if (idx > 0) {\n                    long d = Math.abs(total - 2 * (lSum + arr[idx - 1]));\n                    if (d < res) res = d;\n                }\n            }\n        }\n        return res;\n    }\n\n    private long[][] genSubsetSums(long[] arr) {\n        int k = arr.length;\n        List<List<Long>> sums = new ArrayList<>();\n        for (int i = 0; i <= k; i++) sums.add(new ArrayList<>());\n        for (int mask = 0; mask < (1 << k); mask++) {\n            long s = 0; int cnt = 0;\n            for (int i = 0; i < k; i++) {\n                if ((mask & (1 << i)) != 0) { s += arr[i]; cnt++; }\n            }\n            sums.get(cnt).add(s);\n        }\n        long[][] out = new long[k + 1][];\n        for (int i = 0; i <= k; i++) {\n            List<Long> lst = sums.get(i);\n            long[] a = new long[lst.size()];\n            for (int j = 0; j < lst.size(); j++) a[j] = lst.get(j);\n            out[i] = a;\n        }\n        return out;\n    }\n\n    // Returns first index i where arr[i] >= t (Go sort.Search / bisect_left)\n    private int lowerBound(long[] arr, long t) {\n        int lo = 0, hi = arr.length;\n        while (lo < hi) {\n            int mid = lo + (hi - lo) / 2;\n            if (arr[mid] >= t) hi = mid; else lo = mid + 1;\n        }\n        return lo;\n    }\n}',
  },
  'imp-85-valid-palindrome-iii': {
    python:
      "def is_valid_palindrome(s: str, k: int) -> bool:\n    b = s.encode('utf-8')\n    n = len(b)\n    dp = [1] * n\n    for i in range(n - 2, -1, -1):\n        prev = 0\n        for j in range(i + 1, n):\n            tmp = dp[j]\n            if b[i] == b[j]:\n                dp[j] = prev + 2\n            elif dp[j - 1] > dp[j]:\n                dp[j] = dp[j - 1]\n            prev = tmp\n    return n - dp[n - 1] <= k",
    java: 'import java.nio.charset.StandardCharsets;\n\nclass Solution {\n    public boolean isValidPalindrome(String s, int k) {\n        byte[] b = s.getBytes(StandardCharsets.UTF_8);\n        int n = b.length;\n        long[] dp = new long[n];\n        for (int i = 0; i < n; i++) {\n            dp[i] = 1;\n        }\n        for (int i = n - 2; i >= 0; i--) {\n            long prev = 0;\n            for (int j = i + 1; j < n; j++) {\n                long tmp = dp[j];\n                if (b[i] == b[j]) {\n                    dp[j] = prev + 2;\n                } else if (dp[j - 1] > dp[j]) {\n                    dp[j] = dp[j - 1];\n                }\n                prev = tmp;\n            }\n        }\n        return n - dp[n - 1] <= k;\n    }\n}',
  },
};
